package Paws::KinesisVideo::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type KinesisVideo_AccountStreamLimitExceededException, { class => 'Paws::KinesisVideo::AccountStreamLimitExceededException' };
  class_type KinesisVideo_ClientLimitExceededException, { class => 'Paws::KinesisVideo::ClientLimitExceededException' };
  class_type KinesisVideo_CreateStreamInput, { class => 'Paws::KinesisVideo::CreateStreamInput' };
  class_type KinesisVideo_CreateStreamOutput, { class => 'Paws::KinesisVideo::CreateStreamOutput' };
  class_type KinesisVideo_DeleteStreamInput, { class => 'Paws::KinesisVideo::DeleteStreamInput' };
  class_type KinesisVideo_DeleteStreamOutput, { class => 'Paws::KinesisVideo::DeleteStreamOutput' };
  class_type KinesisVideo_DescribeStreamInput, { class => 'Paws::KinesisVideo::DescribeStreamInput' };
  class_type KinesisVideo_DescribeStreamOutput, { class => 'Paws::KinesisVideo::DescribeStreamOutput' };
  class_type KinesisVideo_DeviceStreamLimitExceededException, { class => 'Paws::KinesisVideo::DeviceStreamLimitExceededException' };
  class_type KinesisVideo_GetDataEndpointInput, { class => 'Paws::KinesisVideo::GetDataEndpointInput' };
  class_type KinesisVideo_GetDataEndpointOutput, { class => 'Paws::KinesisVideo::GetDataEndpointOutput' };
  class_type KinesisVideo_InvalidArgumentException, { class => 'Paws::KinesisVideo::InvalidArgumentException' };
  class_type KinesisVideo_InvalidDeviceException, { class => 'Paws::KinesisVideo::InvalidDeviceException' };
  class_type KinesisVideo_InvalidResourceFormatException, { class => 'Paws::KinesisVideo::InvalidResourceFormatException' };
  class_type KinesisVideo_ListStreamsInput, { class => 'Paws::KinesisVideo::ListStreamsInput' };
  class_type KinesisVideo_ListStreamsOutput, { class => 'Paws::KinesisVideo::ListStreamsOutput' };
  class_type KinesisVideo_ListTagsForStreamInput, { class => 'Paws::KinesisVideo::ListTagsForStreamInput' };
  class_type KinesisVideo_ListTagsForStreamOutput, { class => 'Paws::KinesisVideo::ListTagsForStreamOutput' };
  class_type KinesisVideo_NotAuthorizedException, { class => 'Paws::KinesisVideo::NotAuthorizedException' };
  class_type KinesisVideo_ResourceInUseException, { class => 'Paws::KinesisVideo::ResourceInUseException' };
  class_type KinesisVideo_ResourceNotFoundException, { class => 'Paws::KinesisVideo::ResourceNotFoundException' };
  class_type KinesisVideo_ResourceTags, { class => 'Paws::KinesisVideo::ResourceTags' };
  class_type KinesisVideo_StreamInfo, { class => 'Paws::KinesisVideo::StreamInfo' };
  class_type KinesisVideo_StreamNameCondition, { class => 'Paws::KinesisVideo::StreamNameCondition' };
  class_type KinesisVideo_TagsPerResourceExceededLimitException, { class => 'Paws::KinesisVideo::TagsPerResourceExceededLimitException' };
  class_type KinesisVideo_TagStreamInput, { class => 'Paws::KinesisVideo::TagStreamInput' };
  class_type KinesisVideo_TagStreamOutput, { class => 'Paws::KinesisVideo::TagStreamOutput' };
  class_type KinesisVideo_UntagStreamInput, { class => 'Paws::KinesisVideo::UntagStreamInput' };
  class_type KinesisVideo_UntagStreamOutput, { class => 'Paws::KinesisVideo::UntagStreamOutput' };
  class_type KinesisVideo_UpdateDataRetentionInput, { class => 'Paws::KinesisVideo::UpdateDataRetentionInput' };
  class_type KinesisVideo_UpdateDataRetentionOutput, { class => 'Paws::KinesisVideo::UpdateDataRetentionOutput' };
  class_type KinesisVideo_UpdateStreamInput, { class => 'Paws::KinesisVideo::UpdateStreamInput' };
  class_type KinesisVideo_UpdateStreamOutput, { class => 'Paws::KinesisVideo::UpdateStreamOutput' };
  class_type KinesisVideo_VersionMismatchException, { class => 'Paws::KinesisVideo::VersionMismatchException' };

1;
