package Paws::Athena::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Athena_BatchGetNamedQueryInput, { class => 'Paws::Athena::BatchGetNamedQueryInput' };
  class_type Athena_BatchGetNamedQueryOutput, { class => 'Paws::Athena::BatchGetNamedQueryOutput' };
  class_type Athena_BatchGetQueryExecutionInput, { class => 'Paws::Athena::BatchGetQueryExecutionInput' };
  class_type Athena_BatchGetQueryExecutionOutput, { class => 'Paws::Athena::BatchGetQueryExecutionOutput' };
  class_type Athena_ColumnInfo, { class => 'Paws::Athena::ColumnInfo' };
  class_type Athena_CreateNamedQueryInput, { class => 'Paws::Athena::CreateNamedQueryInput' };
  class_type Athena_CreateNamedQueryOutput, { class => 'Paws::Athena::CreateNamedQueryOutput' };
  class_type Athena_CreateWorkGroupInput, { class => 'Paws::Athena::CreateWorkGroupInput' };
  class_type Athena_CreateWorkGroupOutput, { class => 'Paws::Athena::CreateWorkGroupOutput' };
  class_type Athena_Datum, { class => 'Paws::Athena::Datum' };
  class_type Athena_DeleteNamedQueryInput, { class => 'Paws::Athena::DeleteNamedQueryInput' };
  class_type Athena_DeleteNamedQueryOutput, { class => 'Paws::Athena::DeleteNamedQueryOutput' };
  class_type Athena_DeleteWorkGroupInput, { class => 'Paws::Athena::DeleteWorkGroupInput' };
  class_type Athena_DeleteWorkGroupOutput, { class => 'Paws::Athena::DeleteWorkGroupOutput' };
  class_type Athena_EncryptionConfiguration, { class => 'Paws::Athena::EncryptionConfiguration' };
  class_type Athena_GetNamedQueryInput, { class => 'Paws::Athena::GetNamedQueryInput' };
  class_type Athena_GetNamedQueryOutput, { class => 'Paws::Athena::GetNamedQueryOutput' };
  class_type Athena_GetQueryExecutionInput, { class => 'Paws::Athena::GetQueryExecutionInput' };
  class_type Athena_GetQueryExecutionOutput, { class => 'Paws::Athena::GetQueryExecutionOutput' };
  class_type Athena_GetQueryResultsInput, { class => 'Paws::Athena::GetQueryResultsInput' };
  class_type Athena_GetQueryResultsOutput, { class => 'Paws::Athena::GetQueryResultsOutput' };
  class_type Athena_GetWorkGroupInput, { class => 'Paws::Athena::GetWorkGroupInput' };
  class_type Athena_GetWorkGroupOutput, { class => 'Paws::Athena::GetWorkGroupOutput' };
  class_type Athena_InternalServerException, { class => 'Paws::Athena::InternalServerException' };
  class_type Athena_InvalidRequestException, { class => 'Paws::Athena::InvalidRequestException' };
  class_type Athena_ListNamedQueriesInput, { class => 'Paws::Athena::ListNamedQueriesInput' };
  class_type Athena_ListNamedQueriesOutput, { class => 'Paws::Athena::ListNamedQueriesOutput' };
  class_type Athena_ListQueryExecutionsInput, { class => 'Paws::Athena::ListQueryExecutionsInput' };
  class_type Athena_ListQueryExecutionsOutput, { class => 'Paws::Athena::ListQueryExecutionsOutput' };
  class_type Athena_ListTagsForResourceInput, { class => 'Paws::Athena::ListTagsForResourceInput' };
  class_type Athena_ListTagsForResourceOutput, { class => 'Paws::Athena::ListTagsForResourceOutput' };
  class_type Athena_ListWorkGroupsInput, { class => 'Paws::Athena::ListWorkGroupsInput' };
  class_type Athena_ListWorkGroupsOutput, { class => 'Paws::Athena::ListWorkGroupsOutput' };
  class_type Athena_NamedQuery, { class => 'Paws::Athena::NamedQuery' };
  class_type Athena_QueryExecution, { class => 'Paws::Athena::QueryExecution' };
  class_type Athena_QueryExecutionContext, { class => 'Paws::Athena::QueryExecutionContext' };
  class_type Athena_QueryExecutionStatistics, { class => 'Paws::Athena::QueryExecutionStatistics' };
  class_type Athena_QueryExecutionStatus, { class => 'Paws::Athena::QueryExecutionStatus' };
  class_type Athena_ResourceNotFoundException, { class => 'Paws::Athena::ResourceNotFoundException' };
  class_type Athena_ResultConfiguration, { class => 'Paws::Athena::ResultConfiguration' };
  class_type Athena_ResultConfigurationUpdates, { class => 'Paws::Athena::ResultConfigurationUpdates' };
  class_type Athena_ResultSet, { class => 'Paws::Athena::ResultSet' };
  class_type Athena_ResultSetMetadata, { class => 'Paws::Athena::ResultSetMetadata' };
  class_type Athena_Row, { class => 'Paws::Athena::Row' };
  class_type Athena_StartQueryExecutionInput, { class => 'Paws::Athena::StartQueryExecutionInput' };
  class_type Athena_StartQueryExecutionOutput, { class => 'Paws::Athena::StartQueryExecutionOutput' };
  class_type Athena_StopQueryExecutionInput, { class => 'Paws::Athena::StopQueryExecutionInput' };
  class_type Athena_StopQueryExecutionOutput, { class => 'Paws::Athena::StopQueryExecutionOutput' };
  class_type Athena_Tag, { class => 'Paws::Athena::Tag' };
  class_type Athena_TagResourceInput, { class => 'Paws::Athena::TagResourceInput' };
  class_type Athena_TagResourceOutput, { class => 'Paws::Athena::TagResourceOutput' };
  class_type Athena_TooManyRequestsException, { class => 'Paws::Athena::TooManyRequestsException' };
  class_type Athena_UnprocessedNamedQueryId, { class => 'Paws::Athena::UnprocessedNamedQueryId' };
  class_type Athena_UnprocessedQueryExecutionId, { class => 'Paws::Athena::UnprocessedQueryExecutionId' };
  class_type Athena_UntagResourceInput, { class => 'Paws::Athena::UntagResourceInput' };
  class_type Athena_UntagResourceOutput, { class => 'Paws::Athena::UntagResourceOutput' };
  class_type Athena_UpdateWorkGroupInput, { class => 'Paws::Athena::UpdateWorkGroupInput' };
  class_type Athena_UpdateWorkGroupOutput, { class => 'Paws::Athena::UpdateWorkGroupOutput' };
  class_type Athena_WorkGroup, { class => 'Paws::Athena::WorkGroup' };
  class_type Athena_WorkGroupConfiguration, { class => 'Paws::Athena::WorkGroupConfiguration' };
  class_type Athena_WorkGroupConfigurationUpdates, { class => 'Paws::Athena::WorkGroupConfigurationUpdates' };
  class_type Athena_WorkGroupSummary, { class => 'Paws::Athena::WorkGroupSummary' };

1;
