package Paws::Polly::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Polly_DeleteLexiconInput, { class => 'Paws::Polly::DeleteLexiconInput' };
  class_type Polly_DeleteLexiconOutput, { class => 'Paws::Polly::DeleteLexiconOutput' };
  class_type Polly_DescribeVoicesInput, { class => 'Paws::Polly::DescribeVoicesInput' };
  class_type Polly_DescribeVoicesOutput, { class => 'Paws::Polly::DescribeVoicesOutput' };
  class_type Polly_GetLexiconInput, { class => 'Paws::Polly::GetLexiconInput' };
  class_type Polly_GetLexiconOutput, { class => 'Paws::Polly::GetLexiconOutput' };
  class_type Polly_GetSpeechSynthesisTaskInput, { class => 'Paws::Polly::GetSpeechSynthesisTaskInput' };
  class_type Polly_GetSpeechSynthesisTaskOutput, { class => 'Paws::Polly::GetSpeechSynthesisTaskOutput' };
  class_type Polly_InvalidLexiconException, { class => 'Paws::Polly::InvalidLexiconException' };
  class_type Polly_InvalidNextTokenException, { class => 'Paws::Polly::InvalidNextTokenException' };
  class_type Polly_InvalidS3BucketException, { class => 'Paws::Polly::InvalidS3BucketException' };
  class_type Polly_InvalidS3KeyException, { class => 'Paws::Polly::InvalidS3KeyException' };
  class_type Polly_InvalidSampleRateException, { class => 'Paws::Polly::InvalidSampleRateException' };
  class_type Polly_InvalidSnsTopicArnException, { class => 'Paws::Polly::InvalidSnsTopicArnException' };
  class_type Polly_InvalidSsmlException, { class => 'Paws::Polly::InvalidSsmlException' };
  class_type Polly_InvalidTaskIdException, { class => 'Paws::Polly::InvalidTaskIdException' };
  class_type Polly_LanguageNotSupportedException, { class => 'Paws::Polly::LanguageNotSupportedException' };
  class_type Polly_Lexicon, { class => 'Paws::Polly::Lexicon' };
  class_type Polly_LexiconAttributes, { class => 'Paws::Polly::LexiconAttributes' };
  class_type Polly_LexiconDescription, { class => 'Paws::Polly::LexiconDescription' };
  class_type Polly_LexiconNotFoundException, { class => 'Paws::Polly::LexiconNotFoundException' };
  class_type Polly_LexiconSizeExceededException, { class => 'Paws::Polly::LexiconSizeExceededException' };
  class_type Polly_ListLexiconsInput, { class => 'Paws::Polly::ListLexiconsInput' };
  class_type Polly_ListLexiconsOutput, { class => 'Paws::Polly::ListLexiconsOutput' };
  class_type Polly_ListSpeechSynthesisTasksInput, { class => 'Paws::Polly::ListSpeechSynthesisTasksInput' };
  class_type Polly_ListSpeechSynthesisTasksOutput, { class => 'Paws::Polly::ListSpeechSynthesisTasksOutput' };
  class_type Polly_MarksNotSupportedForFormatException, { class => 'Paws::Polly::MarksNotSupportedForFormatException' };
  class_type Polly_MaxLexemeLengthExceededException, { class => 'Paws::Polly::MaxLexemeLengthExceededException' };
  class_type Polly_MaxLexiconsNumberExceededException, { class => 'Paws::Polly::MaxLexiconsNumberExceededException' };
  class_type Polly_PutLexiconInput, { class => 'Paws::Polly::PutLexiconInput' };
  class_type Polly_PutLexiconOutput, { class => 'Paws::Polly::PutLexiconOutput' };
  class_type Polly_ServiceFailureException, { class => 'Paws::Polly::ServiceFailureException' };
  class_type Polly_SsmlMarksNotSupportedForTextTypeException, { class => 'Paws::Polly::SsmlMarksNotSupportedForTextTypeException' };
  class_type Polly_StartSpeechSynthesisTaskInput, { class => 'Paws::Polly::StartSpeechSynthesisTaskInput' };
  class_type Polly_StartSpeechSynthesisTaskOutput, { class => 'Paws::Polly::StartSpeechSynthesisTaskOutput' };
  class_type Polly_SynthesisTask, { class => 'Paws::Polly::SynthesisTask' };
  class_type Polly_SynthesisTaskNotFoundException, { class => 'Paws::Polly::SynthesisTaskNotFoundException' };
  class_type Polly_SynthesizeSpeechInput, { class => 'Paws::Polly::SynthesizeSpeechInput' };
  class_type Polly_SynthesizeSpeechOutput, { class => 'Paws::Polly::SynthesizeSpeechOutput' };
  class_type Polly_TextLengthExceededException, { class => 'Paws::Polly::TextLengthExceededException' };
  class_type Polly_UnsupportedPlsAlphabetException, { class => 'Paws::Polly::UnsupportedPlsAlphabetException' };
  class_type Polly_UnsupportedPlsLanguageException, { class => 'Paws::Polly::UnsupportedPlsLanguageException' };
  class_type Polly_Voice, { class => 'Paws::Polly::Voice' };

1;
