package Paws::ComprehendMedical::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ComprehendMedical_Attribute, { class => 'Paws::ComprehendMedical::Attribute' };
  class_type ComprehendMedical_ComprehendMedicalAsyncJobFilter, { class => 'Paws::ComprehendMedical::ComprehendMedicalAsyncJobFilter' };
  class_type ComprehendMedical_ComprehendMedicalAsyncJobProperties, { class => 'Paws::ComprehendMedical::ComprehendMedicalAsyncJobProperties' };
  class_type ComprehendMedical_DescribeEntitiesDetectionV2JobRequest, { class => 'Paws::ComprehendMedical::DescribeEntitiesDetectionV2JobRequest' };
  class_type ComprehendMedical_DescribeEntitiesDetectionV2JobResponse, { class => 'Paws::ComprehendMedical::DescribeEntitiesDetectionV2JobResponse' };
  class_type ComprehendMedical_DescribePHIDetectionJobRequest, { class => 'Paws::ComprehendMedical::DescribePHIDetectionJobRequest' };
  class_type ComprehendMedical_DescribePHIDetectionJobResponse, { class => 'Paws::ComprehendMedical::DescribePHIDetectionJobResponse' };
  class_type ComprehendMedical_DetectEntitiesRequest, { class => 'Paws::ComprehendMedical::DetectEntitiesRequest' };
  class_type ComprehendMedical_DetectEntitiesResponse, { class => 'Paws::ComprehendMedical::DetectEntitiesResponse' };
  class_type ComprehendMedical_DetectEntitiesV2Request, { class => 'Paws::ComprehendMedical::DetectEntitiesV2Request' };
  class_type ComprehendMedical_DetectEntitiesV2Response, { class => 'Paws::ComprehendMedical::DetectEntitiesV2Response' };
  class_type ComprehendMedical_DetectPHIRequest, { class => 'Paws::ComprehendMedical::DetectPHIRequest' };
  class_type ComprehendMedical_DetectPHIResponse, { class => 'Paws::ComprehendMedical::DetectPHIResponse' };
  class_type ComprehendMedical_Entity, { class => 'Paws::ComprehendMedical::Entity' };
  class_type ComprehendMedical_InputDataConfig, { class => 'Paws::ComprehendMedical::InputDataConfig' };
  class_type ComprehendMedical_InternalServerException, { class => 'Paws::ComprehendMedical::InternalServerException' };
  class_type ComprehendMedical_InvalidEncodingException, { class => 'Paws::ComprehendMedical::InvalidEncodingException' };
  class_type ComprehendMedical_InvalidRequestException, { class => 'Paws::ComprehendMedical::InvalidRequestException' };
  class_type ComprehendMedical_ListEntitiesDetectionV2JobsRequest, { class => 'Paws::ComprehendMedical::ListEntitiesDetectionV2JobsRequest' };
  class_type ComprehendMedical_ListEntitiesDetectionV2JobsResponse, { class => 'Paws::ComprehendMedical::ListEntitiesDetectionV2JobsResponse' };
  class_type ComprehendMedical_ListPHIDetectionJobsRequest, { class => 'Paws::ComprehendMedical::ListPHIDetectionJobsRequest' };
  class_type ComprehendMedical_ListPHIDetectionJobsResponse, { class => 'Paws::ComprehendMedical::ListPHIDetectionJobsResponse' };
  class_type ComprehendMedical_OutputDataConfig, { class => 'Paws::ComprehendMedical::OutputDataConfig' };
  class_type ComprehendMedical_ResourceNotFoundException, { class => 'Paws::ComprehendMedical::ResourceNotFoundException' };
  class_type ComprehendMedical_ServiceUnavailableException, { class => 'Paws::ComprehendMedical::ServiceUnavailableException' };
  class_type ComprehendMedical_StartEntitiesDetectionV2JobRequest, { class => 'Paws::ComprehendMedical::StartEntitiesDetectionV2JobRequest' };
  class_type ComprehendMedical_StartEntitiesDetectionV2JobResponse, { class => 'Paws::ComprehendMedical::StartEntitiesDetectionV2JobResponse' };
  class_type ComprehendMedical_StartPHIDetectionJobRequest, { class => 'Paws::ComprehendMedical::StartPHIDetectionJobRequest' };
  class_type ComprehendMedical_StartPHIDetectionJobResponse, { class => 'Paws::ComprehendMedical::StartPHIDetectionJobResponse' };
  class_type ComprehendMedical_StopEntitiesDetectionV2JobRequest, { class => 'Paws::ComprehendMedical::StopEntitiesDetectionV2JobRequest' };
  class_type ComprehendMedical_StopEntitiesDetectionV2JobResponse, { class => 'Paws::ComprehendMedical::StopEntitiesDetectionV2JobResponse' };
  class_type ComprehendMedical_StopPHIDetectionJobRequest, { class => 'Paws::ComprehendMedical::StopPHIDetectionJobRequest' };
  class_type ComprehendMedical_StopPHIDetectionJobResponse, { class => 'Paws::ComprehendMedical::StopPHIDetectionJobResponse' };
  class_type ComprehendMedical_TextSizeLimitExceededException, { class => 'Paws::ComprehendMedical::TextSizeLimitExceededException' };
  class_type ComprehendMedical_TooManyRequestsException, { class => 'Paws::ComprehendMedical::TooManyRequestsException' };
  class_type ComprehendMedical_Trait, { class => 'Paws::ComprehendMedical::Trait' };
  class_type ComprehendMedical_UnmappedAttribute, { class => 'Paws::ComprehendMedical::UnmappedAttribute' };
  class_type ComprehendMedical_ValidationException, { class => 'Paws::ComprehendMedical::ValidationException' };

1;
