package Paws::S3Control::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type S3Control_BadRequestException, { class => 'Paws::S3Control::BadRequestException' };
  class_type S3Control_CreateJobRequest, { class => 'Paws::S3Control::CreateJobRequest' };
  class_type S3Control_CreateJobResult, { class => 'Paws::S3Control::CreateJobResult' };
  class_type S3Control_DeletePublicAccessBlockRequest, { class => 'Paws::S3Control::DeletePublicAccessBlockRequest' };
  class_type S3Control_DescribeJobRequest, { class => 'Paws::S3Control::DescribeJobRequest' };
  class_type S3Control_DescribeJobResult, { class => 'Paws::S3Control::DescribeJobResult' };
  class_type S3Control_GetPublicAccessBlockOutput, { class => 'Paws::S3Control::GetPublicAccessBlockOutput' };
  class_type S3Control_GetPublicAccessBlockRequest, { class => 'Paws::S3Control::GetPublicAccessBlockRequest' };
  class_type S3Control_IdempotencyException, { class => 'Paws::S3Control::IdempotencyException' };
  class_type S3Control_InternalServiceException, { class => 'Paws::S3Control::InternalServiceException' };
  class_type S3Control_InvalidNextTokenException, { class => 'Paws::S3Control::InvalidNextTokenException' };
  class_type S3Control_InvalidRequestException, { class => 'Paws::S3Control::InvalidRequestException' };
  class_type S3Control_JobDescriptor, { class => 'Paws::S3Control::JobDescriptor' };
  class_type S3Control_JobFailure, { class => 'Paws::S3Control::JobFailure' };
  class_type S3Control_JobListDescriptor, { class => 'Paws::S3Control::JobListDescriptor' };
  class_type S3Control_JobManifest, { class => 'Paws::S3Control::JobManifest' };
  class_type S3Control_JobManifestLocation, { class => 'Paws::S3Control::JobManifestLocation' };
  class_type S3Control_JobManifestSpec, { class => 'Paws::S3Control::JobManifestSpec' };
  class_type S3Control_JobOperation, { class => 'Paws::S3Control::JobOperation' };
  class_type S3Control_JobProgressSummary, { class => 'Paws::S3Control::JobProgressSummary' };
  class_type S3Control_JobReport, { class => 'Paws::S3Control::JobReport' };
  class_type S3Control_JobStatusException, { class => 'Paws::S3Control::JobStatusException' };
  class_type S3Control_LambdaInvokeOperation, { class => 'Paws::S3Control::LambdaInvokeOperation' };
  class_type S3Control_ListJobsRequest, { class => 'Paws::S3Control::ListJobsRequest' };
  class_type S3Control_ListJobsResult, { class => 'Paws::S3Control::ListJobsResult' };
  class_type S3Control_NoSuchPublicAccessBlockConfiguration, { class => 'Paws::S3Control::NoSuchPublicAccessBlockConfiguration' };
  class_type S3Control_NotFoundException, { class => 'Paws::S3Control::NotFoundException' };
  class_type S3Control_PublicAccessBlockConfiguration, { class => 'Paws::S3Control::PublicAccessBlockConfiguration' };
  class_type S3Control_PutPublicAccessBlockRequest, { class => 'Paws::S3Control::PutPublicAccessBlockRequest' };
  class_type S3Control_S3AccessControlList, { class => 'Paws::S3Control::S3AccessControlList' };
  class_type S3Control_S3AccessControlPolicy, { class => 'Paws::S3Control::S3AccessControlPolicy' };
  class_type S3Control_S3CopyObjectOperation, { class => 'Paws::S3Control::S3CopyObjectOperation' };
  class_type S3Control_S3Grant, { class => 'Paws::S3Control::S3Grant' };
  class_type S3Control_S3Grantee, { class => 'Paws::S3Control::S3Grantee' };
  class_type S3Control_S3InitiateRestoreObjectOperation, { class => 'Paws::S3Control::S3InitiateRestoreObjectOperation' };
  class_type S3Control_S3ObjectMetadata, { class => 'Paws::S3Control::S3ObjectMetadata' };
  class_type S3Control_S3ObjectOwner, { class => 'Paws::S3Control::S3ObjectOwner' };
  class_type S3Control_S3SetObjectAclOperation, { class => 'Paws::S3Control::S3SetObjectAclOperation' };
  class_type S3Control_S3SetObjectTaggingOperation, { class => 'Paws::S3Control::S3SetObjectTaggingOperation' };
  class_type S3Control_S3Tag, { class => 'Paws::S3Control::S3Tag' };
  class_type S3Control_S3UserMetadata, { class => 'Paws::S3Control::S3UserMetadata' };
  class_type S3Control_TooManyRequestsException, { class => 'Paws::S3Control::TooManyRequestsException' };
  class_type S3Control_UpdateJobPriorityRequest, { class => 'Paws::S3Control::UpdateJobPriorityRequest' };
  class_type S3Control_UpdateJobPriorityResult, { class => 'Paws::S3Control::UpdateJobPriorityResult' };
  class_type S3Control_UpdateJobStatusRequest, { class => 'Paws::S3Control::UpdateJobStatusRequest' };
  class_type S3Control_UpdateJobStatusResult, { class => 'Paws::S3Control::UpdateJobStatusResult' };

1;
