package Paws::FSX::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type FSX_ActiveDirectoryBackupAttributes, { class => 'Paws::FSX::ActiveDirectoryBackupAttributes' };
  class_type FSX_ActiveDirectoryError, { class => 'Paws::FSX::ActiveDirectoryError' };
  class_type FSX_Backup, { class => 'Paws::FSX::Backup' };
  class_type FSX_BackupFailureDetails, { class => 'Paws::FSX::BackupFailureDetails' };
  class_type FSX_BackupInProgress, { class => 'Paws::FSX::BackupInProgress' };
  class_type FSX_BackupNotFound, { class => 'Paws::FSX::BackupNotFound' };
  class_type FSX_BackupRestoring, { class => 'Paws::FSX::BackupRestoring' };
  class_type FSX_BadRequest, { class => 'Paws::FSX::BadRequest' };
  class_type FSX_CreateBackupRequest, { class => 'Paws::FSX::CreateBackupRequest' };
  class_type FSX_CreateBackupResponse, { class => 'Paws::FSX::CreateBackupResponse' };
  class_type FSX_CreateFileSystemFromBackupRequest, { class => 'Paws::FSX::CreateFileSystemFromBackupRequest' };
  class_type FSX_CreateFileSystemFromBackupResponse, { class => 'Paws::FSX::CreateFileSystemFromBackupResponse' };
  class_type FSX_CreateFileSystemLustreConfiguration, { class => 'Paws::FSX::CreateFileSystemLustreConfiguration' };
  class_type FSX_CreateFileSystemRequest, { class => 'Paws::FSX::CreateFileSystemRequest' };
  class_type FSX_CreateFileSystemResponse, { class => 'Paws::FSX::CreateFileSystemResponse' };
  class_type FSX_CreateFileSystemWindowsConfiguration, { class => 'Paws::FSX::CreateFileSystemWindowsConfiguration' };
  class_type FSX_DataRepositoryConfiguration, { class => 'Paws::FSX::DataRepositoryConfiguration' };
  class_type FSX_DeleteBackupRequest, { class => 'Paws::FSX::DeleteBackupRequest' };
  class_type FSX_DeleteBackupResponse, { class => 'Paws::FSX::DeleteBackupResponse' };
  class_type FSX_DeleteFileSystemRequest, { class => 'Paws::FSX::DeleteFileSystemRequest' };
  class_type FSX_DeleteFileSystemResponse, { class => 'Paws::FSX::DeleteFileSystemResponse' };
  class_type FSX_DeleteFileSystemWindowsConfiguration, { class => 'Paws::FSX::DeleteFileSystemWindowsConfiguration' };
  class_type FSX_DeleteFileSystemWindowsResponse, { class => 'Paws::FSX::DeleteFileSystemWindowsResponse' };
  class_type FSX_DescribeBackupsRequest, { class => 'Paws::FSX::DescribeBackupsRequest' };
  class_type FSX_DescribeBackupsResponse, { class => 'Paws::FSX::DescribeBackupsResponse' };
  class_type FSX_DescribeFileSystemsRequest, { class => 'Paws::FSX::DescribeFileSystemsRequest' };
  class_type FSX_DescribeFileSystemsResponse, { class => 'Paws::FSX::DescribeFileSystemsResponse' };
  class_type FSX_FileSystem, { class => 'Paws::FSX::FileSystem' };
  class_type FSX_FileSystemFailureDetails, { class => 'Paws::FSX::FileSystemFailureDetails' };
  class_type FSX_FileSystemNotFound, { class => 'Paws::FSX::FileSystemNotFound' };
  class_type FSX_Filter, { class => 'Paws::FSX::Filter' };
  class_type FSX_IncompatibleParameterError, { class => 'Paws::FSX::IncompatibleParameterError' };
  class_type FSX_InternalServerError, { class => 'Paws::FSX::InternalServerError' };
  class_type FSX_InvalidExportPath, { class => 'Paws::FSX::InvalidExportPath' };
  class_type FSX_InvalidImportPath, { class => 'Paws::FSX::InvalidImportPath' };
  class_type FSX_InvalidNetworkSettings, { class => 'Paws::FSX::InvalidNetworkSettings' };
  class_type FSX_ListTagsForResourceRequest, { class => 'Paws::FSX::ListTagsForResourceRequest' };
  class_type FSX_ListTagsForResourceResponse, { class => 'Paws::FSX::ListTagsForResourceResponse' };
  class_type FSX_LustreFileSystemConfiguration, { class => 'Paws::FSX::LustreFileSystemConfiguration' };
  class_type FSX_MissingFileSystemConfiguration, { class => 'Paws::FSX::MissingFileSystemConfiguration' };
  class_type FSX_NotServiceResourceError, { class => 'Paws::FSX::NotServiceResourceError' };
  class_type FSX_ResourceDoesNotSupportTagging, { class => 'Paws::FSX::ResourceDoesNotSupportTagging' };
  class_type FSX_ResourceNotFound, { class => 'Paws::FSX::ResourceNotFound' };
  class_type FSX_SelfManagedActiveDirectoryAttributes, { class => 'Paws::FSX::SelfManagedActiveDirectoryAttributes' };
  class_type FSX_SelfManagedActiveDirectoryConfiguration, { class => 'Paws::FSX::SelfManagedActiveDirectoryConfiguration' };
  class_type FSX_SelfManagedActiveDirectoryConfigurationUpdates, { class => 'Paws::FSX::SelfManagedActiveDirectoryConfigurationUpdates' };
  class_type FSX_ServiceLimitExceeded, { class => 'Paws::FSX::ServiceLimitExceeded' };
  class_type FSX_Tag, { class => 'Paws::FSX::Tag' };
  class_type FSX_TagResourceRequest, { class => 'Paws::FSX::TagResourceRequest' };
  class_type FSX_TagResourceResponse, { class => 'Paws::FSX::TagResourceResponse' };
  class_type FSX_UnsupportedOperation, { class => 'Paws::FSX::UnsupportedOperation' };
  class_type FSX_UntagResourceRequest, { class => 'Paws::FSX::UntagResourceRequest' };
  class_type FSX_UntagResourceResponse, { class => 'Paws::FSX::UntagResourceResponse' };
  class_type FSX_UpdateFileSystemLustreConfiguration, { class => 'Paws::FSX::UpdateFileSystemLustreConfiguration' };
  class_type FSX_UpdateFileSystemRequest, { class => 'Paws::FSX::UpdateFileSystemRequest' };
  class_type FSX_UpdateFileSystemResponse, { class => 'Paws::FSX::UpdateFileSystemResponse' };
  class_type FSX_UpdateFileSystemWindowsConfiguration, { class => 'Paws::FSX::UpdateFileSystemWindowsConfiguration' };
  class_type FSX_WindowsFileSystemConfiguration, { class => 'Paws::FSX::WindowsFileSystemConfiguration' };

1;
