package Paws::EKS::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type EKS_Certificate, { class => 'Paws::EKS::Certificate' };
  class_type EKS_ClientException, { class => 'Paws::EKS::ClientException' };
  class_type EKS_Cluster, { class => 'Paws::EKS::Cluster' };
  class_type EKS_CreateClusterRequest, { class => 'Paws::EKS::CreateClusterRequest' };
  class_type EKS_CreateClusterResponse, { class => 'Paws::EKS::CreateClusterResponse' };
  class_type EKS_DeleteClusterRequest, { class => 'Paws::EKS::DeleteClusterRequest' };
  class_type EKS_DeleteClusterResponse, { class => 'Paws::EKS::DeleteClusterResponse' };
  class_type EKS_DescribeClusterRequest, { class => 'Paws::EKS::DescribeClusterRequest' };
  class_type EKS_DescribeClusterResponse, { class => 'Paws::EKS::DescribeClusterResponse' };
  class_type EKS_DescribeUpdateRequest, { class => 'Paws::EKS::DescribeUpdateRequest' };
  class_type EKS_DescribeUpdateResponse, { class => 'Paws::EKS::DescribeUpdateResponse' };
  class_type EKS_ErrorDetail, { class => 'Paws::EKS::ErrorDetail' };
  class_type EKS_InvalidParameterException, { class => 'Paws::EKS::InvalidParameterException' };
  class_type EKS_InvalidRequestException, { class => 'Paws::EKS::InvalidRequestException' };
  class_type EKS_ListClustersRequest, { class => 'Paws::EKS::ListClustersRequest' };
  class_type EKS_ListClustersResponse, { class => 'Paws::EKS::ListClustersResponse' };
  class_type EKS_ListUpdatesRequest, { class => 'Paws::EKS::ListUpdatesRequest' };
  class_type EKS_ListUpdatesResponse, { class => 'Paws::EKS::ListUpdatesResponse' };
  class_type EKS_Logging, { class => 'Paws::EKS::Logging' };
  class_type EKS_LogSetup, { class => 'Paws::EKS::LogSetup' };
  class_type EKS_ResourceInUseException, { class => 'Paws::EKS::ResourceInUseException' };
  class_type EKS_ResourceLimitExceededException, { class => 'Paws::EKS::ResourceLimitExceededException' };
  class_type EKS_ResourceNotFoundException, { class => 'Paws::EKS::ResourceNotFoundException' };
  class_type EKS_ServerException, { class => 'Paws::EKS::ServerException' };
  class_type EKS_ServiceUnavailableException, { class => 'Paws::EKS::ServiceUnavailableException' };
  class_type EKS_UnsupportedAvailabilityZoneException, { class => 'Paws::EKS::UnsupportedAvailabilityZoneException' };
  class_type EKS_Update, { class => 'Paws::EKS::Update' };
  class_type EKS_UpdateClusterConfigRequest, { class => 'Paws::EKS::UpdateClusterConfigRequest' };
  class_type EKS_UpdateClusterConfigResponse, { class => 'Paws::EKS::UpdateClusterConfigResponse' };
  class_type EKS_UpdateClusterVersionRequest, { class => 'Paws::EKS::UpdateClusterVersionRequest' };
  class_type EKS_UpdateClusterVersionResponse, { class => 'Paws::EKS::UpdateClusterVersionResponse' };
  class_type EKS_UpdateParam, { class => 'Paws::EKS::UpdateParam' };
  class_type EKS_VpcConfigRequest, { class => 'Paws::EKS::VpcConfigRequest' };
  class_type EKS_VpcConfigResponse, { class => 'Paws::EKS::VpcConfigResponse' };

1;
