package Paws::EFS::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type EFS_BadRequest, { class => 'Paws::EFS::BadRequest' };
  class_type EFS_CreateFileSystemRequest, { class => 'Paws::EFS::CreateFileSystemRequest' };
  class_type EFS_CreateMountTargetRequest, { class => 'Paws::EFS::CreateMountTargetRequest' };
  class_type EFS_CreateTagsRequest, { class => 'Paws::EFS::CreateTagsRequest' };
  class_type EFS_DeleteFileSystemRequest, { class => 'Paws::EFS::DeleteFileSystemRequest' };
  class_type EFS_DeleteMountTargetRequest, { class => 'Paws::EFS::DeleteMountTargetRequest' };
  class_type EFS_DeleteTagsRequest, { class => 'Paws::EFS::DeleteTagsRequest' };
  class_type EFS_DependencyTimeout, { class => 'Paws::EFS::DependencyTimeout' };
  class_type EFS_DescribeFileSystemsRequest, { class => 'Paws::EFS::DescribeFileSystemsRequest' };
  class_type EFS_DescribeFileSystemsResponse, { class => 'Paws::EFS::DescribeFileSystemsResponse' };
  class_type EFS_DescribeLifecycleConfigurationRequest, { class => 'Paws::EFS::DescribeLifecycleConfigurationRequest' };
  class_type EFS_DescribeMountTargetSecurityGroupsRequest, { class => 'Paws::EFS::DescribeMountTargetSecurityGroupsRequest' };
  class_type EFS_DescribeMountTargetSecurityGroupsResponse, { class => 'Paws::EFS::DescribeMountTargetSecurityGroupsResponse' };
  class_type EFS_DescribeMountTargetsRequest, { class => 'Paws::EFS::DescribeMountTargetsRequest' };
  class_type EFS_DescribeMountTargetsResponse, { class => 'Paws::EFS::DescribeMountTargetsResponse' };
  class_type EFS_DescribeTagsRequest, { class => 'Paws::EFS::DescribeTagsRequest' };
  class_type EFS_DescribeTagsResponse, { class => 'Paws::EFS::DescribeTagsResponse' };
  class_type EFS_FileSystemAlreadyExists, { class => 'Paws::EFS::FileSystemAlreadyExists' };
  class_type EFS_FileSystemDescription, { class => 'Paws::EFS::FileSystemDescription' };
  class_type EFS_FileSystemInUse, { class => 'Paws::EFS::FileSystemInUse' };
  class_type EFS_FileSystemLimitExceeded, { class => 'Paws::EFS::FileSystemLimitExceeded' };
  class_type EFS_FileSystemNotFound, { class => 'Paws::EFS::FileSystemNotFound' };
  class_type EFS_FileSystemSize, { class => 'Paws::EFS::FileSystemSize' };
  class_type EFS_IncorrectFileSystemLifeCycleState, { class => 'Paws::EFS::IncorrectFileSystemLifeCycleState' };
  class_type EFS_IncorrectMountTargetState, { class => 'Paws::EFS::IncorrectMountTargetState' };
  class_type EFS_InsufficientThroughputCapacity, { class => 'Paws::EFS::InsufficientThroughputCapacity' };
  class_type EFS_InternalServerError, { class => 'Paws::EFS::InternalServerError' };
  class_type EFS_IpAddressInUse, { class => 'Paws::EFS::IpAddressInUse' };
  class_type EFS_LifecycleConfigurationDescription, { class => 'Paws::EFS::LifecycleConfigurationDescription' };
  class_type EFS_LifecyclePolicy, { class => 'Paws::EFS::LifecyclePolicy' };
  class_type EFS_ModifyMountTargetSecurityGroupsRequest, { class => 'Paws::EFS::ModifyMountTargetSecurityGroupsRequest' };
  class_type EFS_MountTargetConflict, { class => 'Paws::EFS::MountTargetConflict' };
  class_type EFS_MountTargetDescription, { class => 'Paws::EFS::MountTargetDescription' };
  class_type EFS_MountTargetNotFound, { class => 'Paws::EFS::MountTargetNotFound' };
  class_type EFS_NetworkInterfaceLimitExceeded, { class => 'Paws::EFS::NetworkInterfaceLimitExceeded' };
  class_type EFS_NoFreeAddressesInSubnet, { class => 'Paws::EFS::NoFreeAddressesInSubnet' };
  class_type EFS_PutLifecycleConfigurationRequest, { class => 'Paws::EFS::PutLifecycleConfigurationRequest' };
  class_type EFS_SecurityGroupLimitExceeded, { class => 'Paws::EFS::SecurityGroupLimitExceeded' };
  class_type EFS_SecurityGroupNotFound, { class => 'Paws::EFS::SecurityGroupNotFound' };
  class_type EFS_SubnetNotFound, { class => 'Paws::EFS::SubnetNotFound' };
  class_type EFS_Tag, { class => 'Paws::EFS::Tag' };
  class_type EFS_ThroughputLimitExceeded, { class => 'Paws::EFS::ThroughputLimitExceeded' };
  class_type EFS_TooManyRequests, { class => 'Paws::EFS::TooManyRequests' };
  class_type EFS_UnsupportedAvailabilityZone, { class => 'Paws::EFS::UnsupportedAvailabilityZone' };
  class_type EFS_UpdateFileSystemRequest, { class => 'Paws::EFS::UpdateFileSystemRequest' };

1;
