language: perl
env:
  - IN_TRAVIS=1 AUTHOR_TESTING=1 PERL_MB_OPT="quiet=1" HELPERS_DEBUG=1
perl:
  - "dev"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  allow_failures:
    - perl: dev
    - perl: 5.8
sudo: false
# before_install:
#   - eval $(curl https://travis-perl.github.io/init) --auto

before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install --deps       # installs prereqs, including recommends
  - cpan-install --coverage   # installs coverage prereqs, if enabled
script:
  - prove -l -j$(test-jobs) $(test-files)   # parallel testing
before_script:
  - coverage-setup