package Paws::ImportExport::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ImportExport_Artifact, { class => 'Paws::ImportExport::Artifact' };
  class_type ImportExport_BucketPermissionException, { class => 'Paws::ImportExport::BucketPermissionException' };
  class_type ImportExport_CanceledJobIdException, { class => 'Paws::ImportExport::CanceledJobIdException' };
  class_type ImportExport_CancelJobInput, { class => 'Paws::ImportExport::CancelJobInput' };
  class_type ImportExport_CancelJobOutput, { class => 'Paws::ImportExport::CancelJobOutput' };
  class_type ImportExport_CreateJobInput, { class => 'Paws::ImportExport::CreateJobInput' };
  class_type ImportExport_CreateJobOutput, { class => 'Paws::ImportExport::CreateJobOutput' };
  class_type ImportExport_CreateJobQuotaExceededException, { class => 'Paws::ImportExport::CreateJobQuotaExceededException' };
  class_type ImportExport_ExpiredJobIdException, { class => 'Paws::ImportExport::ExpiredJobIdException' };
  class_type ImportExport_GetShippingLabelInput, { class => 'Paws::ImportExport::GetShippingLabelInput' };
  class_type ImportExport_GetShippingLabelOutput, { class => 'Paws::ImportExport::GetShippingLabelOutput' };
  class_type ImportExport_GetStatusInput, { class => 'Paws::ImportExport::GetStatusInput' };
  class_type ImportExport_GetStatusOutput, { class => 'Paws::ImportExport::GetStatusOutput' };
  class_type ImportExport_InvalidAccessKeyIdException, { class => 'Paws::ImportExport::InvalidAccessKeyIdException' };
  class_type ImportExport_InvalidAddressException, { class => 'Paws::ImportExport::InvalidAddressException' };
  class_type ImportExport_InvalidCustomsException, { class => 'Paws::ImportExport::InvalidCustomsException' };
  class_type ImportExport_InvalidFileSystemException, { class => 'Paws::ImportExport::InvalidFileSystemException' };
  class_type ImportExport_InvalidJobIdException, { class => 'Paws::ImportExport::InvalidJobIdException' };
  class_type ImportExport_InvalidManifestFieldException, { class => 'Paws::ImportExport::InvalidManifestFieldException' };
  class_type ImportExport_InvalidParameterException, { class => 'Paws::ImportExport::InvalidParameterException' };
  class_type ImportExport_InvalidVersionException, { class => 'Paws::ImportExport::InvalidVersionException' };
  class_type ImportExport_Job, { class => 'Paws::ImportExport::Job' };
  class_type ImportExport_ListJobsInput, { class => 'Paws::ImportExport::ListJobsInput' };
  class_type ImportExport_ListJobsOutput, { class => 'Paws::ImportExport::ListJobsOutput' };
  class_type ImportExport_MalformedManifestException, { class => 'Paws::ImportExport::MalformedManifestException' };
  class_type ImportExport_MissingCustomsException, { class => 'Paws::ImportExport::MissingCustomsException' };
  class_type ImportExport_MissingManifestFieldException, { class => 'Paws::ImportExport::MissingManifestFieldException' };
  class_type ImportExport_MissingParameterException, { class => 'Paws::ImportExport::MissingParameterException' };
  class_type ImportExport_MultipleRegionsException, { class => 'Paws::ImportExport::MultipleRegionsException' };
  class_type ImportExport_NoSuchBucketException, { class => 'Paws::ImportExport::NoSuchBucketException' };
  class_type ImportExport_UnableToCancelJobIdException, { class => 'Paws::ImportExport::UnableToCancelJobIdException' };
  class_type ImportExport_UnableToUpdateJobIdException, { class => 'Paws::ImportExport::UnableToUpdateJobIdException' };
  class_type ImportExport_UpdateJobInput, { class => 'Paws::ImportExport::UpdateJobInput' };
  class_type ImportExport_UpdateJobOutput, { class => 'Paws::ImportExport::UpdateJobOutput' };

1;
