package Paws::CloudWatchEvents::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CloudWatchEvents_AwsVpcConfiguration, { class => 'Paws::CloudWatchEvents::AwsVpcConfiguration' };
  class_type CloudWatchEvents_BatchArrayProperties, { class => 'Paws::CloudWatchEvents::BatchArrayProperties' };
  class_type CloudWatchEvents_BatchParameters, { class => 'Paws::CloudWatchEvents::BatchParameters' };
  class_type CloudWatchEvents_BatchRetryStrategy, { class => 'Paws::CloudWatchEvents::BatchRetryStrategy' };
  class_type CloudWatchEvents_ConcurrentModificationException, { class => 'Paws::CloudWatchEvents::ConcurrentModificationException' };
  class_type CloudWatchEvents_Condition, { class => 'Paws::CloudWatchEvents::Condition' };
  class_type CloudWatchEvents_DeleteRuleRequest, { class => 'Paws::CloudWatchEvents::DeleteRuleRequest' };
  class_type CloudWatchEvents_DescribeEventBusRequest, { class => 'Paws::CloudWatchEvents::DescribeEventBusRequest' };
  class_type CloudWatchEvents_DescribeEventBusResponse, { class => 'Paws::CloudWatchEvents::DescribeEventBusResponse' };
  class_type CloudWatchEvents_DescribeRuleRequest, { class => 'Paws::CloudWatchEvents::DescribeRuleRequest' };
  class_type CloudWatchEvents_DescribeRuleResponse, { class => 'Paws::CloudWatchEvents::DescribeRuleResponse' };
  class_type CloudWatchEvents_DisableRuleRequest, { class => 'Paws::CloudWatchEvents::DisableRuleRequest' };
  class_type CloudWatchEvents_EcsParameters, { class => 'Paws::CloudWatchEvents::EcsParameters' };
  class_type CloudWatchEvents_EnableRuleRequest, { class => 'Paws::CloudWatchEvents::EnableRuleRequest' };
  class_type CloudWatchEvents_InputTransformer, { class => 'Paws::CloudWatchEvents::InputTransformer' };
  class_type CloudWatchEvents_InternalException, { class => 'Paws::CloudWatchEvents::InternalException' };
  class_type CloudWatchEvents_InvalidEventPatternException, { class => 'Paws::CloudWatchEvents::InvalidEventPatternException' };
  class_type CloudWatchEvents_KinesisParameters, { class => 'Paws::CloudWatchEvents::KinesisParameters' };
  class_type CloudWatchEvents_LimitExceededException, { class => 'Paws::CloudWatchEvents::LimitExceededException' };
  class_type CloudWatchEvents_ListRuleNamesByTargetRequest, { class => 'Paws::CloudWatchEvents::ListRuleNamesByTargetRequest' };
  class_type CloudWatchEvents_ListRuleNamesByTargetResponse, { class => 'Paws::CloudWatchEvents::ListRuleNamesByTargetResponse' };
  class_type CloudWatchEvents_ListRulesRequest, { class => 'Paws::CloudWatchEvents::ListRulesRequest' };
  class_type CloudWatchEvents_ListRulesResponse, { class => 'Paws::CloudWatchEvents::ListRulesResponse' };
  class_type CloudWatchEvents_ListTagsForResourceRequest, { class => 'Paws::CloudWatchEvents::ListTagsForResourceRequest' };
  class_type CloudWatchEvents_ListTagsForResourceResponse, { class => 'Paws::CloudWatchEvents::ListTagsForResourceResponse' };
  class_type CloudWatchEvents_ListTargetsByRuleRequest, { class => 'Paws::CloudWatchEvents::ListTargetsByRuleRequest' };
  class_type CloudWatchEvents_ListTargetsByRuleResponse, { class => 'Paws::CloudWatchEvents::ListTargetsByRuleResponse' };
  class_type CloudWatchEvents_ManagedRuleException, { class => 'Paws::CloudWatchEvents::ManagedRuleException' };
  class_type CloudWatchEvents_NetworkConfiguration, { class => 'Paws::CloudWatchEvents::NetworkConfiguration' };
  class_type CloudWatchEvents_PolicyLengthExceededException, { class => 'Paws::CloudWatchEvents::PolicyLengthExceededException' };
  class_type CloudWatchEvents_PutEventsRequest, { class => 'Paws::CloudWatchEvents::PutEventsRequest' };
  class_type CloudWatchEvents_PutEventsRequestEntry, { class => 'Paws::CloudWatchEvents::PutEventsRequestEntry' };
  class_type CloudWatchEvents_PutEventsResponse, { class => 'Paws::CloudWatchEvents::PutEventsResponse' };
  class_type CloudWatchEvents_PutEventsResultEntry, { class => 'Paws::CloudWatchEvents::PutEventsResultEntry' };
  class_type CloudWatchEvents_PutPermissionRequest, { class => 'Paws::CloudWatchEvents::PutPermissionRequest' };
  class_type CloudWatchEvents_PutRuleRequest, { class => 'Paws::CloudWatchEvents::PutRuleRequest' };
  class_type CloudWatchEvents_PutRuleResponse, { class => 'Paws::CloudWatchEvents::PutRuleResponse' };
  class_type CloudWatchEvents_PutTargetsRequest, { class => 'Paws::CloudWatchEvents::PutTargetsRequest' };
  class_type CloudWatchEvents_PutTargetsResponse, { class => 'Paws::CloudWatchEvents::PutTargetsResponse' };
  class_type CloudWatchEvents_PutTargetsResultEntry, { class => 'Paws::CloudWatchEvents::PutTargetsResultEntry' };
  class_type CloudWatchEvents_RemovePermissionRequest, { class => 'Paws::CloudWatchEvents::RemovePermissionRequest' };
  class_type CloudWatchEvents_RemoveTargetsRequest, { class => 'Paws::CloudWatchEvents::RemoveTargetsRequest' };
  class_type CloudWatchEvents_RemoveTargetsResponse, { class => 'Paws::CloudWatchEvents::RemoveTargetsResponse' };
  class_type CloudWatchEvents_RemoveTargetsResultEntry, { class => 'Paws::CloudWatchEvents::RemoveTargetsResultEntry' };
  class_type CloudWatchEvents_ResourceNotFoundException, { class => 'Paws::CloudWatchEvents::ResourceNotFoundException' };
  class_type CloudWatchEvents_Rule, { class => 'Paws::CloudWatchEvents::Rule' };
  class_type CloudWatchEvents_RunCommandParameters, { class => 'Paws::CloudWatchEvents::RunCommandParameters' };
  class_type CloudWatchEvents_RunCommandTarget, { class => 'Paws::CloudWatchEvents::RunCommandTarget' };
  class_type CloudWatchEvents_SqsParameters, { class => 'Paws::CloudWatchEvents::SqsParameters' };
  class_type CloudWatchEvents_Tag, { class => 'Paws::CloudWatchEvents::Tag' };
  class_type CloudWatchEvents_TagResourceRequest, { class => 'Paws::CloudWatchEvents::TagResourceRequest' };
  class_type CloudWatchEvents_TagResourceResponse, { class => 'Paws::CloudWatchEvents::TagResourceResponse' };
  class_type CloudWatchEvents_Target, { class => 'Paws::CloudWatchEvents::Target' };
  class_type CloudWatchEvents_TestEventPatternRequest, { class => 'Paws::CloudWatchEvents::TestEventPatternRequest' };
  class_type CloudWatchEvents_TestEventPatternResponse, { class => 'Paws::CloudWatchEvents::TestEventPatternResponse' };
  class_type CloudWatchEvents_TransformerPaths, { class => 'Paws::CloudWatchEvents::TransformerPaths' };
  class_type CloudWatchEvents_UntagResourceRequest, { class => 'Paws::CloudWatchEvents::UntagResourceRequest' };
  class_type CloudWatchEvents_UntagResourceResponse, { class => 'Paws::CloudWatchEvents::UntagResourceResponse' };

1;
