package Paws::CostExplorer::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CostExplorer_Attributes, { class => 'Paws::CostExplorer::Attributes' };
  class_type CostExplorer_BillExpirationException, { class => 'Paws::CostExplorer::BillExpirationException' };
  class_type CostExplorer_Coverage, { class => 'Paws::CostExplorer::Coverage' };
  class_type CostExplorer_CoverageByTime, { class => 'Paws::CostExplorer::CoverageByTime' };
  class_type CostExplorer_CoverageCost, { class => 'Paws::CostExplorer::CoverageCost' };
  class_type CostExplorer_CoverageHours, { class => 'Paws::CostExplorer::CoverageHours' };
  class_type CostExplorer_CoverageNormalizedUnits, { class => 'Paws::CostExplorer::CoverageNormalizedUnits' };
  class_type CostExplorer_DataUnavailableException, { class => 'Paws::CostExplorer::DataUnavailableException' };
  class_type CostExplorer_DateInterval, { class => 'Paws::CostExplorer::DateInterval' };
  class_type CostExplorer_DimensionValues, { class => 'Paws::CostExplorer::DimensionValues' };
  class_type CostExplorer_DimensionValuesWithAttributes, { class => 'Paws::CostExplorer::DimensionValuesWithAttributes' };
  class_type CostExplorer_EC2InstanceDetails, { class => 'Paws::CostExplorer::EC2InstanceDetails' };
  class_type CostExplorer_EC2Specification, { class => 'Paws::CostExplorer::EC2Specification' };
  class_type CostExplorer_ElastiCacheInstanceDetails, { class => 'Paws::CostExplorer::ElastiCacheInstanceDetails' };
  class_type CostExplorer_ESInstanceDetails, { class => 'Paws::CostExplorer::ESInstanceDetails' };
  class_type CostExplorer_Expression, { class => 'Paws::CostExplorer::Expression' };
  class_type CostExplorer_ForecastResult, { class => 'Paws::CostExplorer::ForecastResult' };
  class_type CostExplorer_GetCostAndUsageRequest, { class => 'Paws::CostExplorer::GetCostAndUsageRequest' };
  class_type CostExplorer_GetCostAndUsageResponse, { class => 'Paws::CostExplorer::GetCostAndUsageResponse' };
  class_type CostExplorer_GetCostForecastRequest, { class => 'Paws::CostExplorer::GetCostForecastRequest' };
  class_type CostExplorer_GetCostForecastResponse, { class => 'Paws::CostExplorer::GetCostForecastResponse' };
  class_type CostExplorer_GetDimensionValuesRequest, { class => 'Paws::CostExplorer::GetDimensionValuesRequest' };
  class_type CostExplorer_GetDimensionValuesResponse, { class => 'Paws::CostExplorer::GetDimensionValuesResponse' };
  class_type CostExplorer_GetReservationCoverageRequest, { class => 'Paws::CostExplorer::GetReservationCoverageRequest' };
  class_type CostExplorer_GetReservationCoverageResponse, { class => 'Paws::CostExplorer::GetReservationCoverageResponse' };
  class_type CostExplorer_GetReservationPurchaseRecommendationRequest, { class => 'Paws::CostExplorer::GetReservationPurchaseRecommendationRequest' };
  class_type CostExplorer_GetReservationPurchaseRecommendationResponse, { class => 'Paws::CostExplorer::GetReservationPurchaseRecommendationResponse' };
  class_type CostExplorer_GetReservationUtilizationRequest, { class => 'Paws::CostExplorer::GetReservationUtilizationRequest' };
  class_type CostExplorer_GetReservationUtilizationResponse, { class => 'Paws::CostExplorer::GetReservationUtilizationResponse' };
  class_type CostExplorer_GetTagsRequest, { class => 'Paws::CostExplorer::GetTagsRequest' };
  class_type CostExplorer_GetTagsResponse, { class => 'Paws::CostExplorer::GetTagsResponse' };
  class_type CostExplorer_GetUsageForecastRequest, { class => 'Paws::CostExplorer::GetUsageForecastRequest' };
  class_type CostExplorer_GetUsageForecastResponse, { class => 'Paws::CostExplorer::GetUsageForecastResponse' };
  class_type CostExplorer_Group, { class => 'Paws::CostExplorer::Group' };
  class_type CostExplorer_GroupDefinition, { class => 'Paws::CostExplorer::GroupDefinition' };
  class_type CostExplorer_InstanceDetails, { class => 'Paws::CostExplorer::InstanceDetails' };
  class_type CostExplorer_InvalidNextTokenException, { class => 'Paws::CostExplorer::InvalidNextTokenException' };
  class_type CostExplorer_LimitExceededException, { class => 'Paws::CostExplorer::LimitExceededException' };
  class_type CostExplorer_Metrics, { class => 'Paws::CostExplorer::Metrics' };
  class_type CostExplorer_MetricValue, { class => 'Paws::CostExplorer::MetricValue' };
  class_type CostExplorer_RDSInstanceDetails, { class => 'Paws::CostExplorer::RDSInstanceDetails' };
  class_type CostExplorer_RedshiftInstanceDetails, { class => 'Paws::CostExplorer::RedshiftInstanceDetails' };
  class_type CostExplorer_RequestChangedException, { class => 'Paws::CostExplorer::RequestChangedException' };
  class_type CostExplorer_ReservationAggregates, { class => 'Paws::CostExplorer::ReservationAggregates' };
  class_type CostExplorer_ReservationCoverageGroup, { class => 'Paws::CostExplorer::ReservationCoverageGroup' };
  class_type CostExplorer_ReservationPurchaseRecommendation, { class => 'Paws::CostExplorer::ReservationPurchaseRecommendation' };
  class_type CostExplorer_ReservationPurchaseRecommendationDetail, { class => 'Paws::CostExplorer::ReservationPurchaseRecommendationDetail' };
  class_type CostExplorer_ReservationPurchaseRecommendationMetadata, { class => 'Paws::CostExplorer::ReservationPurchaseRecommendationMetadata' };
  class_type CostExplorer_ReservationPurchaseRecommendationSummary, { class => 'Paws::CostExplorer::ReservationPurchaseRecommendationSummary' };
  class_type CostExplorer_ReservationUtilizationGroup, { class => 'Paws::CostExplorer::ReservationUtilizationGroup' };
  class_type CostExplorer_ResultByTime, { class => 'Paws::CostExplorer::ResultByTime' };
  class_type CostExplorer_ServiceSpecification, { class => 'Paws::CostExplorer::ServiceSpecification' };
  class_type CostExplorer_TagValues, { class => 'Paws::CostExplorer::TagValues' };
  class_type CostExplorer_UnresolvableUsageUnitException, { class => 'Paws::CostExplorer::UnresolvableUsageUnitException' };
  class_type CostExplorer_UtilizationByTime, { class => 'Paws::CostExplorer::UtilizationByTime' };

1;
