package Paws::SDB::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type SDB_Attribute, { class => 'Paws::SDB::Attribute' };
  class_type SDB_AttributeDoesNotExist, { class => 'Paws::SDB::AttributeDoesNotExist' };
  class_type SDB_BatchDeleteAttributesRequest, { class => 'Paws::SDB::BatchDeleteAttributesRequest' };
  class_type SDB_BatchPutAttributesRequest, { class => 'Paws::SDB::BatchPutAttributesRequest' };
  class_type SDB_CreateDomainRequest, { class => 'Paws::SDB::CreateDomainRequest' };
  class_type SDB_DeletableAttribute, { class => 'Paws::SDB::DeletableAttribute' };
  class_type SDB_DeletableItem, { class => 'Paws::SDB::DeletableItem' };
  class_type SDB_DeleteAttributesRequest, { class => 'Paws::SDB::DeleteAttributesRequest' };
  class_type SDB_DeleteDomainRequest, { class => 'Paws::SDB::DeleteDomainRequest' };
  class_type SDB_DomainMetadataRequest, { class => 'Paws::SDB::DomainMetadataRequest' };
  class_type SDB_DomainMetadataResult, { class => 'Paws::SDB::DomainMetadataResult' };
  class_type SDB_DuplicateItemName, { class => 'Paws::SDB::DuplicateItemName' };
  class_type SDB_GetAttributesRequest, { class => 'Paws::SDB::GetAttributesRequest' };
  class_type SDB_GetAttributesResult, { class => 'Paws::SDB::GetAttributesResult' };
  class_type SDB_InvalidNextToken, { class => 'Paws::SDB::InvalidNextToken' };
  class_type SDB_InvalidNumberPredicates, { class => 'Paws::SDB::InvalidNumberPredicates' };
  class_type SDB_InvalidNumberValueTests, { class => 'Paws::SDB::InvalidNumberValueTests' };
  class_type SDB_InvalidParameterValue, { class => 'Paws::SDB::InvalidParameterValue' };
  class_type SDB_InvalidQueryExpression, { class => 'Paws::SDB::InvalidQueryExpression' };
  class_type SDB_Item, { class => 'Paws::SDB::Item' };
  class_type SDB_ListDomainsRequest, { class => 'Paws::SDB::ListDomainsRequest' };
  class_type SDB_ListDomainsResult, { class => 'Paws::SDB::ListDomainsResult' };
  class_type SDB_MissingParameter, { class => 'Paws::SDB::MissingParameter' };
  class_type SDB_NoSuchDomain, { class => 'Paws::SDB::NoSuchDomain' };
  class_type SDB_NumberDomainAttributesExceeded, { class => 'Paws::SDB::NumberDomainAttributesExceeded' };
  class_type SDB_NumberDomainBytesExceeded, { class => 'Paws::SDB::NumberDomainBytesExceeded' };
  class_type SDB_NumberDomainsExceeded, { class => 'Paws::SDB::NumberDomainsExceeded' };
  class_type SDB_NumberItemAttributesExceeded, { class => 'Paws::SDB::NumberItemAttributesExceeded' };
  class_type SDB_NumberSubmittedAttributesExceeded, { class => 'Paws::SDB::NumberSubmittedAttributesExceeded' };
  class_type SDB_NumberSubmittedItemsExceeded, { class => 'Paws::SDB::NumberSubmittedItemsExceeded' };
  class_type SDB_PutAttributesRequest, { class => 'Paws::SDB::PutAttributesRequest' };
  class_type SDB_ReplaceableAttribute, { class => 'Paws::SDB::ReplaceableAttribute' };
  class_type SDB_ReplaceableItem, { class => 'Paws::SDB::ReplaceableItem' };
  class_type SDB_RequestTimeout, { class => 'Paws::SDB::RequestTimeout' };
  class_type SDB_SelectRequest, { class => 'Paws::SDB::SelectRequest' };
  class_type SDB_SelectResult, { class => 'Paws::SDB::SelectResult' };
  class_type SDB_TooManyRequestedAttributes, { class => 'Paws::SDB::TooManyRequestedAttributes' };
  class_type SDB_UpdateCondition, { class => 'Paws::SDB::UpdateCondition' };

1;
