---
call: GetPublicKeyConfig
service: CloudFront
tests:
  - expected: EATE6CQLJ15Q4
    op: eq
    path: ETag
  - expected: 01-01-2020-000003
    op: eq
    path: PublicKeyConfig.CallerReference
  - expected: This is a test key3
    op: eq
    path: PublicKeyConfig.Comment
  - expected: |
      -----BEGIN PUBLIC KEY-----
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAp5X8pCq9EllW/vd8dYc2
      oCl58nAuSoYTfEdzR/XQGLKugBqwSSHtfyG10bAsNjS6UnqfK3vG7QSo9zgiCvCn
      KUF4J9mCEzUMCkiKcqZn169YheeMKCF04Q2xmdIMlw1FA/VGZ3HhC49hsIzAKlqC
      q/3n3nEdb4Gf4J3KvY+KW+YcZJZQQG4QzqeUG/01MHs47RzhA9xFRJDvSXf4EGTT
      eg6IAbeOlGDxiQ0d25PqZ9y+LVpa6pVy86qHnvkzbMHE2yGCiQKIuC60D4AJS/dx
      2TLLOAI8w0zm3aSvd1ktNZZMgNlnUkJFEMMlq3H7edzkb2NDNvGQ07cwJRU9h4Wt
      bwIDAQAB
      -----END PUBLIC KEY-----
    op: eq
    path: PublicKeyConfig.EncodedKey
  - expected: TestKeyPaws3
    op: eq
    path: PublicKeyConfig.Name
  - expected: 504822e6-6b01-4c3a-9d4f-566bfcd35a59
    op: eq
    path: _request_id
