---
call: ListFieldLevelEncryptionConfigs
service: CloudFront
tests:
  - expected: No Gerry you can't come!
    op: eq
    path: FieldLevelEncryptionList.Items.0.Comment
  - expected: application/x-www-form-urlencoded
    op: eq
    path: FieldLevelEncryptionList.Items.0.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.ContentType
  - expected: URLEncoded
    op: eq
    path: FieldLevelEncryptionList.Items.0.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.Format
  - expected: P14TNUMMKLEPXX
    op: eq
    path: FieldLevelEncryptionList.Items.0.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.ProfileId
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.0.ContentTypeProfileConfig.ContentTypeProfiles.Quantity
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.0.ContentTypeProfileConfig.ForwardWhenContentTypeIsUnknown
  - expected: C26GE31LXDSQZI
    op: eq
    path: FieldLevelEncryptionList.Items.0.Id
  - expected: 2020-01-09T21:16:52.064Z
    op: eq
    path: FieldLevelEncryptionList.Items.0.LastModifiedTime
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.0.QueryArgProfileConfig.ForwardWhenQueryArgProfileIsUnknown
  - expected: P14TNUMMKLEPXX
    op: eq
    path: FieldLevelEncryptionList.Items.0.QueryArgProfileConfig.QueryArgProfiles.Items.0.ProfileId
  - expected: no_conig
    op: eq
    path: FieldLevelEncryptionList.Items.0.QueryArgProfileConfig.QueryArgProfiles.Items.0.QueryArg
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.0.QueryArgProfileConfig.QueryArgProfiles.Quantity
  - expected: Please Rick. I can take care of myself!
    op: eq
    path: FieldLevelEncryptionList.Items.1.Comment
  - expected: application/x-www-form-urlencoded
    op: eq
    path: FieldLevelEncryptionList.Items.1.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.ContentType
  - expected: URLEncoded
    op: eq
    path: FieldLevelEncryptionList.Items.1.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.Format
  - expected: P14TNUMMKLEPXX
    op: eq
    path: FieldLevelEncryptionList.Items.1.ContentTypeProfileConfig.ContentTypeProfiles.Items.0.ProfileId
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.1.ContentTypeProfileConfig.ContentTypeProfiles.Quantity
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.1.ContentTypeProfileConfig.ForwardWhenContentTypeIsUnknown
  - expected: C1PAI9EKFLCYTY
    op: eq
    path: FieldLevelEncryptionList.Items.1.Id
  - expected: 2020-01-09T21:27:58.848Z
    op: eq
    path: FieldLevelEncryptionList.Items.1.LastModifiedTime
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.1.QueryArgProfileConfig.ForwardWhenQueryArgProfileIsUnknown
  - expected: P14TNUMMKLEPXX
    op: eq
    path: FieldLevelEncryptionList.Items.1.QueryArgProfileConfig.QueryArgProfiles.Items.0.ProfileId
  - expected: no_conig
    op: eq
    path: FieldLevelEncryptionList.Items.1.QueryArgProfileConfig.QueryArgProfiles.Items.0.QueryArg
  - expected: 1
    op: eq
    path: FieldLevelEncryptionList.Items.1.QueryArgProfileConfig.QueryArgProfiles.Quantity
  - expected: 5
    op: eq
    path: FieldLevelEncryptionList.MaxItems
  - expected: 2
    op: eq
    path: FieldLevelEncryptionList.Quantity
  - expected: c7285a15-c030-42dc-9625-6557bdf079ab
    op: eq
    path: _request_id
