---
call: GetBucketMetricsConfiguration
service: S3
tests:
  - expected: documents
    op: eq
    path: MetricsConfiguration.Filter.And.Prefix
  - expected: priority
    op: eq
    path: MetricsConfiguration.Filter.And.Tags.0.Key
  - expected: high
    op: eq
    path: MetricsConfiguration.Filter.And.Tags.0.Value
  - expected: class
    op: eq
    path: MetricsConfiguration.Filter.And.Tags.1.Key
  - expected: blue
    op: eq
    path: MetricsConfiguration.Filter.And.Tags.1.Value
  - expected: ImportantBlueDocuments
    op: eq
    path: MetricsConfiguration.Id
