package Paws::ACMPCA::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ACMPCA_ASN1Subject, { class => 'Paws::ACMPCA::ASN1Subject' };
  class_type ACMPCA_CertificateAuthority, { class => 'Paws::ACMPCA::CertificateAuthority' };
  class_type ACMPCA_CertificateAuthorityConfiguration, { class => 'Paws::ACMPCA::CertificateAuthorityConfiguration' };
  class_type ACMPCA_CertificateMismatchException, { class => 'Paws::ACMPCA::CertificateMismatchException' };
  class_type ACMPCA_ConcurrentModificationException, { class => 'Paws::ACMPCA::ConcurrentModificationException' };
  class_type ACMPCA_CreateCertificateAuthorityAuditReportRequest, { class => 'Paws::ACMPCA::CreateCertificateAuthorityAuditReportRequest' };
  class_type ACMPCA_CreateCertificateAuthorityAuditReportResponse, { class => 'Paws::ACMPCA::CreateCertificateAuthorityAuditReportResponse' };
  class_type ACMPCA_CreateCertificateAuthorityRequest, { class => 'Paws::ACMPCA::CreateCertificateAuthorityRequest' };
  class_type ACMPCA_CreateCertificateAuthorityResponse, { class => 'Paws::ACMPCA::CreateCertificateAuthorityResponse' };
  class_type ACMPCA_CreatePermissionRequest, { class => 'Paws::ACMPCA::CreatePermissionRequest' };
  class_type ACMPCA_CrlConfiguration, { class => 'Paws::ACMPCA::CrlConfiguration' };
  class_type ACMPCA_DeleteCertificateAuthorityRequest, { class => 'Paws::ACMPCA::DeleteCertificateAuthorityRequest' };
  class_type ACMPCA_DeletePermissionRequest, { class => 'Paws::ACMPCA::DeletePermissionRequest' };
  class_type ACMPCA_DescribeCertificateAuthorityAuditReportRequest, { class => 'Paws::ACMPCA::DescribeCertificateAuthorityAuditReportRequest' };
  class_type ACMPCA_DescribeCertificateAuthorityAuditReportResponse, { class => 'Paws::ACMPCA::DescribeCertificateAuthorityAuditReportResponse' };
  class_type ACMPCA_DescribeCertificateAuthorityRequest, { class => 'Paws::ACMPCA::DescribeCertificateAuthorityRequest' };
  class_type ACMPCA_DescribeCertificateAuthorityResponse, { class => 'Paws::ACMPCA::DescribeCertificateAuthorityResponse' };
  class_type ACMPCA_GetCertificateAuthorityCertificateRequest, { class => 'Paws::ACMPCA::GetCertificateAuthorityCertificateRequest' };
  class_type ACMPCA_GetCertificateAuthorityCertificateResponse, { class => 'Paws::ACMPCA::GetCertificateAuthorityCertificateResponse' };
  class_type ACMPCA_GetCertificateAuthorityCsrRequest, { class => 'Paws::ACMPCA::GetCertificateAuthorityCsrRequest' };
  class_type ACMPCA_GetCertificateAuthorityCsrResponse, { class => 'Paws::ACMPCA::GetCertificateAuthorityCsrResponse' };
  class_type ACMPCA_GetCertificateRequest, { class => 'Paws::ACMPCA::GetCertificateRequest' };
  class_type ACMPCA_GetCertificateResponse, { class => 'Paws::ACMPCA::GetCertificateResponse' };
  class_type ACMPCA_ImportCertificateAuthorityCertificateRequest, { class => 'Paws::ACMPCA::ImportCertificateAuthorityCertificateRequest' };
  class_type ACMPCA_InvalidArgsException, { class => 'Paws::ACMPCA::InvalidArgsException' };
  class_type ACMPCA_InvalidArnException, { class => 'Paws::ACMPCA::InvalidArnException' };
  class_type ACMPCA_InvalidNextTokenException, { class => 'Paws::ACMPCA::InvalidNextTokenException' };
  class_type ACMPCA_InvalidPolicyException, { class => 'Paws::ACMPCA::InvalidPolicyException' };
  class_type ACMPCA_InvalidRequestException, { class => 'Paws::ACMPCA::InvalidRequestException' };
  class_type ACMPCA_InvalidStateException, { class => 'Paws::ACMPCA::InvalidStateException' };
  class_type ACMPCA_InvalidTagException, { class => 'Paws::ACMPCA::InvalidTagException' };
  class_type ACMPCA_IssueCertificateRequest, { class => 'Paws::ACMPCA::IssueCertificateRequest' };
  class_type ACMPCA_IssueCertificateResponse, { class => 'Paws::ACMPCA::IssueCertificateResponse' };
  class_type ACMPCA_LimitExceededException, { class => 'Paws::ACMPCA::LimitExceededException' };
  class_type ACMPCA_ListCertificateAuthoritiesRequest, { class => 'Paws::ACMPCA::ListCertificateAuthoritiesRequest' };
  class_type ACMPCA_ListCertificateAuthoritiesResponse, { class => 'Paws::ACMPCA::ListCertificateAuthoritiesResponse' };
  class_type ACMPCA_ListPermissionsRequest, { class => 'Paws::ACMPCA::ListPermissionsRequest' };
  class_type ACMPCA_ListPermissionsResponse, { class => 'Paws::ACMPCA::ListPermissionsResponse' };
  class_type ACMPCA_ListTagsRequest, { class => 'Paws::ACMPCA::ListTagsRequest' };
  class_type ACMPCA_ListTagsResponse, { class => 'Paws::ACMPCA::ListTagsResponse' };
  class_type ACMPCA_MalformedCertificateException, { class => 'Paws::ACMPCA::MalformedCertificateException' };
  class_type ACMPCA_MalformedCSRException, { class => 'Paws::ACMPCA::MalformedCSRException' };
  class_type ACMPCA_Permission, { class => 'Paws::ACMPCA::Permission' };
  class_type ACMPCA_PermissionAlreadyExistsException, { class => 'Paws::ACMPCA::PermissionAlreadyExistsException' };
  class_type ACMPCA_RequestAlreadyProcessedException, { class => 'Paws::ACMPCA::RequestAlreadyProcessedException' };
  class_type ACMPCA_RequestFailedException, { class => 'Paws::ACMPCA::RequestFailedException' };
  class_type ACMPCA_RequestInProgressException, { class => 'Paws::ACMPCA::RequestInProgressException' };
  class_type ACMPCA_ResourceNotFoundException, { class => 'Paws::ACMPCA::ResourceNotFoundException' };
  class_type ACMPCA_RestoreCertificateAuthorityRequest, { class => 'Paws::ACMPCA::RestoreCertificateAuthorityRequest' };
  class_type ACMPCA_RevocationConfiguration, { class => 'Paws::ACMPCA::RevocationConfiguration' };
  class_type ACMPCA_RevokeCertificateRequest, { class => 'Paws::ACMPCA::RevokeCertificateRequest' };
  class_type ACMPCA_Tag, { class => 'Paws::ACMPCA::Tag' };
  class_type ACMPCA_TagCertificateAuthorityRequest, { class => 'Paws::ACMPCA::TagCertificateAuthorityRequest' };
  class_type ACMPCA_TooManyTagsException, { class => 'Paws::ACMPCA::TooManyTagsException' };
  class_type ACMPCA_UntagCertificateAuthorityRequest, { class => 'Paws::ACMPCA::UntagCertificateAuthorityRequest' };
  class_type ACMPCA_UpdateCertificateAuthorityRequest, { class => 'Paws::ACMPCA::UpdateCertificateAuthorityRequest' };
  class_type ACMPCA_Validity, { class => 'Paws::ACMPCA::Validity' };

1;
