package Paws::Transfer::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Transfer_CreateServerRequest, { class => 'Paws::Transfer::CreateServerRequest' };
  class_type Transfer_CreateServerResponse, { class => 'Paws::Transfer::CreateServerResponse' };
  class_type Transfer_CreateUserRequest, { class => 'Paws::Transfer::CreateUserRequest' };
  class_type Transfer_CreateUserResponse, { class => 'Paws::Transfer::CreateUserResponse' };
  class_type Transfer_DeleteServerRequest, { class => 'Paws::Transfer::DeleteServerRequest' };
  class_type Transfer_DeleteSshPublicKeyRequest, { class => 'Paws::Transfer::DeleteSshPublicKeyRequest' };
  class_type Transfer_DeleteUserRequest, { class => 'Paws::Transfer::DeleteUserRequest' };
  class_type Transfer_DescribedServer, { class => 'Paws::Transfer::DescribedServer' };
  class_type Transfer_DescribedUser, { class => 'Paws::Transfer::DescribedUser' };
  class_type Transfer_DescribeServerRequest, { class => 'Paws::Transfer::DescribeServerRequest' };
  class_type Transfer_DescribeServerResponse, { class => 'Paws::Transfer::DescribeServerResponse' };
  class_type Transfer_DescribeUserRequest, { class => 'Paws::Transfer::DescribeUserRequest' };
  class_type Transfer_DescribeUserResponse, { class => 'Paws::Transfer::DescribeUserResponse' };
  class_type Transfer_EndpointDetails, { class => 'Paws::Transfer::EndpointDetails' };
  class_type Transfer_IdentityProviderDetails, { class => 'Paws::Transfer::IdentityProviderDetails' };
  class_type Transfer_ImportSshPublicKeyRequest, { class => 'Paws::Transfer::ImportSshPublicKeyRequest' };
  class_type Transfer_ImportSshPublicKeyResponse, { class => 'Paws::Transfer::ImportSshPublicKeyResponse' };
  class_type Transfer_InternalServiceError, { class => 'Paws::Transfer::InternalServiceError' };
  class_type Transfer_InvalidNextTokenException, { class => 'Paws::Transfer::InvalidNextTokenException' };
  class_type Transfer_InvalidRequestException, { class => 'Paws::Transfer::InvalidRequestException' };
  class_type Transfer_ListedServer, { class => 'Paws::Transfer::ListedServer' };
  class_type Transfer_ListedUser, { class => 'Paws::Transfer::ListedUser' };
  class_type Transfer_ListServersRequest, { class => 'Paws::Transfer::ListServersRequest' };
  class_type Transfer_ListServersResponse, { class => 'Paws::Transfer::ListServersResponse' };
  class_type Transfer_ListTagsForResourceRequest, { class => 'Paws::Transfer::ListTagsForResourceRequest' };
  class_type Transfer_ListTagsForResourceResponse, { class => 'Paws::Transfer::ListTagsForResourceResponse' };
  class_type Transfer_ListUsersRequest, { class => 'Paws::Transfer::ListUsersRequest' };
  class_type Transfer_ListUsersResponse, { class => 'Paws::Transfer::ListUsersResponse' };
  class_type Transfer_ResourceExistsException, { class => 'Paws::Transfer::ResourceExistsException' };
  class_type Transfer_ResourceNotFoundException, { class => 'Paws::Transfer::ResourceNotFoundException' };
  class_type Transfer_ServiceUnavailableException, { class => 'Paws::Transfer::ServiceUnavailableException' };
  class_type Transfer_SshPublicKey, { class => 'Paws::Transfer::SshPublicKey' };
  class_type Transfer_StartServerRequest, { class => 'Paws::Transfer::StartServerRequest' };
  class_type Transfer_StopServerRequest, { class => 'Paws::Transfer::StopServerRequest' };
  class_type Transfer_Tag, { class => 'Paws::Transfer::Tag' };
  class_type Transfer_TagResourceRequest, { class => 'Paws::Transfer::TagResourceRequest' };
  class_type Transfer_TestIdentityProviderRequest, { class => 'Paws::Transfer::TestIdentityProviderRequest' };
  class_type Transfer_TestIdentityProviderResponse, { class => 'Paws::Transfer::TestIdentityProviderResponse' };
  class_type Transfer_UntagResourceRequest, { class => 'Paws::Transfer::UntagResourceRequest' };
  class_type Transfer_UpdateServerRequest, { class => 'Paws::Transfer::UpdateServerRequest' };
  class_type Transfer_UpdateServerResponse, { class => 'Paws::Transfer::UpdateServerResponse' };
  class_type Transfer_UpdateUserRequest, { class => 'Paws::Transfer::UpdateUserRequest' };
  class_type Transfer_UpdateUserResponse, { class => 'Paws::Transfer::UpdateUserResponse' };

1;
