package Paws::Budgets::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Budgets_AccessDeniedException, { class => 'Paws::Budgets::AccessDeniedException' };
  class_type Budgets_Budget, { class => 'Paws::Budgets::Budget' };
  class_type Budgets_BudgetedAndActualAmounts, { class => 'Paws::Budgets::BudgetedAndActualAmounts' };
  class_type Budgets_BudgetPerformanceHistory, { class => 'Paws::Budgets::BudgetPerformanceHistory' };
  class_type Budgets_CalculatedSpend, { class => 'Paws::Budgets::CalculatedSpend' };
  class_type Budgets_CostFilters, { class => 'Paws::Budgets::CostFilters' };
  class_type Budgets_CostTypes, { class => 'Paws::Budgets::CostTypes' };
  class_type Budgets_CreateBudgetRequest, { class => 'Paws::Budgets::CreateBudgetRequest' };
  class_type Budgets_CreateBudgetResponse, { class => 'Paws::Budgets::CreateBudgetResponse' };
  class_type Budgets_CreateNotificationRequest, { class => 'Paws::Budgets::CreateNotificationRequest' };
  class_type Budgets_CreateNotificationResponse, { class => 'Paws::Budgets::CreateNotificationResponse' };
  class_type Budgets_CreateSubscriberRequest, { class => 'Paws::Budgets::CreateSubscriberRequest' };
  class_type Budgets_CreateSubscriberResponse, { class => 'Paws::Budgets::CreateSubscriberResponse' };
  class_type Budgets_CreationLimitExceededException, { class => 'Paws::Budgets::CreationLimitExceededException' };
  class_type Budgets_DeleteBudgetRequest, { class => 'Paws::Budgets::DeleteBudgetRequest' };
  class_type Budgets_DeleteBudgetResponse, { class => 'Paws::Budgets::DeleteBudgetResponse' };
  class_type Budgets_DeleteNotificationRequest, { class => 'Paws::Budgets::DeleteNotificationRequest' };
  class_type Budgets_DeleteNotificationResponse, { class => 'Paws::Budgets::DeleteNotificationResponse' };
  class_type Budgets_DeleteSubscriberRequest, { class => 'Paws::Budgets::DeleteSubscriberRequest' };
  class_type Budgets_DeleteSubscriberResponse, { class => 'Paws::Budgets::DeleteSubscriberResponse' };
  class_type Budgets_DescribeBudgetPerformanceHistoryRequest, { class => 'Paws::Budgets::DescribeBudgetPerformanceHistoryRequest' };
  class_type Budgets_DescribeBudgetPerformanceHistoryResponse, { class => 'Paws::Budgets::DescribeBudgetPerformanceHistoryResponse' };
  class_type Budgets_DescribeBudgetRequest, { class => 'Paws::Budgets::DescribeBudgetRequest' };
  class_type Budgets_DescribeBudgetResponse, { class => 'Paws::Budgets::DescribeBudgetResponse' };
  class_type Budgets_DescribeBudgetsRequest, { class => 'Paws::Budgets::DescribeBudgetsRequest' };
  class_type Budgets_DescribeBudgetsResponse, { class => 'Paws::Budgets::DescribeBudgetsResponse' };
  class_type Budgets_DescribeNotificationsForBudgetRequest, { class => 'Paws::Budgets::DescribeNotificationsForBudgetRequest' };
  class_type Budgets_DescribeNotificationsForBudgetResponse, { class => 'Paws::Budgets::DescribeNotificationsForBudgetResponse' };
  class_type Budgets_DescribeSubscribersForNotificationRequest, { class => 'Paws::Budgets::DescribeSubscribersForNotificationRequest' };
  class_type Budgets_DescribeSubscribersForNotificationResponse, { class => 'Paws::Budgets::DescribeSubscribersForNotificationResponse' };
  class_type Budgets_DuplicateRecordException, { class => 'Paws::Budgets::DuplicateRecordException' };
  class_type Budgets_ExpiredNextTokenException, { class => 'Paws::Budgets::ExpiredNextTokenException' };
  class_type Budgets_InternalErrorException, { class => 'Paws::Budgets::InternalErrorException' };
  class_type Budgets_InvalidNextTokenException, { class => 'Paws::Budgets::InvalidNextTokenException' };
  class_type Budgets_InvalidParameterException, { class => 'Paws::Budgets::InvalidParameterException' };
  class_type Budgets_NotFoundException, { class => 'Paws::Budgets::NotFoundException' };
  class_type Budgets_Notification, { class => 'Paws::Budgets::Notification' };
  class_type Budgets_NotificationWithSubscribers, { class => 'Paws::Budgets::NotificationWithSubscribers' };
  class_type Budgets_PlannedBudgetLimits, { class => 'Paws::Budgets::PlannedBudgetLimits' };
  class_type Budgets_Spend, { class => 'Paws::Budgets::Spend' };
  class_type Budgets_Subscriber, { class => 'Paws::Budgets::Subscriber' };
  class_type Budgets_TimePeriod, { class => 'Paws::Budgets::TimePeriod' };
  class_type Budgets_UpdateBudgetRequest, { class => 'Paws::Budgets::UpdateBudgetRequest' };
  class_type Budgets_UpdateBudgetResponse, { class => 'Paws::Budgets::UpdateBudgetResponse' };
  class_type Budgets_UpdateNotificationRequest, { class => 'Paws::Budgets::UpdateNotificationRequest' };
  class_type Budgets_UpdateNotificationResponse, { class => 'Paws::Budgets::UpdateNotificationResponse' };
  class_type Budgets_UpdateSubscriberRequest, { class => 'Paws::Budgets::UpdateSubscriberRequest' };
  class_type Budgets_UpdateSubscriberResponse, { class => 'Paws::Budgets::UpdateSubscriberResponse' };

1;
