package Paws::OpsWorksCM::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type OpsWorksCM_AccountAttribute, { class => 'Paws::OpsWorksCM::AccountAttribute' };
  class_type OpsWorksCM_AssociateNodeRequest, { class => 'Paws::OpsWorksCM::AssociateNodeRequest' };
  class_type OpsWorksCM_AssociateNodeResponse, { class => 'Paws::OpsWorksCM::AssociateNodeResponse' };
  class_type OpsWorksCM_Backup, { class => 'Paws::OpsWorksCM::Backup' };
  class_type OpsWorksCM_CreateBackupRequest, { class => 'Paws::OpsWorksCM::CreateBackupRequest' };
  class_type OpsWorksCM_CreateBackupResponse, { class => 'Paws::OpsWorksCM::CreateBackupResponse' };
  class_type OpsWorksCM_CreateServerRequest, { class => 'Paws::OpsWorksCM::CreateServerRequest' };
  class_type OpsWorksCM_CreateServerResponse, { class => 'Paws::OpsWorksCM::CreateServerResponse' };
  class_type OpsWorksCM_DeleteBackupRequest, { class => 'Paws::OpsWorksCM::DeleteBackupRequest' };
  class_type OpsWorksCM_DeleteBackupResponse, { class => 'Paws::OpsWorksCM::DeleteBackupResponse' };
  class_type OpsWorksCM_DeleteServerRequest, { class => 'Paws::OpsWorksCM::DeleteServerRequest' };
  class_type OpsWorksCM_DeleteServerResponse, { class => 'Paws::OpsWorksCM::DeleteServerResponse' };
  class_type OpsWorksCM_DescribeAccountAttributesRequest, { class => 'Paws::OpsWorksCM::DescribeAccountAttributesRequest' };
  class_type OpsWorksCM_DescribeAccountAttributesResponse, { class => 'Paws::OpsWorksCM::DescribeAccountAttributesResponse' };
  class_type OpsWorksCM_DescribeBackupsRequest, { class => 'Paws::OpsWorksCM::DescribeBackupsRequest' };
  class_type OpsWorksCM_DescribeBackupsResponse, { class => 'Paws::OpsWorksCM::DescribeBackupsResponse' };
  class_type OpsWorksCM_DescribeEventsRequest, { class => 'Paws::OpsWorksCM::DescribeEventsRequest' };
  class_type OpsWorksCM_DescribeEventsResponse, { class => 'Paws::OpsWorksCM::DescribeEventsResponse' };
  class_type OpsWorksCM_DescribeNodeAssociationStatusRequest, { class => 'Paws::OpsWorksCM::DescribeNodeAssociationStatusRequest' };
  class_type OpsWorksCM_DescribeNodeAssociationStatusResponse, { class => 'Paws::OpsWorksCM::DescribeNodeAssociationStatusResponse' };
  class_type OpsWorksCM_DescribeServersRequest, { class => 'Paws::OpsWorksCM::DescribeServersRequest' };
  class_type OpsWorksCM_DescribeServersResponse, { class => 'Paws::OpsWorksCM::DescribeServersResponse' };
  class_type OpsWorksCM_DisassociateNodeRequest, { class => 'Paws::OpsWorksCM::DisassociateNodeRequest' };
  class_type OpsWorksCM_DisassociateNodeResponse, { class => 'Paws::OpsWorksCM::DisassociateNodeResponse' };
  class_type OpsWorksCM_EngineAttribute, { class => 'Paws::OpsWorksCM::EngineAttribute' };
  class_type OpsWorksCM_ExportServerEngineAttributeRequest, { class => 'Paws::OpsWorksCM::ExportServerEngineAttributeRequest' };
  class_type OpsWorksCM_ExportServerEngineAttributeResponse, { class => 'Paws::OpsWorksCM::ExportServerEngineAttributeResponse' };
  class_type OpsWorksCM_InvalidNextTokenException, { class => 'Paws::OpsWorksCM::InvalidNextTokenException' };
  class_type OpsWorksCM_InvalidStateException, { class => 'Paws::OpsWorksCM::InvalidStateException' };
  class_type OpsWorksCM_LimitExceededException, { class => 'Paws::OpsWorksCM::LimitExceededException' };
  class_type OpsWorksCM_ResourceAlreadyExistsException, { class => 'Paws::OpsWorksCM::ResourceAlreadyExistsException' };
  class_type OpsWorksCM_ResourceNotFoundException, { class => 'Paws::OpsWorksCM::ResourceNotFoundException' };
  class_type OpsWorksCM_RestoreServerRequest, { class => 'Paws::OpsWorksCM::RestoreServerRequest' };
  class_type OpsWorksCM_RestoreServerResponse, { class => 'Paws::OpsWorksCM::RestoreServerResponse' };
  class_type OpsWorksCM_Server, { class => 'Paws::OpsWorksCM::Server' };
  class_type OpsWorksCM_ServerEvent, { class => 'Paws::OpsWorksCM::ServerEvent' };
  class_type OpsWorksCM_StartMaintenanceRequest, { class => 'Paws::OpsWorksCM::StartMaintenanceRequest' };
  class_type OpsWorksCM_StartMaintenanceResponse, { class => 'Paws::OpsWorksCM::StartMaintenanceResponse' };
  class_type OpsWorksCM_UpdateServerEngineAttributesRequest, { class => 'Paws::OpsWorksCM::UpdateServerEngineAttributesRequest' };
  class_type OpsWorksCM_UpdateServerEngineAttributesResponse, { class => 'Paws::OpsWorksCM::UpdateServerEngineAttributesResponse' };
  class_type OpsWorksCM_UpdateServerRequest, { class => 'Paws::OpsWorksCM::UpdateServerRequest' };
  class_type OpsWorksCM_UpdateServerResponse, { class => 'Paws::OpsWorksCM::UpdateServerResponse' };
  class_type OpsWorksCM_ValidationException, { class => 'Paws::OpsWorksCM::ValidationException' };

1;
