package Paws::GlobalAccelerator::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type GlobalAccelerator_Accelerator, { class => 'Paws::GlobalAccelerator::Accelerator' };
  class_type GlobalAccelerator_AcceleratorAttributes, { class => 'Paws::GlobalAccelerator::AcceleratorAttributes' };
  class_type GlobalAccelerator_AcceleratorNotDisabledException, { class => 'Paws::GlobalAccelerator::AcceleratorNotDisabledException' };
  class_type GlobalAccelerator_AcceleratorNotFoundException, { class => 'Paws::GlobalAccelerator::AcceleratorNotFoundException' };
  class_type GlobalAccelerator_AccessDeniedException, { class => 'Paws::GlobalAccelerator::AccessDeniedException' };
  class_type GlobalAccelerator_AssociatedEndpointGroupFoundException, { class => 'Paws::GlobalAccelerator::AssociatedEndpointGroupFoundException' };
  class_type GlobalAccelerator_AssociatedListenerFoundException, { class => 'Paws::GlobalAccelerator::AssociatedListenerFoundException' };
  class_type GlobalAccelerator_CreateAcceleratorRequest, { class => 'Paws::GlobalAccelerator::CreateAcceleratorRequest' };
  class_type GlobalAccelerator_CreateAcceleratorResponse, { class => 'Paws::GlobalAccelerator::CreateAcceleratorResponse' };
  class_type GlobalAccelerator_CreateEndpointGroupRequest, { class => 'Paws::GlobalAccelerator::CreateEndpointGroupRequest' };
  class_type GlobalAccelerator_CreateEndpointGroupResponse, { class => 'Paws::GlobalAccelerator::CreateEndpointGroupResponse' };
  class_type GlobalAccelerator_CreateListenerRequest, { class => 'Paws::GlobalAccelerator::CreateListenerRequest' };
  class_type GlobalAccelerator_CreateListenerResponse, { class => 'Paws::GlobalAccelerator::CreateListenerResponse' };
  class_type GlobalAccelerator_DeleteAcceleratorRequest, { class => 'Paws::GlobalAccelerator::DeleteAcceleratorRequest' };
  class_type GlobalAccelerator_DeleteEndpointGroupRequest, { class => 'Paws::GlobalAccelerator::DeleteEndpointGroupRequest' };
  class_type GlobalAccelerator_DeleteListenerRequest, { class => 'Paws::GlobalAccelerator::DeleteListenerRequest' };
  class_type GlobalAccelerator_DescribeAcceleratorAttributesRequest, { class => 'Paws::GlobalAccelerator::DescribeAcceleratorAttributesRequest' };
  class_type GlobalAccelerator_DescribeAcceleratorAttributesResponse, { class => 'Paws::GlobalAccelerator::DescribeAcceleratorAttributesResponse' };
  class_type GlobalAccelerator_DescribeAcceleratorRequest, { class => 'Paws::GlobalAccelerator::DescribeAcceleratorRequest' };
  class_type GlobalAccelerator_DescribeAcceleratorResponse, { class => 'Paws::GlobalAccelerator::DescribeAcceleratorResponse' };
  class_type GlobalAccelerator_DescribeEndpointGroupRequest, { class => 'Paws::GlobalAccelerator::DescribeEndpointGroupRequest' };
  class_type GlobalAccelerator_DescribeEndpointGroupResponse, { class => 'Paws::GlobalAccelerator::DescribeEndpointGroupResponse' };
  class_type GlobalAccelerator_DescribeListenerRequest, { class => 'Paws::GlobalAccelerator::DescribeListenerRequest' };
  class_type GlobalAccelerator_DescribeListenerResponse, { class => 'Paws::GlobalAccelerator::DescribeListenerResponse' };
  class_type GlobalAccelerator_EndpointConfiguration, { class => 'Paws::GlobalAccelerator::EndpointConfiguration' };
  class_type GlobalAccelerator_EndpointDescription, { class => 'Paws::GlobalAccelerator::EndpointDescription' };
  class_type GlobalAccelerator_EndpointGroup, { class => 'Paws::GlobalAccelerator::EndpointGroup' };
  class_type GlobalAccelerator_EndpointGroupAlreadyExistsException, { class => 'Paws::GlobalAccelerator::EndpointGroupAlreadyExistsException' };
  class_type GlobalAccelerator_EndpointGroupNotFoundException, { class => 'Paws::GlobalAccelerator::EndpointGroupNotFoundException' };
  class_type GlobalAccelerator_InternalServiceErrorException, { class => 'Paws::GlobalAccelerator::InternalServiceErrorException' };
  class_type GlobalAccelerator_InvalidArgumentException, { class => 'Paws::GlobalAccelerator::InvalidArgumentException' };
  class_type GlobalAccelerator_InvalidNextTokenException, { class => 'Paws::GlobalAccelerator::InvalidNextTokenException' };
  class_type GlobalAccelerator_InvalidPortRangeException, { class => 'Paws::GlobalAccelerator::InvalidPortRangeException' };
  class_type GlobalAccelerator_IpSet, { class => 'Paws::GlobalAccelerator::IpSet' };
  class_type GlobalAccelerator_LimitExceededException, { class => 'Paws::GlobalAccelerator::LimitExceededException' };
  class_type GlobalAccelerator_ListAcceleratorsRequest, { class => 'Paws::GlobalAccelerator::ListAcceleratorsRequest' };
  class_type GlobalAccelerator_ListAcceleratorsResponse, { class => 'Paws::GlobalAccelerator::ListAcceleratorsResponse' };
  class_type GlobalAccelerator_ListEndpointGroupsRequest, { class => 'Paws::GlobalAccelerator::ListEndpointGroupsRequest' };
  class_type GlobalAccelerator_ListEndpointGroupsResponse, { class => 'Paws::GlobalAccelerator::ListEndpointGroupsResponse' };
  class_type GlobalAccelerator_Listener, { class => 'Paws::GlobalAccelerator::Listener' };
  class_type GlobalAccelerator_ListenerNotFoundException, { class => 'Paws::GlobalAccelerator::ListenerNotFoundException' };
  class_type GlobalAccelerator_ListListenersRequest, { class => 'Paws::GlobalAccelerator::ListListenersRequest' };
  class_type GlobalAccelerator_ListListenersResponse, { class => 'Paws::GlobalAccelerator::ListListenersResponse' };
  class_type GlobalAccelerator_PortRange, { class => 'Paws::GlobalAccelerator::PortRange' };
  class_type GlobalAccelerator_UpdateAcceleratorAttributesRequest, { class => 'Paws::GlobalAccelerator::UpdateAcceleratorAttributesRequest' };
  class_type GlobalAccelerator_UpdateAcceleratorAttributesResponse, { class => 'Paws::GlobalAccelerator::UpdateAcceleratorAttributesResponse' };
  class_type GlobalAccelerator_UpdateAcceleratorRequest, { class => 'Paws::GlobalAccelerator::UpdateAcceleratorRequest' };
  class_type GlobalAccelerator_UpdateAcceleratorResponse, { class => 'Paws::GlobalAccelerator::UpdateAcceleratorResponse' };
  class_type GlobalAccelerator_UpdateEndpointGroupRequest, { class => 'Paws::GlobalAccelerator::UpdateEndpointGroupRequest' };
  class_type GlobalAccelerator_UpdateEndpointGroupResponse, { class => 'Paws::GlobalAccelerator::UpdateEndpointGroupResponse' };
  class_type GlobalAccelerator_UpdateListenerRequest, { class => 'Paws::GlobalAccelerator::UpdateListenerRequest' };
  class_type GlobalAccelerator_UpdateListenerResponse, { class => 'Paws::GlobalAccelerator::UpdateListenerResponse' };

1;
