package Paws::Quicksight::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Quicksight_AccessDeniedException, { class => 'Paws::Quicksight::AccessDeniedException' };
  class_type Quicksight_CreateGroupMembershipRequest, { class => 'Paws::Quicksight::CreateGroupMembershipRequest' };
  class_type Quicksight_CreateGroupMembershipResponse, { class => 'Paws::Quicksight::CreateGroupMembershipResponse' };
  class_type Quicksight_CreateGroupRequest, { class => 'Paws::Quicksight::CreateGroupRequest' };
  class_type Quicksight_CreateGroupResponse, { class => 'Paws::Quicksight::CreateGroupResponse' };
  class_type Quicksight_DeleteGroupMembershipRequest, { class => 'Paws::Quicksight::DeleteGroupMembershipRequest' };
  class_type Quicksight_DeleteGroupMembershipResponse, { class => 'Paws::Quicksight::DeleteGroupMembershipResponse' };
  class_type Quicksight_DeleteGroupRequest, { class => 'Paws::Quicksight::DeleteGroupRequest' };
  class_type Quicksight_DeleteGroupResponse, { class => 'Paws::Quicksight::DeleteGroupResponse' };
  class_type Quicksight_DeleteUserByPrincipalIdRequest, { class => 'Paws::Quicksight::DeleteUserByPrincipalIdRequest' };
  class_type Quicksight_DeleteUserByPrincipalIdResponse, { class => 'Paws::Quicksight::DeleteUserByPrincipalIdResponse' };
  class_type Quicksight_DeleteUserRequest, { class => 'Paws::Quicksight::DeleteUserRequest' };
  class_type Quicksight_DeleteUserResponse, { class => 'Paws::Quicksight::DeleteUserResponse' };
  class_type Quicksight_DescribeGroupRequest, { class => 'Paws::Quicksight::DescribeGroupRequest' };
  class_type Quicksight_DescribeGroupResponse, { class => 'Paws::Quicksight::DescribeGroupResponse' };
  class_type Quicksight_DescribeUserRequest, { class => 'Paws::Quicksight::DescribeUserRequest' };
  class_type Quicksight_DescribeUserResponse, { class => 'Paws::Quicksight::DescribeUserResponse' };
  class_type Quicksight_DomainNotWhitelistedException, { class => 'Paws::Quicksight::DomainNotWhitelistedException' };
  class_type Quicksight_GetDashboardEmbedUrlRequest, { class => 'Paws::Quicksight::GetDashboardEmbedUrlRequest' };
  class_type Quicksight_GetDashboardEmbedUrlResponse, { class => 'Paws::Quicksight::GetDashboardEmbedUrlResponse' };
  class_type Quicksight_Group, { class => 'Paws::Quicksight::Group' };
  class_type Quicksight_GroupMember, { class => 'Paws::Quicksight::GroupMember' };
  class_type Quicksight_IdentityTypeNotSupportedException, { class => 'Paws::Quicksight::IdentityTypeNotSupportedException' };
  class_type Quicksight_InternalFailureException, { class => 'Paws::Quicksight::InternalFailureException' };
  class_type Quicksight_InvalidNextTokenException, { class => 'Paws::Quicksight::InvalidNextTokenException' };
  class_type Quicksight_InvalidParameterValueException, { class => 'Paws::Quicksight::InvalidParameterValueException' };
  class_type Quicksight_LimitExceededException, { class => 'Paws::Quicksight::LimitExceededException' };
  class_type Quicksight_ListGroupMembershipsRequest, { class => 'Paws::Quicksight::ListGroupMembershipsRequest' };
  class_type Quicksight_ListGroupMembershipsResponse, { class => 'Paws::Quicksight::ListGroupMembershipsResponse' };
  class_type Quicksight_ListGroupsRequest, { class => 'Paws::Quicksight::ListGroupsRequest' };
  class_type Quicksight_ListGroupsResponse, { class => 'Paws::Quicksight::ListGroupsResponse' };
  class_type Quicksight_ListUserGroupsRequest, { class => 'Paws::Quicksight::ListUserGroupsRequest' };
  class_type Quicksight_ListUserGroupsResponse, { class => 'Paws::Quicksight::ListUserGroupsResponse' };
  class_type Quicksight_ListUsersRequest, { class => 'Paws::Quicksight::ListUsersRequest' };
  class_type Quicksight_ListUsersResponse, { class => 'Paws::Quicksight::ListUsersResponse' };
  class_type Quicksight_PreconditionNotMetException, { class => 'Paws::Quicksight::PreconditionNotMetException' };
  class_type Quicksight_QuickSightUserNotFoundException, { class => 'Paws::Quicksight::QuickSightUserNotFoundException' };
  class_type Quicksight_RegisterUserRequest, { class => 'Paws::Quicksight::RegisterUserRequest' };
  class_type Quicksight_RegisterUserResponse, { class => 'Paws::Quicksight::RegisterUserResponse' };
  class_type Quicksight_ResourceExistsException, { class => 'Paws::Quicksight::ResourceExistsException' };
  class_type Quicksight_ResourceNotFoundException, { class => 'Paws::Quicksight::ResourceNotFoundException' };
  class_type Quicksight_ResourceUnavailableException, { class => 'Paws::Quicksight::ResourceUnavailableException' };
  class_type Quicksight_SessionLifetimeInMinutesInvalidException, { class => 'Paws::Quicksight::SessionLifetimeInMinutesInvalidException' };
  class_type Quicksight_ThrottlingException, { class => 'Paws::Quicksight::ThrottlingException' };
  class_type Quicksight_UnsupportedUserEditionException, { class => 'Paws::Quicksight::UnsupportedUserEditionException' };
  class_type Quicksight_UpdateGroupRequest, { class => 'Paws::Quicksight::UpdateGroupRequest' };
  class_type Quicksight_UpdateGroupResponse, { class => 'Paws::Quicksight::UpdateGroupResponse' };
  class_type Quicksight_UpdateUserRequest, { class => 'Paws::Quicksight::UpdateUserRequest' };
  class_type Quicksight_UpdateUserResponse, { class => 'Paws::Quicksight::UpdateUserResponse' };
  class_type Quicksight_User, { class => 'Paws::Quicksight::User' };

1;
