package Paws::CodeStarNotifications::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CodeStarNotifications_AccessDeniedException, { class => 'Paws::CodeStarNotifications::AccessDeniedException' };
  class_type CodeStarNotifications_ConcurrentModificationException, { class => 'Paws::CodeStarNotifications::ConcurrentModificationException' };
  class_type CodeStarNotifications_ConfigurationException, { class => 'Paws::CodeStarNotifications::ConfigurationException' };
  class_type CodeStarNotifications_CreateNotificationRuleRequest, { class => 'Paws::CodeStarNotifications::CreateNotificationRuleRequest' };
  class_type CodeStarNotifications_CreateNotificationRuleResult, { class => 'Paws::CodeStarNotifications::CreateNotificationRuleResult' };
  class_type CodeStarNotifications_DeleteNotificationRuleRequest, { class => 'Paws::CodeStarNotifications::DeleteNotificationRuleRequest' };
  class_type CodeStarNotifications_DeleteNotificationRuleResult, { class => 'Paws::CodeStarNotifications::DeleteNotificationRuleResult' };
  class_type CodeStarNotifications_DeleteTargetRequest, { class => 'Paws::CodeStarNotifications::DeleteTargetRequest' };
  class_type CodeStarNotifications_DeleteTargetResult, { class => 'Paws::CodeStarNotifications::DeleteTargetResult' };
  class_type CodeStarNotifications_DescribeNotificationRuleRequest, { class => 'Paws::CodeStarNotifications::DescribeNotificationRuleRequest' };
  class_type CodeStarNotifications_DescribeNotificationRuleResult, { class => 'Paws::CodeStarNotifications::DescribeNotificationRuleResult' };
  class_type CodeStarNotifications_EventTypeSummary, { class => 'Paws::CodeStarNotifications::EventTypeSummary' };
  class_type CodeStarNotifications_InvalidNextTokenException, { class => 'Paws::CodeStarNotifications::InvalidNextTokenException' };
  class_type CodeStarNotifications_LimitExceededException, { class => 'Paws::CodeStarNotifications::LimitExceededException' };
  class_type CodeStarNotifications_ListEventTypesFilter, { class => 'Paws::CodeStarNotifications::ListEventTypesFilter' };
  class_type CodeStarNotifications_ListEventTypesRequest, { class => 'Paws::CodeStarNotifications::ListEventTypesRequest' };
  class_type CodeStarNotifications_ListEventTypesResult, { class => 'Paws::CodeStarNotifications::ListEventTypesResult' };
  class_type CodeStarNotifications_ListNotificationRulesFilter, { class => 'Paws::CodeStarNotifications::ListNotificationRulesFilter' };
  class_type CodeStarNotifications_ListNotificationRulesRequest, { class => 'Paws::CodeStarNotifications::ListNotificationRulesRequest' };
  class_type CodeStarNotifications_ListNotificationRulesResult, { class => 'Paws::CodeStarNotifications::ListNotificationRulesResult' };
  class_type CodeStarNotifications_ListTagsForResourceRequest, { class => 'Paws::CodeStarNotifications::ListTagsForResourceRequest' };
  class_type CodeStarNotifications_ListTagsForResourceResult, { class => 'Paws::CodeStarNotifications::ListTagsForResourceResult' };
  class_type CodeStarNotifications_ListTargetsFilter, { class => 'Paws::CodeStarNotifications::ListTargetsFilter' };
  class_type CodeStarNotifications_ListTargetsRequest, { class => 'Paws::CodeStarNotifications::ListTargetsRequest' };
  class_type CodeStarNotifications_ListTargetsResult, { class => 'Paws::CodeStarNotifications::ListTargetsResult' };
  class_type CodeStarNotifications_NotificationRuleSummary, { class => 'Paws::CodeStarNotifications::NotificationRuleSummary' };
  class_type CodeStarNotifications_ResourceAlreadyExistsException, { class => 'Paws::CodeStarNotifications::ResourceAlreadyExistsException' };
  class_type CodeStarNotifications_ResourceNotFoundException, { class => 'Paws::CodeStarNotifications::ResourceNotFoundException' };
  class_type CodeStarNotifications_SubscribeRequest, { class => 'Paws::CodeStarNotifications::SubscribeRequest' };
  class_type CodeStarNotifications_SubscribeResult, { class => 'Paws::CodeStarNotifications::SubscribeResult' };
  class_type CodeStarNotifications_TagResourceRequest, { class => 'Paws::CodeStarNotifications::TagResourceRequest' };
  class_type CodeStarNotifications_TagResourceResult, { class => 'Paws::CodeStarNotifications::TagResourceResult' };
  class_type CodeStarNotifications_Tags, { class => 'Paws::CodeStarNotifications::Tags' };
  class_type CodeStarNotifications_Target, { class => 'Paws::CodeStarNotifications::Target' };
  class_type CodeStarNotifications_TargetSummary, { class => 'Paws::CodeStarNotifications::TargetSummary' };
  class_type CodeStarNotifications_UnsubscribeRequest, { class => 'Paws::CodeStarNotifications::UnsubscribeRequest' };
  class_type CodeStarNotifications_UnsubscribeResult, { class => 'Paws::CodeStarNotifications::UnsubscribeResult' };
  class_type CodeStarNotifications_UntagResourceRequest, { class => 'Paws::CodeStarNotifications::UntagResourceRequest' };
  class_type CodeStarNotifications_UntagResourceResult, { class => 'Paws::CodeStarNotifications::UntagResourceResult' };
  class_type CodeStarNotifications_UpdateNotificationRuleRequest, { class => 'Paws::CodeStarNotifications::UpdateNotificationRuleRequest' };
  class_type CodeStarNotifications_UpdateNotificationRuleResult, { class => 'Paws::CodeStarNotifications::UpdateNotificationRuleResult' };
  class_type CodeStarNotifications_ValidationException, { class => 'Paws::CodeStarNotifications::ValidationException' };

1;
