package Paws::ResourceGroups::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ResourceGroups_BadRequestException, { class => 'Paws::ResourceGroups::BadRequestException' };
  class_type ResourceGroups_CreateGroupInput, { class => 'Paws::ResourceGroups::CreateGroupInput' };
  class_type ResourceGroups_CreateGroupOutput, { class => 'Paws::ResourceGroups::CreateGroupOutput' };
  class_type ResourceGroups_DeleteGroupInput, { class => 'Paws::ResourceGroups::DeleteGroupInput' };
  class_type ResourceGroups_DeleteGroupOutput, { class => 'Paws::ResourceGroups::DeleteGroupOutput' };
  class_type ResourceGroups_ForbiddenException, { class => 'Paws::ResourceGroups::ForbiddenException' };
  class_type ResourceGroups_GetGroupInput, { class => 'Paws::ResourceGroups::GetGroupInput' };
  class_type ResourceGroups_GetGroupOutput, { class => 'Paws::ResourceGroups::GetGroupOutput' };
  class_type ResourceGroups_GetGroupQueryInput, { class => 'Paws::ResourceGroups::GetGroupQueryInput' };
  class_type ResourceGroups_GetGroupQueryOutput, { class => 'Paws::ResourceGroups::GetGroupQueryOutput' };
  class_type ResourceGroups_GetTagsInput, { class => 'Paws::ResourceGroups::GetTagsInput' };
  class_type ResourceGroups_GetTagsOutput, { class => 'Paws::ResourceGroups::GetTagsOutput' };
  class_type ResourceGroups_Group, { class => 'Paws::ResourceGroups::Group' };
  class_type ResourceGroups_GroupFilter, { class => 'Paws::ResourceGroups::GroupFilter' };
  class_type ResourceGroups_GroupIdentifier, { class => 'Paws::ResourceGroups::GroupIdentifier' };
  class_type ResourceGroups_GroupQuery, { class => 'Paws::ResourceGroups::GroupQuery' };
  class_type ResourceGroups_InternalServerErrorException, { class => 'Paws::ResourceGroups::InternalServerErrorException' };
  class_type ResourceGroups_ListGroupResourcesInput, { class => 'Paws::ResourceGroups::ListGroupResourcesInput' };
  class_type ResourceGroups_ListGroupResourcesOutput, { class => 'Paws::ResourceGroups::ListGroupResourcesOutput' };
  class_type ResourceGroups_ListGroupsInput, { class => 'Paws::ResourceGroups::ListGroupsInput' };
  class_type ResourceGroups_ListGroupsOutput, { class => 'Paws::ResourceGroups::ListGroupsOutput' };
  class_type ResourceGroups_MethodNotAllowedException, { class => 'Paws::ResourceGroups::MethodNotAllowedException' };
  class_type ResourceGroups_NotFoundException, { class => 'Paws::ResourceGroups::NotFoundException' };
  class_type ResourceGroups_QueryError, { class => 'Paws::ResourceGroups::QueryError' };
  class_type ResourceGroups_ResourceFilter, { class => 'Paws::ResourceGroups::ResourceFilter' };
  class_type ResourceGroups_ResourceIdentifier, { class => 'Paws::ResourceGroups::ResourceIdentifier' };
  class_type ResourceGroups_ResourceQuery, { class => 'Paws::ResourceGroups::ResourceQuery' };
  class_type ResourceGroups_SearchResourcesInput, { class => 'Paws::ResourceGroups::SearchResourcesInput' };
  class_type ResourceGroups_SearchResourcesOutput, { class => 'Paws::ResourceGroups::SearchResourcesOutput' };
  class_type ResourceGroups_TagInput, { class => 'Paws::ResourceGroups::TagInput' };
  class_type ResourceGroups_TagOutput, { class => 'Paws::ResourceGroups::TagOutput' };
  class_type ResourceGroups_Tags, { class => 'Paws::ResourceGroups::Tags' };
  class_type ResourceGroups_TooManyRequestsException, { class => 'Paws::ResourceGroups::TooManyRequestsException' };
  class_type ResourceGroups_UnauthorizedException, { class => 'Paws::ResourceGroups::UnauthorizedException' };
  class_type ResourceGroups_UntagInput, { class => 'Paws::ResourceGroups::UntagInput' };
  class_type ResourceGroups_UntagOutput, { class => 'Paws::ResourceGroups::UntagOutput' };
  class_type ResourceGroups_UpdateGroupInput, { class => 'Paws::ResourceGroups::UpdateGroupInput' };
  class_type ResourceGroups_UpdateGroupOutput, { class => 'Paws::ResourceGroups::UpdateGroupOutput' };
  class_type ResourceGroups_UpdateGroupQueryInput, { class => 'Paws::ResourceGroups::UpdateGroupQueryInput' };
  class_type ResourceGroups_UpdateGroupQueryOutput, { class => 'Paws::ResourceGroups::UpdateGroupQueryOutput' };

1;
