package Paws::Support::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Support_AddAttachmentsToSetRequest, { class => 'Paws::Support::AddAttachmentsToSetRequest' };
  class_type Support_AddAttachmentsToSetResponse, { class => 'Paws::Support::AddAttachmentsToSetResponse' };
  class_type Support_AddCommunicationToCaseRequest, { class => 'Paws::Support::AddCommunicationToCaseRequest' };
  class_type Support_AddCommunicationToCaseResponse, { class => 'Paws::Support::AddCommunicationToCaseResponse' };
  class_type Support_Attachment, { class => 'Paws::Support::Attachment' };
  class_type Support_AttachmentDetails, { class => 'Paws::Support::AttachmentDetails' };
  class_type Support_AttachmentIdNotFound, { class => 'Paws::Support::AttachmentIdNotFound' };
  class_type Support_AttachmentLimitExceeded, { class => 'Paws::Support::AttachmentLimitExceeded' };
  class_type Support_AttachmentSetExpired, { class => 'Paws::Support::AttachmentSetExpired' };
  class_type Support_AttachmentSetIdNotFound, { class => 'Paws::Support::AttachmentSetIdNotFound' };
  class_type Support_AttachmentSetSizeLimitExceeded, { class => 'Paws::Support::AttachmentSetSizeLimitExceeded' };
  class_type Support_CaseCreationLimitExceeded, { class => 'Paws::Support::CaseCreationLimitExceeded' };
  class_type Support_CaseDetails, { class => 'Paws::Support::CaseDetails' };
  class_type Support_CaseIdNotFound, { class => 'Paws::Support::CaseIdNotFound' };
  class_type Support_Category, { class => 'Paws::Support::Category' };
  class_type Support_Communication, { class => 'Paws::Support::Communication' };
  class_type Support_CreateCaseRequest, { class => 'Paws::Support::CreateCaseRequest' };
  class_type Support_CreateCaseResponse, { class => 'Paws::Support::CreateCaseResponse' };
  class_type Support_DescribeAttachmentLimitExceeded, { class => 'Paws::Support::DescribeAttachmentLimitExceeded' };
  class_type Support_DescribeAttachmentRequest, { class => 'Paws::Support::DescribeAttachmentRequest' };
  class_type Support_DescribeAttachmentResponse, { class => 'Paws::Support::DescribeAttachmentResponse' };
  class_type Support_DescribeCasesRequest, { class => 'Paws::Support::DescribeCasesRequest' };
  class_type Support_DescribeCasesResponse, { class => 'Paws::Support::DescribeCasesResponse' };
  class_type Support_DescribeCommunicationsRequest, { class => 'Paws::Support::DescribeCommunicationsRequest' };
  class_type Support_DescribeCommunicationsResponse, { class => 'Paws::Support::DescribeCommunicationsResponse' };
  class_type Support_DescribeServicesRequest, { class => 'Paws::Support::DescribeServicesRequest' };
  class_type Support_DescribeServicesResponse, { class => 'Paws::Support::DescribeServicesResponse' };
  class_type Support_DescribeSeverityLevelsRequest, { class => 'Paws::Support::DescribeSeverityLevelsRequest' };
  class_type Support_DescribeSeverityLevelsResponse, { class => 'Paws::Support::DescribeSeverityLevelsResponse' };
  class_type Support_DescribeTrustedAdvisorCheckRefreshStatusesRequest, { class => 'Paws::Support::DescribeTrustedAdvisorCheckRefreshStatusesRequest' };
  class_type Support_DescribeTrustedAdvisorCheckRefreshStatusesResponse, { class => 'Paws::Support::DescribeTrustedAdvisorCheckRefreshStatusesResponse' };
  class_type Support_DescribeTrustedAdvisorCheckResultRequest, { class => 'Paws::Support::DescribeTrustedAdvisorCheckResultRequest' };
  class_type Support_DescribeTrustedAdvisorCheckResultResponse, { class => 'Paws::Support::DescribeTrustedAdvisorCheckResultResponse' };
  class_type Support_DescribeTrustedAdvisorChecksRequest, { class => 'Paws::Support::DescribeTrustedAdvisorChecksRequest' };
  class_type Support_DescribeTrustedAdvisorChecksResponse, { class => 'Paws::Support::DescribeTrustedAdvisorChecksResponse' };
  class_type Support_DescribeTrustedAdvisorCheckSummariesRequest, { class => 'Paws::Support::DescribeTrustedAdvisorCheckSummariesRequest' };
  class_type Support_DescribeTrustedAdvisorCheckSummariesResponse, { class => 'Paws::Support::DescribeTrustedAdvisorCheckSummariesResponse' };
  class_type Support_InternalServerError, { class => 'Paws::Support::InternalServerError' };
  class_type Support_RecentCaseCommunications, { class => 'Paws::Support::RecentCaseCommunications' };
  class_type Support_RefreshTrustedAdvisorCheckRequest, { class => 'Paws::Support::RefreshTrustedAdvisorCheckRequest' };
  class_type Support_RefreshTrustedAdvisorCheckResponse, { class => 'Paws::Support::RefreshTrustedAdvisorCheckResponse' };
  class_type Support_ResolveCaseRequest, { class => 'Paws::Support::ResolveCaseRequest' };
  class_type Support_ResolveCaseResponse, { class => 'Paws::Support::ResolveCaseResponse' };
  class_type Support_Service, { class => 'Paws::Support::Service' };
  class_type Support_SeverityLevel, { class => 'Paws::Support::SeverityLevel' };
  class_type Support_TrustedAdvisorCategorySpecificSummary, { class => 'Paws::Support::TrustedAdvisorCategorySpecificSummary' };
  class_type Support_TrustedAdvisorCheckDescription, { class => 'Paws::Support::TrustedAdvisorCheckDescription' };
  class_type Support_TrustedAdvisorCheckRefreshStatus, { class => 'Paws::Support::TrustedAdvisorCheckRefreshStatus' };
  class_type Support_TrustedAdvisorCheckResult, { class => 'Paws::Support::TrustedAdvisorCheckResult' };
  class_type Support_TrustedAdvisorCheckSummary, { class => 'Paws::Support::TrustedAdvisorCheckSummary' };
  class_type Support_TrustedAdvisorCostOptimizingSummary, { class => 'Paws::Support::TrustedAdvisorCostOptimizingSummary' };
  class_type Support_TrustedAdvisorResourceDetail, { class => 'Paws::Support::TrustedAdvisorResourceDetail' };
  class_type Support_TrustedAdvisorResourcesSummary, { class => 'Paws::Support::TrustedAdvisorResourcesSummary' };

1;
