package Paws::IoT1ClickProjects::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type IoT1ClickProjects_AssociateDeviceWithPlacementRequest, { class => 'Paws::IoT1ClickProjects::AssociateDeviceWithPlacementRequest' };
  class_type IoT1ClickProjects_AssociateDeviceWithPlacementResponse, { class => 'Paws::IoT1ClickProjects::AssociateDeviceWithPlacementResponse' };
  class_type IoT1ClickProjects_CreatePlacementRequest, { class => 'Paws::IoT1ClickProjects::CreatePlacementRequest' };
  class_type IoT1ClickProjects_CreatePlacementResponse, { class => 'Paws::IoT1ClickProjects::CreatePlacementResponse' };
  class_type IoT1ClickProjects_CreateProjectRequest, { class => 'Paws::IoT1ClickProjects::CreateProjectRequest' };
  class_type IoT1ClickProjects_CreateProjectResponse, { class => 'Paws::IoT1ClickProjects::CreateProjectResponse' };
  class_type IoT1ClickProjects_DefaultPlacementAttributeMap, { class => 'Paws::IoT1ClickProjects::DefaultPlacementAttributeMap' };
  class_type IoT1ClickProjects_DeletePlacementRequest, { class => 'Paws::IoT1ClickProjects::DeletePlacementRequest' };
  class_type IoT1ClickProjects_DeletePlacementResponse, { class => 'Paws::IoT1ClickProjects::DeletePlacementResponse' };
  class_type IoT1ClickProjects_DeleteProjectRequest, { class => 'Paws::IoT1ClickProjects::DeleteProjectRequest' };
  class_type IoT1ClickProjects_DeleteProjectResponse, { class => 'Paws::IoT1ClickProjects::DeleteProjectResponse' };
  class_type IoT1ClickProjects_DescribePlacementRequest, { class => 'Paws::IoT1ClickProjects::DescribePlacementRequest' };
  class_type IoT1ClickProjects_DescribePlacementResponse, { class => 'Paws::IoT1ClickProjects::DescribePlacementResponse' };
  class_type IoT1ClickProjects_DescribeProjectRequest, { class => 'Paws::IoT1ClickProjects::DescribeProjectRequest' };
  class_type IoT1ClickProjects_DescribeProjectResponse, { class => 'Paws::IoT1ClickProjects::DescribeProjectResponse' };
  class_type IoT1ClickProjects_DeviceCallbackOverrideMap, { class => 'Paws::IoT1ClickProjects::DeviceCallbackOverrideMap' };
  class_type IoT1ClickProjects_DeviceMap, { class => 'Paws::IoT1ClickProjects::DeviceMap' };
  class_type IoT1ClickProjects_DeviceTemplate, { class => 'Paws::IoT1ClickProjects::DeviceTemplate' };
  class_type IoT1ClickProjects_DeviceTemplateMap, { class => 'Paws::IoT1ClickProjects::DeviceTemplateMap' };
  class_type IoT1ClickProjects_DisassociateDeviceFromPlacementRequest, { class => 'Paws::IoT1ClickProjects::DisassociateDeviceFromPlacementRequest' };
  class_type IoT1ClickProjects_DisassociateDeviceFromPlacementResponse, { class => 'Paws::IoT1ClickProjects::DisassociateDeviceFromPlacementResponse' };
  class_type IoT1ClickProjects_GetDevicesInPlacementRequest, { class => 'Paws::IoT1ClickProjects::GetDevicesInPlacementRequest' };
  class_type IoT1ClickProjects_GetDevicesInPlacementResponse, { class => 'Paws::IoT1ClickProjects::GetDevicesInPlacementResponse' };
  class_type IoT1ClickProjects_InternalFailureException, { class => 'Paws::IoT1ClickProjects::InternalFailureException' };
  class_type IoT1ClickProjects_InvalidRequestException, { class => 'Paws::IoT1ClickProjects::InvalidRequestException' };
  class_type IoT1ClickProjects_ListPlacementsRequest, { class => 'Paws::IoT1ClickProjects::ListPlacementsRequest' };
  class_type IoT1ClickProjects_ListPlacementsResponse, { class => 'Paws::IoT1ClickProjects::ListPlacementsResponse' };
  class_type IoT1ClickProjects_ListProjectsRequest, { class => 'Paws::IoT1ClickProjects::ListProjectsRequest' };
  class_type IoT1ClickProjects_ListProjectsResponse, { class => 'Paws::IoT1ClickProjects::ListProjectsResponse' };
  class_type IoT1ClickProjects_ListTagsForResourceRequest, { class => 'Paws::IoT1ClickProjects::ListTagsForResourceRequest' };
  class_type IoT1ClickProjects_ListTagsForResourceResponse, { class => 'Paws::IoT1ClickProjects::ListTagsForResourceResponse' };
  class_type IoT1ClickProjects_PlacementAttributeMap, { class => 'Paws::IoT1ClickProjects::PlacementAttributeMap' };
  class_type IoT1ClickProjects_PlacementDescription, { class => 'Paws::IoT1ClickProjects::PlacementDescription' };
  class_type IoT1ClickProjects_PlacementSummary, { class => 'Paws::IoT1ClickProjects::PlacementSummary' };
  class_type IoT1ClickProjects_PlacementTemplate, { class => 'Paws::IoT1ClickProjects::PlacementTemplate' };
  class_type IoT1ClickProjects_ProjectDescription, { class => 'Paws::IoT1ClickProjects::ProjectDescription' };
  class_type IoT1ClickProjects_ProjectSummary, { class => 'Paws::IoT1ClickProjects::ProjectSummary' };
  class_type IoT1ClickProjects_ResourceConflictException, { class => 'Paws::IoT1ClickProjects::ResourceConflictException' };
  class_type IoT1ClickProjects_ResourceNotFoundException, { class => 'Paws::IoT1ClickProjects::ResourceNotFoundException' };
  class_type IoT1ClickProjects_TagMap, { class => 'Paws::IoT1ClickProjects::TagMap' };
  class_type IoT1ClickProjects_TagResourceRequest, { class => 'Paws::IoT1ClickProjects::TagResourceRequest' };
  class_type IoT1ClickProjects_TagResourceResponse, { class => 'Paws::IoT1ClickProjects::TagResourceResponse' };
  class_type IoT1ClickProjects_TooManyRequestsException, { class => 'Paws::IoT1ClickProjects::TooManyRequestsException' };
  class_type IoT1ClickProjects_UntagResourceRequest, { class => 'Paws::IoT1ClickProjects::UntagResourceRequest' };
  class_type IoT1ClickProjects_UntagResourceResponse, { class => 'Paws::IoT1ClickProjects::UntagResourceResponse' };
  class_type IoT1ClickProjects_UpdatePlacementRequest, { class => 'Paws::IoT1ClickProjects::UpdatePlacementRequest' };
  class_type IoT1ClickProjects_UpdatePlacementResponse, { class => 'Paws::IoT1ClickProjects::UpdatePlacementResponse' };
  class_type IoT1ClickProjects_UpdateProjectRequest, { class => 'Paws::IoT1ClickProjects::UpdateProjectRequest' };
  class_type IoT1ClickProjects_UpdateProjectResponse, { class => 'Paws::IoT1ClickProjects::UpdateProjectResponse' };

1;
