package Paws::ACM::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ACM_AddTagsToCertificateRequest, { class => 'Paws::ACM::AddTagsToCertificateRequest' };
  class_type ACM_CertificateDetail, { class => 'Paws::ACM::CertificateDetail' };
  class_type ACM_CertificateOptions, { class => 'Paws::ACM::CertificateOptions' };
  class_type ACM_CertificateSummary, { class => 'Paws::ACM::CertificateSummary' };
  class_type ACM_DeleteCertificateRequest, { class => 'Paws::ACM::DeleteCertificateRequest' };
  class_type ACM_DescribeCertificateRequest, { class => 'Paws::ACM::DescribeCertificateRequest' };
  class_type ACM_DescribeCertificateResponse, { class => 'Paws::ACM::DescribeCertificateResponse' };
  class_type ACM_DomainValidation, { class => 'Paws::ACM::DomainValidation' };
  class_type ACM_DomainValidationOption, { class => 'Paws::ACM::DomainValidationOption' };
  class_type ACM_ExportCertificateRequest, { class => 'Paws::ACM::ExportCertificateRequest' };
  class_type ACM_ExportCertificateResponse, { class => 'Paws::ACM::ExportCertificateResponse' };
  class_type ACM_ExtendedKeyUsage, { class => 'Paws::ACM::ExtendedKeyUsage' };
  class_type ACM_Filters, { class => 'Paws::ACM::Filters' };
  class_type ACM_GetCertificateRequest, { class => 'Paws::ACM::GetCertificateRequest' };
  class_type ACM_GetCertificateResponse, { class => 'Paws::ACM::GetCertificateResponse' };
  class_type ACM_ImportCertificateRequest, { class => 'Paws::ACM::ImportCertificateRequest' };
  class_type ACM_ImportCertificateResponse, { class => 'Paws::ACM::ImportCertificateResponse' };
  class_type ACM_InvalidArgsException, { class => 'Paws::ACM::InvalidArgsException' };
  class_type ACM_InvalidArnException, { class => 'Paws::ACM::InvalidArnException' };
  class_type ACM_InvalidDomainValidationOptionsException, { class => 'Paws::ACM::InvalidDomainValidationOptionsException' };
  class_type ACM_InvalidStateException, { class => 'Paws::ACM::InvalidStateException' };
  class_type ACM_InvalidTagException, { class => 'Paws::ACM::InvalidTagException' };
  class_type ACM_KeyUsage, { class => 'Paws::ACM::KeyUsage' };
  class_type ACM_LimitExceededException, { class => 'Paws::ACM::LimitExceededException' };
  class_type ACM_ListCertificatesRequest, { class => 'Paws::ACM::ListCertificatesRequest' };
  class_type ACM_ListCertificatesResponse, { class => 'Paws::ACM::ListCertificatesResponse' };
  class_type ACM_ListTagsForCertificateRequest, { class => 'Paws::ACM::ListTagsForCertificateRequest' };
  class_type ACM_ListTagsForCertificateResponse, { class => 'Paws::ACM::ListTagsForCertificateResponse' };
  class_type ACM_RemoveTagsFromCertificateRequest, { class => 'Paws::ACM::RemoveTagsFromCertificateRequest' };
  class_type ACM_RenewalSummary, { class => 'Paws::ACM::RenewalSummary' };
  class_type ACM_RenewCertificateRequest, { class => 'Paws::ACM::RenewCertificateRequest' };
  class_type ACM_RequestCertificateRequest, { class => 'Paws::ACM::RequestCertificateRequest' };
  class_type ACM_RequestCertificateResponse, { class => 'Paws::ACM::RequestCertificateResponse' };
  class_type ACM_RequestInProgressException, { class => 'Paws::ACM::RequestInProgressException' };
  class_type ACM_ResendValidationEmailRequest, { class => 'Paws::ACM::ResendValidationEmailRequest' };
  class_type ACM_ResourceInUseException, { class => 'Paws::ACM::ResourceInUseException' };
  class_type ACM_ResourceNotFoundException, { class => 'Paws::ACM::ResourceNotFoundException' };
  class_type ACM_ResourceRecord, { class => 'Paws::ACM::ResourceRecord' };
  class_type ACM_Tag, { class => 'Paws::ACM::Tag' };
  class_type ACM_TooManyTagsException, { class => 'Paws::ACM::TooManyTagsException' };
  class_type ACM_UpdateCertificateOptionsRequest, { class => 'Paws::ACM::UpdateCertificateOptionsRequest' };

1;
