package Paws::ServiceQuotas::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ServiceQuotas_AccessDeniedException, { class => 'Paws::ServiceQuotas::AccessDeniedException' };
  class_type ServiceQuotas_AssociateServiceQuotaTemplateRequest, { class => 'Paws::ServiceQuotas::AssociateServiceQuotaTemplateRequest' };
  class_type ServiceQuotas_AssociateServiceQuotaTemplateResponse, { class => 'Paws::ServiceQuotas::AssociateServiceQuotaTemplateResponse' };
  class_type ServiceQuotas_AWSServiceAccessNotEnabledException, { class => 'Paws::ServiceQuotas::AWSServiceAccessNotEnabledException' };
  class_type ServiceQuotas_DeleteServiceQuotaIncreaseRequestFromTemplateRequest, { class => 'Paws::ServiceQuotas::DeleteServiceQuotaIncreaseRequestFromTemplateRequest' };
  class_type ServiceQuotas_DeleteServiceQuotaIncreaseRequestFromTemplateResponse, { class => 'Paws::ServiceQuotas::DeleteServiceQuotaIncreaseRequestFromTemplateResponse' };
  class_type ServiceQuotas_DependencyAccessDeniedException, { class => 'Paws::ServiceQuotas::DependencyAccessDeniedException' };
  class_type ServiceQuotas_DisassociateServiceQuotaTemplateRequest, { class => 'Paws::ServiceQuotas::DisassociateServiceQuotaTemplateRequest' };
  class_type ServiceQuotas_DisassociateServiceQuotaTemplateResponse, { class => 'Paws::ServiceQuotas::DisassociateServiceQuotaTemplateResponse' };
  class_type ServiceQuotas_ErrorReason, { class => 'Paws::ServiceQuotas::ErrorReason' };
  class_type ServiceQuotas_GetAssociationForServiceQuotaTemplateRequest, { class => 'Paws::ServiceQuotas::GetAssociationForServiceQuotaTemplateRequest' };
  class_type ServiceQuotas_GetAssociationForServiceQuotaTemplateResponse, { class => 'Paws::ServiceQuotas::GetAssociationForServiceQuotaTemplateResponse' };
  class_type ServiceQuotas_GetAWSDefaultServiceQuotaRequest, { class => 'Paws::ServiceQuotas::GetAWSDefaultServiceQuotaRequest' };
  class_type ServiceQuotas_GetAWSDefaultServiceQuotaResponse, { class => 'Paws::ServiceQuotas::GetAWSDefaultServiceQuotaResponse' };
  class_type ServiceQuotas_GetRequestedServiceQuotaChangeRequest, { class => 'Paws::ServiceQuotas::GetRequestedServiceQuotaChangeRequest' };
  class_type ServiceQuotas_GetRequestedServiceQuotaChangeResponse, { class => 'Paws::ServiceQuotas::GetRequestedServiceQuotaChangeResponse' };
  class_type ServiceQuotas_GetServiceQuotaIncreaseRequestFromTemplateRequest, { class => 'Paws::ServiceQuotas::GetServiceQuotaIncreaseRequestFromTemplateRequest' };
  class_type ServiceQuotas_GetServiceQuotaIncreaseRequestFromTemplateResponse, { class => 'Paws::ServiceQuotas::GetServiceQuotaIncreaseRequestFromTemplateResponse' };
  class_type ServiceQuotas_GetServiceQuotaRequest, { class => 'Paws::ServiceQuotas::GetServiceQuotaRequest' };
  class_type ServiceQuotas_GetServiceQuotaResponse, { class => 'Paws::ServiceQuotas::GetServiceQuotaResponse' };
  class_type ServiceQuotas_IllegalArgumentException, { class => 'Paws::ServiceQuotas::IllegalArgumentException' };
  class_type ServiceQuotas_InvalidPaginationTokenException, { class => 'Paws::ServiceQuotas::InvalidPaginationTokenException' };
  class_type ServiceQuotas_InvalidResourceStateException, { class => 'Paws::ServiceQuotas::InvalidResourceStateException' };
  class_type ServiceQuotas_ListAWSDefaultServiceQuotasRequest, { class => 'Paws::ServiceQuotas::ListAWSDefaultServiceQuotasRequest' };
  class_type ServiceQuotas_ListAWSDefaultServiceQuotasResponse, { class => 'Paws::ServiceQuotas::ListAWSDefaultServiceQuotasResponse' };
  class_type ServiceQuotas_ListRequestedServiceQuotaChangeHistoryByQuotaRequest, { class => 'Paws::ServiceQuotas::ListRequestedServiceQuotaChangeHistoryByQuotaRequest' };
  class_type ServiceQuotas_ListRequestedServiceQuotaChangeHistoryByQuotaResponse, { class => 'Paws::ServiceQuotas::ListRequestedServiceQuotaChangeHistoryByQuotaResponse' };
  class_type ServiceQuotas_ListRequestedServiceQuotaChangeHistoryRequest, { class => 'Paws::ServiceQuotas::ListRequestedServiceQuotaChangeHistoryRequest' };
  class_type ServiceQuotas_ListRequestedServiceQuotaChangeHistoryResponse, { class => 'Paws::ServiceQuotas::ListRequestedServiceQuotaChangeHistoryResponse' };
  class_type ServiceQuotas_ListServiceQuotaIncreaseRequestsInTemplateRequest, { class => 'Paws::ServiceQuotas::ListServiceQuotaIncreaseRequestsInTemplateRequest' };
  class_type ServiceQuotas_ListServiceQuotaIncreaseRequestsInTemplateResponse, { class => 'Paws::ServiceQuotas::ListServiceQuotaIncreaseRequestsInTemplateResponse' };
  class_type ServiceQuotas_ListServiceQuotasRequest, { class => 'Paws::ServiceQuotas::ListServiceQuotasRequest' };
  class_type ServiceQuotas_ListServiceQuotasResponse, { class => 'Paws::ServiceQuotas::ListServiceQuotasResponse' };
  class_type ServiceQuotas_ListServicesRequest, { class => 'Paws::ServiceQuotas::ListServicesRequest' };
  class_type ServiceQuotas_ListServicesResponse, { class => 'Paws::ServiceQuotas::ListServicesResponse' };
  class_type ServiceQuotas_MetricDimensionsMapDefinition, { class => 'Paws::ServiceQuotas::MetricDimensionsMapDefinition' };
  class_type ServiceQuotas_MetricInfo, { class => 'Paws::ServiceQuotas::MetricInfo' };
  class_type ServiceQuotas_NoAvailableOrganizationException, { class => 'Paws::ServiceQuotas::NoAvailableOrganizationException' };
  class_type ServiceQuotas_NoSuchResourceException, { class => 'Paws::ServiceQuotas::NoSuchResourceException' };
  class_type ServiceQuotas_OrganizationNotInAllFeaturesModeException, { class => 'Paws::ServiceQuotas::OrganizationNotInAllFeaturesModeException' };
  class_type ServiceQuotas_PutServiceQuotaIncreaseRequestIntoTemplateRequest, { class => 'Paws::ServiceQuotas::PutServiceQuotaIncreaseRequestIntoTemplateRequest' };
  class_type ServiceQuotas_PutServiceQuotaIncreaseRequestIntoTemplateResponse, { class => 'Paws::ServiceQuotas::PutServiceQuotaIncreaseRequestIntoTemplateResponse' };
  class_type ServiceQuotas_QuotaExceededException, { class => 'Paws::ServiceQuotas::QuotaExceededException' };
  class_type ServiceQuotas_QuotaPeriod, { class => 'Paws::ServiceQuotas::QuotaPeriod' };
  class_type ServiceQuotas_RequestedServiceQuotaChange, { class => 'Paws::ServiceQuotas::RequestedServiceQuotaChange' };
  class_type ServiceQuotas_RequestServiceQuotaIncreaseRequest, { class => 'Paws::ServiceQuotas::RequestServiceQuotaIncreaseRequest' };
  class_type ServiceQuotas_RequestServiceQuotaIncreaseResponse, { class => 'Paws::ServiceQuotas::RequestServiceQuotaIncreaseResponse' };
  class_type ServiceQuotas_ResourceAlreadyExistsException, { class => 'Paws::ServiceQuotas::ResourceAlreadyExistsException' };
  class_type ServiceQuotas_ServiceException, { class => 'Paws::ServiceQuotas::ServiceException' };
  class_type ServiceQuotas_ServiceInfo, { class => 'Paws::ServiceQuotas::ServiceInfo' };
  class_type ServiceQuotas_ServiceQuota, { class => 'Paws::ServiceQuotas::ServiceQuota' };
  class_type ServiceQuotas_ServiceQuotaIncreaseRequestInTemplate, { class => 'Paws::ServiceQuotas::ServiceQuotaIncreaseRequestInTemplate' };
  class_type ServiceQuotas_ServiceQuotaTemplateNotInUseException, { class => 'Paws::ServiceQuotas::ServiceQuotaTemplateNotInUseException' };
  class_type ServiceQuotas_TemplatesNotAvailableInRegionException, { class => 'Paws::ServiceQuotas::TemplatesNotAvailableInRegionException' };
  class_type ServiceQuotas_TooManyRequestsException, { class => 'Paws::ServiceQuotas::TooManyRequestsException' };

1;
