package Paws::ServerlessRepo::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ServerlessRepo_Application, { class => 'Paws::ServerlessRepo::Application' };
  class_type ServerlessRepo_ApplicationDependencyPage, { class => 'Paws::ServerlessRepo::ApplicationDependencyPage' };
  class_type ServerlessRepo_ApplicationDependencySummary, { class => 'Paws::ServerlessRepo::ApplicationDependencySummary' };
  class_type ServerlessRepo_ApplicationPage, { class => 'Paws::ServerlessRepo::ApplicationPage' };
  class_type ServerlessRepo_ApplicationPolicy, { class => 'Paws::ServerlessRepo::ApplicationPolicy' };
  class_type ServerlessRepo_ApplicationPolicyStatement, { class => 'Paws::ServerlessRepo::ApplicationPolicyStatement' };
  class_type ServerlessRepo_ApplicationSummary, { class => 'Paws::ServerlessRepo::ApplicationSummary' };
  class_type ServerlessRepo_ApplicationVersionPage, { class => 'Paws::ServerlessRepo::ApplicationVersionPage' };
  class_type ServerlessRepo_BadRequestException, { class => 'Paws::ServerlessRepo::BadRequestException' };
  class_type ServerlessRepo_ChangeSetDetails, { class => 'Paws::ServerlessRepo::ChangeSetDetails' };
  class_type ServerlessRepo_ConflictException, { class => 'Paws::ServerlessRepo::ConflictException' };
  class_type ServerlessRepo_CreateApplicationInput, { class => 'Paws::ServerlessRepo::CreateApplicationInput' };
  class_type ServerlessRepo_CreateApplicationRequest, { class => 'Paws::ServerlessRepo::CreateApplicationRequest' };
  class_type ServerlessRepo_CreateApplicationResponse, { class => 'Paws::ServerlessRepo::CreateApplicationResponse' };
  class_type ServerlessRepo_CreateApplicationVersionInput, { class => 'Paws::ServerlessRepo::CreateApplicationVersionInput' };
  class_type ServerlessRepo_CreateApplicationVersionRequest, { class => 'Paws::ServerlessRepo::CreateApplicationVersionRequest' };
  class_type ServerlessRepo_CreateApplicationVersionResponse, { class => 'Paws::ServerlessRepo::CreateApplicationVersionResponse' };
  class_type ServerlessRepo_CreateCloudFormationChangeSetInput, { class => 'Paws::ServerlessRepo::CreateCloudFormationChangeSetInput' };
  class_type ServerlessRepo_CreateCloudFormationChangeSetRequest, { class => 'Paws::ServerlessRepo::CreateCloudFormationChangeSetRequest' };
  class_type ServerlessRepo_CreateCloudFormationChangeSetResponse, { class => 'Paws::ServerlessRepo::CreateCloudFormationChangeSetResponse' };
  class_type ServerlessRepo_CreateCloudFormationTemplateRequest, { class => 'Paws::ServerlessRepo::CreateCloudFormationTemplateRequest' };
  class_type ServerlessRepo_CreateCloudFormationTemplateResponse, { class => 'Paws::ServerlessRepo::CreateCloudFormationTemplateResponse' };
  class_type ServerlessRepo_DeleteApplicationRequest, { class => 'Paws::ServerlessRepo::DeleteApplicationRequest' };
  class_type ServerlessRepo_ForbiddenException, { class => 'Paws::ServerlessRepo::ForbiddenException' };
  class_type ServerlessRepo_GetApplicationPolicyRequest, { class => 'Paws::ServerlessRepo::GetApplicationPolicyRequest' };
  class_type ServerlessRepo_GetApplicationPolicyResponse, { class => 'Paws::ServerlessRepo::GetApplicationPolicyResponse' };
  class_type ServerlessRepo_GetApplicationRequest, { class => 'Paws::ServerlessRepo::GetApplicationRequest' };
  class_type ServerlessRepo_GetApplicationResponse, { class => 'Paws::ServerlessRepo::GetApplicationResponse' };
  class_type ServerlessRepo_GetCloudFormationTemplateRequest, { class => 'Paws::ServerlessRepo::GetCloudFormationTemplateRequest' };
  class_type ServerlessRepo_GetCloudFormationTemplateResponse, { class => 'Paws::ServerlessRepo::GetCloudFormationTemplateResponse' };
  class_type ServerlessRepo_InternalServerErrorException, { class => 'Paws::ServerlessRepo::InternalServerErrorException' };
  class_type ServerlessRepo_ListApplicationDependenciesRequest, { class => 'Paws::ServerlessRepo::ListApplicationDependenciesRequest' };
  class_type ServerlessRepo_ListApplicationDependenciesResponse, { class => 'Paws::ServerlessRepo::ListApplicationDependenciesResponse' };
  class_type ServerlessRepo_ListApplicationsRequest, { class => 'Paws::ServerlessRepo::ListApplicationsRequest' };
  class_type ServerlessRepo_ListApplicationsResponse, { class => 'Paws::ServerlessRepo::ListApplicationsResponse' };
  class_type ServerlessRepo_ListApplicationVersionsRequest, { class => 'Paws::ServerlessRepo::ListApplicationVersionsRequest' };
  class_type ServerlessRepo_ListApplicationVersionsResponse, { class => 'Paws::ServerlessRepo::ListApplicationVersionsResponse' };
  class_type ServerlessRepo_NotFoundException, { class => 'Paws::ServerlessRepo::NotFoundException' };
  class_type ServerlessRepo_ParameterDefinition, { class => 'Paws::ServerlessRepo::ParameterDefinition' };
  class_type ServerlessRepo_ParameterValue, { class => 'Paws::ServerlessRepo::ParameterValue' };
  class_type ServerlessRepo_PutApplicationPolicyRequest, { class => 'Paws::ServerlessRepo::PutApplicationPolicyRequest' };
  class_type ServerlessRepo_PutApplicationPolicyResponse, { class => 'Paws::ServerlessRepo::PutApplicationPolicyResponse' };
  class_type ServerlessRepo_RollbackConfiguration, { class => 'Paws::ServerlessRepo::RollbackConfiguration' };
  class_type ServerlessRepo_RollbackTrigger, { class => 'Paws::ServerlessRepo::RollbackTrigger' };
  class_type ServerlessRepo_Tag, { class => 'Paws::ServerlessRepo::Tag' };
  class_type ServerlessRepo_TemplateDetails, { class => 'Paws::ServerlessRepo::TemplateDetails' };
  class_type ServerlessRepo_TooManyRequestsException, { class => 'Paws::ServerlessRepo::TooManyRequestsException' };
  class_type ServerlessRepo_UpdateApplicationInput, { class => 'Paws::ServerlessRepo::UpdateApplicationInput' };
  class_type ServerlessRepo_UpdateApplicationRequest, { class => 'Paws::ServerlessRepo::UpdateApplicationRequest' };
  class_type ServerlessRepo_UpdateApplicationResponse, { class => 'Paws::ServerlessRepo::UpdateApplicationResponse' };
  class_type ServerlessRepo_Version, { class => 'Paws::ServerlessRepo::Version' };
  class_type ServerlessRepo_VersionSummary, { class => 'Paws::ServerlessRepo::VersionSummary' };

1;
