package Paws::SecretsManager::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type SecretsManager_CancelRotateSecretRequest, { class => 'Paws::SecretsManager::CancelRotateSecretRequest' };
  class_type SecretsManager_CancelRotateSecretResponse, { class => 'Paws::SecretsManager::CancelRotateSecretResponse' };
  class_type SecretsManager_CreateSecretRequest, { class => 'Paws::SecretsManager::CreateSecretRequest' };
  class_type SecretsManager_CreateSecretResponse, { class => 'Paws::SecretsManager::CreateSecretResponse' };
  class_type SecretsManager_DecryptionFailure, { class => 'Paws::SecretsManager::DecryptionFailure' };
  class_type SecretsManager_DeleteResourcePolicyRequest, { class => 'Paws::SecretsManager::DeleteResourcePolicyRequest' };
  class_type SecretsManager_DeleteResourcePolicyResponse, { class => 'Paws::SecretsManager::DeleteResourcePolicyResponse' };
  class_type SecretsManager_DeleteSecretRequest, { class => 'Paws::SecretsManager::DeleteSecretRequest' };
  class_type SecretsManager_DeleteSecretResponse, { class => 'Paws::SecretsManager::DeleteSecretResponse' };
  class_type SecretsManager_DescribeSecretRequest, { class => 'Paws::SecretsManager::DescribeSecretRequest' };
  class_type SecretsManager_DescribeSecretResponse, { class => 'Paws::SecretsManager::DescribeSecretResponse' };
  class_type SecretsManager_EncryptionFailure, { class => 'Paws::SecretsManager::EncryptionFailure' };
  class_type SecretsManager_GetRandomPasswordRequest, { class => 'Paws::SecretsManager::GetRandomPasswordRequest' };
  class_type SecretsManager_GetRandomPasswordResponse, { class => 'Paws::SecretsManager::GetRandomPasswordResponse' };
  class_type SecretsManager_GetResourcePolicyRequest, { class => 'Paws::SecretsManager::GetResourcePolicyRequest' };
  class_type SecretsManager_GetResourcePolicyResponse, { class => 'Paws::SecretsManager::GetResourcePolicyResponse' };
  class_type SecretsManager_GetSecretValueRequest, { class => 'Paws::SecretsManager::GetSecretValueRequest' };
  class_type SecretsManager_GetSecretValueResponse, { class => 'Paws::SecretsManager::GetSecretValueResponse' };
  class_type SecretsManager_InternalServiceError, { class => 'Paws::SecretsManager::InternalServiceError' };
  class_type SecretsManager_InvalidNextTokenException, { class => 'Paws::SecretsManager::InvalidNextTokenException' };
  class_type SecretsManager_InvalidParameterException, { class => 'Paws::SecretsManager::InvalidParameterException' };
  class_type SecretsManager_InvalidRequestException, { class => 'Paws::SecretsManager::InvalidRequestException' };
  class_type SecretsManager_LimitExceededException, { class => 'Paws::SecretsManager::LimitExceededException' };
  class_type SecretsManager_ListSecretsRequest, { class => 'Paws::SecretsManager::ListSecretsRequest' };
  class_type SecretsManager_ListSecretsResponse, { class => 'Paws::SecretsManager::ListSecretsResponse' };
  class_type SecretsManager_ListSecretVersionIdsRequest, { class => 'Paws::SecretsManager::ListSecretVersionIdsRequest' };
  class_type SecretsManager_ListSecretVersionIdsResponse, { class => 'Paws::SecretsManager::ListSecretVersionIdsResponse' };
  class_type SecretsManager_MalformedPolicyDocumentException, { class => 'Paws::SecretsManager::MalformedPolicyDocumentException' };
  class_type SecretsManager_PreconditionNotMetException, { class => 'Paws::SecretsManager::PreconditionNotMetException' };
  class_type SecretsManager_PutResourcePolicyRequest, { class => 'Paws::SecretsManager::PutResourcePolicyRequest' };
  class_type SecretsManager_PutResourcePolicyResponse, { class => 'Paws::SecretsManager::PutResourcePolicyResponse' };
  class_type SecretsManager_PutSecretValueRequest, { class => 'Paws::SecretsManager::PutSecretValueRequest' };
  class_type SecretsManager_PutSecretValueResponse, { class => 'Paws::SecretsManager::PutSecretValueResponse' };
  class_type SecretsManager_ResourceExistsException, { class => 'Paws::SecretsManager::ResourceExistsException' };
  class_type SecretsManager_ResourceNotFoundException, { class => 'Paws::SecretsManager::ResourceNotFoundException' };
  class_type SecretsManager_RestoreSecretRequest, { class => 'Paws::SecretsManager::RestoreSecretRequest' };
  class_type SecretsManager_RestoreSecretResponse, { class => 'Paws::SecretsManager::RestoreSecretResponse' };
  class_type SecretsManager_RotateSecretRequest, { class => 'Paws::SecretsManager::RotateSecretRequest' };
  class_type SecretsManager_RotateSecretResponse, { class => 'Paws::SecretsManager::RotateSecretResponse' };
  class_type SecretsManager_RotationRulesType, { class => 'Paws::SecretsManager::RotationRulesType' };
  class_type SecretsManager_SecretListEntry, { class => 'Paws::SecretsManager::SecretListEntry' };
  class_type SecretsManager_SecretVersionsListEntry, { class => 'Paws::SecretsManager::SecretVersionsListEntry' };
  class_type SecretsManager_SecretVersionsToStagesMapType, { class => 'Paws::SecretsManager::SecretVersionsToStagesMapType' };
  class_type SecretsManager_Tag, { class => 'Paws::SecretsManager::Tag' };
  class_type SecretsManager_TagResourceRequest, { class => 'Paws::SecretsManager::TagResourceRequest' };
  class_type SecretsManager_UntagResourceRequest, { class => 'Paws::SecretsManager::UntagResourceRequest' };
  class_type SecretsManager_UpdateSecretRequest, { class => 'Paws::SecretsManager::UpdateSecretRequest' };
  class_type SecretsManager_UpdateSecretResponse, { class => 'Paws::SecretsManager::UpdateSecretResponse' };
  class_type SecretsManager_UpdateSecretVersionStageRequest, { class => 'Paws::SecretsManager::UpdateSecretVersionStageRequest' };
  class_type SecretsManager_UpdateSecretVersionStageResponse, { class => 'Paws::SecretsManager::UpdateSecretVersionStageResponse' };

1;
