package Paws::IoT1ClickDevices::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type IoT1ClickDevices___mapOf__string, { class => 'Paws::IoT1ClickDevices::__mapOf__string' };
  class_type IoT1ClickDevices_Attributes, { class => 'Paws::IoT1ClickDevices::Attributes' };
  class_type IoT1ClickDevices_ClaimDevicesByClaimCodeRequest, { class => 'Paws::IoT1ClickDevices::ClaimDevicesByClaimCodeRequest' };
  class_type IoT1ClickDevices_ClaimDevicesByClaimCodeResponse, { class => 'Paws::IoT1ClickDevices::ClaimDevicesByClaimCodeResponse' };
  class_type IoT1ClickDevices_DescribeDeviceRequest, { class => 'Paws::IoT1ClickDevices::DescribeDeviceRequest' };
  class_type IoT1ClickDevices_DescribeDeviceResponse, { class => 'Paws::IoT1ClickDevices::DescribeDeviceResponse' };
  class_type IoT1ClickDevices_Device, { class => 'Paws::IoT1ClickDevices::Device' };
  class_type IoT1ClickDevices_DeviceAttributes, { class => 'Paws::IoT1ClickDevices::DeviceAttributes' };
  class_type IoT1ClickDevices_DeviceClaimResponse, { class => 'Paws::IoT1ClickDevices::DeviceClaimResponse' };
  class_type IoT1ClickDevices_DeviceDescription, { class => 'Paws::IoT1ClickDevices::DeviceDescription' };
  class_type IoT1ClickDevices_DeviceEvent, { class => 'Paws::IoT1ClickDevices::DeviceEvent' };
  class_type IoT1ClickDevices_DeviceEventsResponse, { class => 'Paws::IoT1ClickDevices::DeviceEventsResponse' };
  class_type IoT1ClickDevices_DeviceMethod, { class => 'Paws::IoT1ClickDevices::DeviceMethod' };
  class_type IoT1ClickDevices_Empty, { class => 'Paws::IoT1ClickDevices::Empty' };
  class_type IoT1ClickDevices_FinalizeDeviceClaimRequest, { class => 'Paws::IoT1ClickDevices::FinalizeDeviceClaimRequest' };
  class_type IoT1ClickDevices_FinalizeDeviceClaimResponse, { class => 'Paws::IoT1ClickDevices::FinalizeDeviceClaimResponse' };
  class_type IoT1ClickDevices_ForbiddenException, { class => 'Paws::IoT1ClickDevices::ForbiddenException' };
  class_type IoT1ClickDevices_GetDeviceMethodsRequest, { class => 'Paws::IoT1ClickDevices::GetDeviceMethodsRequest' };
  class_type IoT1ClickDevices_GetDeviceMethodsResponse, { class => 'Paws::IoT1ClickDevices::GetDeviceMethodsResponse' };
  class_type IoT1ClickDevices_InitiateDeviceClaimRequest, { class => 'Paws::IoT1ClickDevices::InitiateDeviceClaimRequest' };
  class_type IoT1ClickDevices_InitiateDeviceClaimResponse, { class => 'Paws::IoT1ClickDevices::InitiateDeviceClaimResponse' };
  class_type IoT1ClickDevices_InternalFailureException, { class => 'Paws::IoT1ClickDevices::InternalFailureException' };
  class_type IoT1ClickDevices_InvalidRequestException, { class => 'Paws::IoT1ClickDevices::InvalidRequestException' };
  class_type IoT1ClickDevices_InvokeDeviceMethodRequest, { class => 'Paws::IoT1ClickDevices::InvokeDeviceMethodRequest' };
  class_type IoT1ClickDevices_InvokeDeviceMethodResponse, { class => 'Paws::IoT1ClickDevices::InvokeDeviceMethodResponse' };
  class_type IoT1ClickDevices_ListDeviceEventsRequest, { class => 'Paws::IoT1ClickDevices::ListDeviceEventsRequest' };
  class_type IoT1ClickDevices_ListDeviceEventsResponse, { class => 'Paws::IoT1ClickDevices::ListDeviceEventsResponse' };
  class_type IoT1ClickDevices_ListDevicesRequest, { class => 'Paws::IoT1ClickDevices::ListDevicesRequest' };
  class_type IoT1ClickDevices_ListDevicesResponse, { class => 'Paws::IoT1ClickDevices::ListDevicesResponse' };
  class_type IoT1ClickDevices_ListTagsForResourceRequest, { class => 'Paws::IoT1ClickDevices::ListTagsForResourceRequest' };
  class_type IoT1ClickDevices_ListTagsForResourceResponse, { class => 'Paws::IoT1ClickDevices::ListTagsForResourceResponse' };
  class_type IoT1ClickDevices_PreconditionFailedException, { class => 'Paws::IoT1ClickDevices::PreconditionFailedException' };
  class_type IoT1ClickDevices_RangeNotSatisfiableException, { class => 'Paws::IoT1ClickDevices::RangeNotSatisfiableException' };
  class_type IoT1ClickDevices_ResourceConflictException, { class => 'Paws::IoT1ClickDevices::ResourceConflictException' };
  class_type IoT1ClickDevices_ResourceNotFoundException, { class => 'Paws::IoT1ClickDevices::ResourceNotFoundException' };
  class_type IoT1ClickDevices_TagResourceRequest, { class => 'Paws::IoT1ClickDevices::TagResourceRequest' };
  class_type IoT1ClickDevices_UnclaimDeviceRequest, { class => 'Paws::IoT1ClickDevices::UnclaimDeviceRequest' };
  class_type IoT1ClickDevices_UnclaimDeviceResponse, { class => 'Paws::IoT1ClickDevices::UnclaimDeviceResponse' };
  class_type IoT1ClickDevices_UntagResourceRequest, { class => 'Paws::IoT1ClickDevices::UntagResourceRequest' };
  class_type IoT1ClickDevices_UpdateDeviceStateRequest, { class => 'Paws::IoT1ClickDevices::UpdateDeviceStateRequest' };
  class_type IoT1ClickDevices_UpdateDeviceStateResponse, { class => 'Paws::IoT1ClickDevices::UpdateDeviceStateResponse' };

1;
