package Paws::MediaConnect::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type MediaConnect___mapOf__string, { class => 'Paws::MediaConnect::__mapOf__string' };
  class_type MediaConnect_AddFlowOutputs420Exception, { class => 'Paws::MediaConnect::AddFlowOutputs420Exception' };
  class_type MediaConnect_AddFlowOutputsRequest, { class => 'Paws::MediaConnect::AddFlowOutputsRequest' };
  class_type MediaConnect_AddFlowOutputsResponse, { class => 'Paws::MediaConnect::AddFlowOutputsResponse' };
  class_type MediaConnect_AddOutputRequest, { class => 'Paws::MediaConnect::AddOutputRequest' };
  class_type MediaConnect_BadRequestException, { class => 'Paws::MediaConnect::BadRequestException' };
  class_type MediaConnect_CreateFlow420Exception, { class => 'Paws::MediaConnect::CreateFlow420Exception' };
  class_type MediaConnect_CreateFlowRequest, { class => 'Paws::MediaConnect::CreateFlowRequest' };
  class_type MediaConnect_CreateFlowResponse, { class => 'Paws::MediaConnect::CreateFlowResponse' };
  class_type MediaConnect_DeleteFlowRequest, { class => 'Paws::MediaConnect::DeleteFlowRequest' };
  class_type MediaConnect_DeleteFlowResponse, { class => 'Paws::MediaConnect::DeleteFlowResponse' };
  class_type MediaConnect_DescribeFlowRequest, { class => 'Paws::MediaConnect::DescribeFlowRequest' };
  class_type MediaConnect_DescribeFlowResponse, { class => 'Paws::MediaConnect::DescribeFlowResponse' };
  class_type MediaConnect_Encryption, { class => 'Paws::MediaConnect::Encryption' };
  class_type MediaConnect_Entitlement, { class => 'Paws::MediaConnect::Entitlement' };
  class_type MediaConnect_Flow, { class => 'Paws::MediaConnect::Flow' };
  class_type MediaConnect_ForbiddenException, { class => 'Paws::MediaConnect::ForbiddenException' };
  class_type MediaConnect_GrantEntitlementRequest, { class => 'Paws::MediaConnect::GrantEntitlementRequest' };
  class_type MediaConnect_GrantFlowEntitlements420Exception, { class => 'Paws::MediaConnect::GrantFlowEntitlements420Exception' };
  class_type MediaConnect_GrantFlowEntitlementsRequest, { class => 'Paws::MediaConnect::GrantFlowEntitlementsRequest' };
  class_type MediaConnect_GrantFlowEntitlementsResponse, { class => 'Paws::MediaConnect::GrantFlowEntitlementsResponse' };
  class_type MediaConnect_InternalServerErrorException, { class => 'Paws::MediaConnect::InternalServerErrorException' };
  class_type MediaConnect_ListedEntitlement, { class => 'Paws::MediaConnect::ListedEntitlement' };
  class_type MediaConnect_ListedFlow, { class => 'Paws::MediaConnect::ListedFlow' };
  class_type MediaConnect_ListEntitlementsRequest, { class => 'Paws::MediaConnect::ListEntitlementsRequest' };
  class_type MediaConnect_ListEntitlementsResponse, { class => 'Paws::MediaConnect::ListEntitlementsResponse' };
  class_type MediaConnect_ListFlowsRequest, { class => 'Paws::MediaConnect::ListFlowsRequest' };
  class_type MediaConnect_ListFlowsResponse, { class => 'Paws::MediaConnect::ListFlowsResponse' };
  class_type MediaConnect_ListTagsForResourceRequest, { class => 'Paws::MediaConnect::ListTagsForResourceRequest' };
  class_type MediaConnect_ListTagsForResourceResponse, { class => 'Paws::MediaConnect::ListTagsForResourceResponse' };
  class_type MediaConnect_Messages, { class => 'Paws::MediaConnect::Messages' };
  class_type MediaConnect_NotFoundException, { class => 'Paws::MediaConnect::NotFoundException' };
  class_type MediaConnect_Output, { class => 'Paws::MediaConnect::Output' };
  class_type MediaConnect_RemoveFlowOutputRequest, { class => 'Paws::MediaConnect::RemoveFlowOutputRequest' };
  class_type MediaConnect_RemoveFlowOutputResponse, { class => 'Paws::MediaConnect::RemoveFlowOutputResponse' };
  class_type MediaConnect_ResponseError, { class => 'Paws::MediaConnect::ResponseError' };
  class_type MediaConnect_RevokeFlowEntitlementRequest, { class => 'Paws::MediaConnect::RevokeFlowEntitlementRequest' };
  class_type MediaConnect_RevokeFlowEntitlementResponse, { class => 'Paws::MediaConnect::RevokeFlowEntitlementResponse' };
  class_type MediaConnect_ServiceUnavailableException, { class => 'Paws::MediaConnect::ServiceUnavailableException' };
  class_type MediaConnect_SetSourceRequest, { class => 'Paws::MediaConnect::SetSourceRequest' };
  class_type MediaConnect_Source, { class => 'Paws::MediaConnect::Source' };
  class_type MediaConnect_StartFlowRequest, { class => 'Paws::MediaConnect::StartFlowRequest' };
  class_type MediaConnect_StartFlowResponse, { class => 'Paws::MediaConnect::StartFlowResponse' };
  class_type MediaConnect_StopFlowRequest, { class => 'Paws::MediaConnect::StopFlowRequest' };
  class_type MediaConnect_StopFlowResponse, { class => 'Paws::MediaConnect::StopFlowResponse' };
  class_type MediaConnect_TagResourceRequest, { class => 'Paws::MediaConnect::TagResourceRequest' };
  class_type MediaConnect_TooManyRequestsException, { class => 'Paws::MediaConnect::TooManyRequestsException' };
  class_type MediaConnect_Transport, { class => 'Paws::MediaConnect::Transport' };
  class_type MediaConnect_UntagResourceRequest, { class => 'Paws::MediaConnect::UntagResourceRequest' };
  class_type MediaConnect_UpdateEncryption, { class => 'Paws::MediaConnect::UpdateEncryption' };
  class_type MediaConnect_UpdateFlowEntitlementRequest, { class => 'Paws::MediaConnect::UpdateFlowEntitlementRequest' };
  class_type MediaConnect_UpdateFlowEntitlementResponse, { class => 'Paws::MediaConnect::UpdateFlowEntitlementResponse' };
  class_type MediaConnect_UpdateFlowOutputRequest, { class => 'Paws::MediaConnect::UpdateFlowOutputRequest' };
  class_type MediaConnect_UpdateFlowOutputResponse, { class => 'Paws::MediaConnect::UpdateFlowOutputResponse' };
  class_type MediaConnect_UpdateFlowSourceRequest, { class => 'Paws::MediaConnect::UpdateFlowSourceRequest' };
  class_type MediaConnect_UpdateFlowSourceResponse, { class => 'Paws::MediaConnect::UpdateFlowSourceResponse' };

1;
