# Generated by default/object.tt
package Paws::LexModelsV2::CodeHookSpecification;
  use Moose;
  has LambdaCodeHook => (is => 'ro', isa => 'Paws::LexModelsV2::LambdaCodeHook', request_name => 'lambdaCodeHook', traits => ['NameInRequest'], required => 1);

1;

### main pod documentation begin ###

=head1 NAME

Paws::LexModelsV2::CodeHookSpecification

=head1 USAGE

This class represents one of two things:

=head3 Arguments in a call to a service

Use the attributes of this class as arguments to methods. You shouldn't make instances of this class. 
Each attribute should be used as a named argument in the calls that expect this type of object.

As an example, if Att1 is expected to be a Paws::LexModelsV2::CodeHookSpecification object:

  $service_obj->Method(Att1 => { LambdaCodeHook => $value, ..., LambdaCodeHook => $value  });

=head3 Results returned from an API call

Use accessors for each attribute. If Att1 is expected to be an Paws::LexModelsV2::CodeHookSpecification object:

  $result = $service_obj->Method(...);
  $result->Att1->LambdaCodeHook

=head1 DESCRIPTION

Contains information about code hooks that Amazon Lex calls during a
conversation.

=head1 ATTRIBUTES


=head2 B<REQUIRED> LambdaCodeHook => L<Paws::LexModelsV2::LambdaCodeHook>





=head1 SEE ALSO

This class forms part of L<Paws>, describing an object used in L<Paws::LexModelsV2>

=head1 BUGS and CONTRIBUTIONS

The source code is located here: L<https://github.com/pplu/aws-sdk-perl>

Please report bugs to: L<https://github.com/pplu/aws-sdk-perl/issues>

=cut

