package Paws::CognitoSync::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CognitoSync_AlreadyStreamedException, { class => 'Paws::CognitoSync::AlreadyStreamedException' };
  class_type CognitoSync_BulkPublishRequest, { class => 'Paws::CognitoSync::BulkPublishRequest' };
  class_type CognitoSync_BulkPublishResponse, { class => 'Paws::CognitoSync::BulkPublishResponse' };
  class_type CognitoSync_CognitoStreams, { class => 'Paws::CognitoSync::CognitoStreams' };
  class_type CognitoSync_ConcurrentModificationException, { class => 'Paws::CognitoSync::ConcurrentModificationException' };
  class_type CognitoSync_Dataset, { class => 'Paws::CognitoSync::Dataset' };
  class_type CognitoSync_DeleteDatasetRequest, { class => 'Paws::CognitoSync::DeleteDatasetRequest' };
  class_type CognitoSync_DeleteDatasetResponse, { class => 'Paws::CognitoSync::DeleteDatasetResponse' };
  class_type CognitoSync_DescribeDatasetRequest, { class => 'Paws::CognitoSync::DescribeDatasetRequest' };
  class_type CognitoSync_DescribeDatasetResponse, { class => 'Paws::CognitoSync::DescribeDatasetResponse' };
  class_type CognitoSync_DescribeIdentityPoolUsageRequest, { class => 'Paws::CognitoSync::DescribeIdentityPoolUsageRequest' };
  class_type CognitoSync_DescribeIdentityPoolUsageResponse, { class => 'Paws::CognitoSync::DescribeIdentityPoolUsageResponse' };
  class_type CognitoSync_DescribeIdentityUsageRequest, { class => 'Paws::CognitoSync::DescribeIdentityUsageRequest' };
  class_type CognitoSync_DescribeIdentityUsageResponse, { class => 'Paws::CognitoSync::DescribeIdentityUsageResponse' };
  class_type CognitoSync_DuplicateRequestException, { class => 'Paws::CognitoSync::DuplicateRequestException' };
  class_type CognitoSync_Events, { class => 'Paws::CognitoSync::Events' };
  class_type CognitoSync_GetBulkPublishDetailsRequest, { class => 'Paws::CognitoSync::GetBulkPublishDetailsRequest' };
  class_type CognitoSync_GetBulkPublishDetailsResponse, { class => 'Paws::CognitoSync::GetBulkPublishDetailsResponse' };
  class_type CognitoSync_GetCognitoEventsRequest, { class => 'Paws::CognitoSync::GetCognitoEventsRequest' };
  class_type CognitoSync_GetCognitoEventsResponse, { class => 'Paws::CognitoSync::GetCognitoEventsResponse' };
  class_type CognitoSync_GetIdentityPoolConfigurationRequest, { class => 'Paws::CognitoSync::GetIdentityPoolConfigurationRequest' };
  class_type CognitoSync_GetIdentityPoolConfigurationResponse, { class => 'Paws::CognitoSync::GetIdentityPoolConfigurationResponse' };
  class_type CognitoSync_IdentityPoolUsage, { class => 'Paws::CognitoSync::IdentityPoolUsage' };
  class_type CognitoSync_IdentityUsage, { class => 'Paws::CognitoSync::IdentityUsage' };
  class_type CognitoSync_InternalErrorException, { class => 'Paws::CognitoSync::InternalErrorException' };
  class_type CognitoSync_InvalidConfigurationException, { class => 'Paws::CognitoSync::InvalidConfigurationException' };
  class_type CognitoSync_InvalidLambdaFunctionOutputException, { class => 'Paws::CognitoSync::InvalidLambdaFunctionOutputException' };
  class_type CognitoSync_InvalidParameterException, { class => 'Paws::CognitoSync::InvalidParameterException' };
  class_type CognitoSync_LambdaThrottledException, { class => 'Paws::CognitoSync::LambdaThrottledException' };
  class_type CognitoSync_LimitExceededException, { class => 'Paws::CognitoSync::LimitExceededException' };
  class_type CognitoSync_ListDatasetsRequest, { class => 'Paws::CognitoSync::ListDatasetsRequest' };
  class_type CognitoSync_ListDatasetsResponse, { class => 'Paws::CognitoSync::ListDatasetsResponse' };
  class_type CognitoSync_ListIdentityPoolUsageRequest, { class => 'Paws::CognitoSync::ListIdentityPoolUsageRequest' };
  class_type CognitoSync_ListIdentityPoolUsageResponse, { class => 'Paws::CognitoSync::ListIdentityPoolUsageResponse' };
  class_type CognitoSync_ListRecordsRequest, { class => 'Paws::CognitoSync::ListRecordsRequest' };
  class_type CognitoSync_ListRecordsResponse, { class => 'Paws::CognitoSync::ListRecordsResponse' };
  class_type CognitoSync_NotAuthorizedException, { class => 'Paws::CognitoSync::NotAuthorizedException' };
  class_type CognitoSync_PushSync, { class => 'Paws::CognitoSync::PushSync' };
  class_type CognitoSync_Record, { class => 'Paws::CognitoSync::Record' };
  class_type CognitoSync_RecordPatch, { class => 'Paws::CognitoSync::RecordPatch' };
  class_type CognitoSync_RegisterDeviceRequest, { class => 'Paws::CognitoSync::RegisterDeviceRequest' };
  class_type CognitoSync_RegisterDeviceResponse, { class => 'Paws::CognitoSync::RegisterDeviceResponse' };
  class_type CognitoSync_ResourceConflictException, { class => 'Paws::CognitoSync::ResourceConflictException' };
  class_type CognitoSync_ResourceNotFoundException, { class => 'Paws::CognitoSync::ResourceNotFoundException' };
  class_type CognitoSync_SetCognitoEventsRequest, { class => 'Paws::CognitoSync::SetCognitoEventsRequest' };
  class_type CognitoSync_SetIdentityPoolConfigurationRequest, { class => 'Paws::CognitoSync::SetIdentityPoolConfigurationRequest' };
  class_type CognitoSync_SetIdentityPoolConfigurationResponse, { class => 'Paws::CognitoSync::SetIdentityPoolConfigurationResponse' };
  class_type CognitoSync_SubscribeToDatasetRequest, { class => 'Paws::CognitoSync::SubscribeToDatasetRequest' };
  class_type CognitoSync_SubscribeToDatasetResponse, { class => 'Paws::CognitoSync::SubscribeToDatasetResponse' };
  class_type CognitoSync_TooManyRequestsException, { class => 'Paws::CognitoSync::TooManyRequestsException' };
  class_type CognitoSync_UnsubscribeFromDatasetRequest, { class => 'Paws::CognitoSync::UnsubscribeFromDatasetRequest' };
  class_type CognitoSync_UnsubscribeFromDatasetResponse, { class => 'Paws::CognitoSync::UnsubscribeFromDatasetResponse' };
  class_type CognitoSync_UpdateRecordsRequest, { class => 'Paws::CognitoSync::UpdateRecordsRequest' };
  class_type CognitoSync_UpdateRecordsResponse, { class => 'Paws::CognitoSync::UpdateRecordsResponse' };

1;
