package Paws::DataPipeline::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type DataPipeline_ActivatePipelineInput, { class => 'Paws::DataPipeline::ActivatePipelineInput' };
  class_type DataPipeline_ActivatePipelineOutput, { class => 'Paws::DataPipeline::ActivatePipelineOutput' };
  class_type DataPipeline_AddTagsInput, { class => 'Paws::DataPipeline::AddTagsInput' };
  class_type DataPipeline_AddTagsOutput, { class => 'Paws::DataPipeline::AddTagsOutput' };
  class_type DataPipeline_CreatePipelineInput, { class => 'Paws::DataPipeline::CreatePipelineInput' };
  class_type DataPipeline_CreatePipelineOutput, { class => 'Paws::DataPipeline::CreatePipelineOutput' };
  class_type DataPipeline_DeactivatePipelineInput, { class => 'Paws::DataPipeline::DeactivatePipelineInput' };
  class_type DataPipeline_DeactivatePipelineOutput, { class => 'Paws::DataPipeline::DeactivatePipelineOutput' };
  class_type DataPipeline_DeletePipelineInput, { class => 'Paws::DataPipeline::DeletePipelineInput' };
  class_type DataPipeline_DescribeObjectsInput, { class => 'Paws::DataPipeline::DescribeObjectsInput' };
  class_type DataPipeline_DescribeObjectsOutput, { class => 'Paws::DataPipeline::DescribeObjectsOutput' };
  class_type DataPipeline_DescribePipelinesInput, { class => 'Paws::DataPipeline::DescribePipelinesInput' };
  class_type DataPipeline_DescribePipelinesOutput, { class => 'Paws::DataPipeline::DescribePipelinesOutput' };
  class_type DataPipeline_EvaluateExpressionInput, { class => 'Paws::DataPipeline::EvaluateExpressionInput' };
  class_type DataPipeline_EvaluateExpressionOutput, { class => 'Paws::DataPipeline::EvaluateExpressionOutput' };
  class_type DataPipeline_Field, { class => 'Paws::DataPipeline::Field' };
  class_type DataPipeline_GetPipelineDefinitionInput, { class => 'Paws::DataPipeline::GetPipelineDefinitionInput' };
  class_type DataPipeline_GetPipelineDefinitionOutput, { class => 'Paws::DataPipeline::GetPipelineDefinitionOutput' };
  class_type DataPipeline_InstanceIdentity, { class => 'Paws::DataPipeline::InstanceIdentity' };
  class_type DataPipeline_InternalServiceError, { class => 'Paws::DataPipeline::InternalServiceError' };
  class_type DataPipeline_InvalidRequestException, { class => 'Paws::DataPipeline::InvalidRequestException' };
  class_type DataPipeline_ListPipelinesInput, { class => 'Paws::DataPipeline::ListPipelinesInput' };
  class_type DataPipeline_ListPipelinesOutput, { class => 'Paws::DataPipeline::ListPipelinesOutput' };
  class_type DataPipeline_Operator, { class => 'Paws::DataPipeline::Operator' };
  class_type DataPipeline_ParameterAttribute, { class => 'Paws::DataPipeline::ParameterAttribute' };
  class_type DataPipeline_ParameterObject, { class => 'Paws::DataPipeline::ParameterObject' };
  class_type DataPipeline_ParameterValue, { class => 'Paws::DataPipeline::ParameterValue' };
  class_type DataPipeline_PipelineDeletedException, { class => 'Paws::DataPipeline::PipelineDeletedException' };
  class_type DataPipeline_PipelineDescription, { class => 'Paws::DataPipeline::PipelineDescription' };
  class_type DataPipeline_PipelineIdName, { class => 'Paws::DataPipeline::PipelineIdName' };
  class_type DataPipeline_PipelineNotFoundException, { class => 'Paws::DataPipeline::PipelineNotFoundException' };
  class_type DataPipeline_PipelineObject, { class => 'Paws::DataPipeline::PipelineObject' };
  class_type DataPipeline_PipelineObjectMap, { class => 'Paws::DataPipeline::PipelineObjectMap' };
  class_type DataPipeline_PollForTaskInput, { class => 'Paws::DataPipeline::PollForTaskInput' };
  class_type DataPipeline_PollForTaskOutput, { class => 'Paws::DataPipeline::PollForTaskOutput' };
  class_type DataPipeline_PutPipelineDefinitionInput, { class => 'Paws::DataPipeline::PutPipelineDefinitionInput' };
  class_type DataPipeline_PutPipelineDefinitionOutput, { class => 'Paws::DataPipeline::PutPipelineDefinitionOutput' };
  class_type DataPipeline_Query, { class => 'Paws::DataPipeline::Query' };
  class_type DataPipeline_QueryObjectsInput, { class => 'Paws::DataPipeline::QueryObjectsInput' };
  class_type DataPipeline_QueryObjectsOutput, { class => 'Paws::DataPipeline::QueryObjectsOutput' };
  class_type DataPipeline_RemoveTagsInput, { class => 'Paws::DataPipeline::RemoveTagsInput' };
  class_type DataPipeline_RemoveTagsOutput, { class => 'Paws::DataPipeline::RemoveTagsOutput' };
  class_type DataPipeline_ReportTaskProgressInput, { class => 'Paws::DataPipeline::ReportTaskProgressInput' };
  class_type DataPipeline_ReportTaskProgressOutput, { class => 'Paws::DataPipeline::ReportTaskProgressOutput' };
  class_type DataPipeline_ReportTaskRunnerHeartbeatInput, { class => 'Paws::DataPipeline::ReportTaskRunnerHeartbeatInput' };
  class_type DataPipeline_ReportTaskRunnerHeartbeatOutput, { class => 'Paws::DataPipeline::ReportTaskRunnerHeartbeatOutput' };
  class_type DataPipeline_Selector, { class => 'Paws::DataPipeline::Selector' };
  class_type DataPipeline_SetStatusInput, { class => 'Paws::DataPipeline::SetStatusInput' };
  class_type DataPipeline_SetTaskStatusInput, { class => 'Paws::DataPipeline::SetTaskStatusInput' };
  class_type DataPipeline_SetTaskStatusOutput, { class => 'Paws::DataPipeline::SetTaskStatusOutput' };
  class_type DataPipeline_Tag, { class => 'Paws::DataPipeline::Tag' };
  class_type DataPipeline_TaskNotFoundException, { class => 'Paws::DataPipeline::TaskNotFoundException' };
  class_type DataPipeline_TaskObject, { class => 'Paws::DataPipeline::TaskObject' };
  class_type DataPipeline_ValidatePipelineDefinitionInput, { class => 'Paws::DataPipeline::ValidatePipelineDefinitionInput' };
  class_type DataPipeline_ValidatePipelineDefinitionOutput, { class => 'Paws::DataPipeline::ValidatePipelineDefinitionOutput' };
  class_type DataPipeline_ValidationError, { class => 'Paws::DataPipeline::ValidationError' };
  class_type DataPipeline_ValidationWarning, { class => 'Paws::DataPipeline::ValidationWarning' };

1;
