package Paws::ApplicationInsights::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ApplicationInsights_ApplicationComponent, { class => 'Paws::ApplicationInsights::ApplicationComponent' };
  class_type ApplicationInsights_ApplicationInfo, { class => 'Paws::ApplicationInsights::ApplicationInfo' };
  class_type ApplicationInsights_BadRequestException, { class => 'Paws::ApplicationInsights::BadRequestException' };
  class_type ApplicationInsights_CreateApplicationRequest, { class => 'Paws::ApplicationInsights::CreateApplicationRequest' };
  class_type ApplicationInsights_CreateApplicationResponse, { class => 'Paws::ApplicationInsights::CreateApplicationResponse' };
  class_type ApplicationInsights_CreateComponentRequest, { class => 'Paws::ApplicationInsights::CreateComponentRequest' };
  class_type ApplicationInsights_CreateComponentResponse, { class => 'Paws::ApplicationInsights::CreateComponentResponse' };
  class_type ApplicationInsights_DeleteApplicationRequest, { class => 'Paws::ApplicationInsights::DeleteApplicationRequest' };
  class_type ApplicationInsights_DeleteApplicationResponse, { class => 'Paws::ApplicationInsights::DeleteApplicationResponse' };
  class_type ApplicationInsights_DeleteComponentRequest, { class => 'Paws::ApplicationInsights::DeleteComponentRequest' };
  class_type ApplicationInsights_DeleteComponentResponse, { class => 'Paws::ApplicationInsights::DeleteComponentResponse' };
  class_type ApplicationInsights_DescribeApplicationRequest, { class => 'Paws::ApplicationInsights::DescribeApplicationRequest' };
  class_type ApplicationInsights_DescribeApplicationResponse, { class => 'Paws::ApplicationInsights::DescribeApplicationResponse' };
  class_type ApplicationInsights_DescribeComponentConfigurationRecommendationRequest, { class => 'Paws::ApplicationInsights::DescribeComponentConfigurationRecommendationRequest' };
  class_type ApplicationInsights_DescribeComponentConfigurationRecommendationResponse, { class => 'Paws::ApplicationInsights::DescribeComponentConfigurationRecommendationResponse' };
  class_type ApplicationInsights_DescribeComponentConfigurationRequest, { class => 'Paws::ApplicationInsights::DescribeComponentConfigurationRequest' };
  class_type ApplicationInsights_DescribeComponentConfigurationResponse, { class => 'Paws::ApplicationInsights::DescribeComponentConfigurationResponse' };
  class_type ApplicationInsights_DescribeComponentRequest, { class => 'Paws::ApplicationInsights::DescribeComponentRequest' };
  class_type ApplicationInsights_DescribeComponentResponse, { class => 'Paws::ApplicationInsights::DescribeComponentResponse' };
  class_type ApplicationInsights_DescribeObservationRequest, { class => 'Paws::ApplicationInsights::DescribeObservationRequest' };
  class_type ApplicationInsights_DescribeObservationResponse, { class => 'Paws::ApplicationInsights::DescribeObservationResponse' };
  class_type ApplicationInsights_DescribeProblemObservationsRequest, { class => 'Paws::ApplicationInsights::DescribeProblemObservationsRequest' };
  class_type ApplicationInsights_DescribeProblemObservationsResponse, { class => 'Paws::ApplicationInsights::DescribeProblemObservationsResponse' };
  class_type ApplicationInsights_DescribeProblemRequest, { class => 'Paws::ApplicationInsights::DescribeProblemRequest' };
  class_type ApplicationInsights_DescribeProblemResponse, { class => 'Paws::ApplicationInsights::DescribeProblemResponse' };
  class_type ApplicationInsights_Feedback, { class => 'Paws::ApplicationInsights::Feedback' };
  class_type ApplicationInsights_InternalServerException, { class => 'Paws::ApplicationInsights::InternalServerException' };
  class_type ApplicationInsights_ListApplicationsRequest, { class => 'Paws::ApplicationInsights::ListApplicationsRequest' };
  class_type ApplicationInsights_ListApplicationsResponse, { class => 'Paws::ApplicationInsights::ListApplicationsResponse' };
  class_type ApplicationInsights_ListComponentsRequest, { class => 'Paws::ApplicationInsights::ListComponentsRequest' };
  class_type ApplicationInsights_ListComponentsResponse, { class => 'Paws::ApplicationInsights::ListComponentsResponse' };
  class_type ApplicationInsights_ListProblemsRequest, { class => 'Paws::ApplicationInsights::ListProblemsRequest' };
  class_type ApplicationInsights_ListProblemsResponse, { class => 'Paws::ApplicationInsights::ListProblemsResponse' };
  class_type ApplicationInsights_Observation, { class => 'Paws::ApplicationInsights::Observation' };
  class_type ApplicationInsights_Problem, { class => 'Paws::ApplicationInsights::Problem' };
  class_type ApplicationInsights_RelatedObservations, { class => 'Paws::ApplicationInsights::RelatedObservations' };
  class_type ApplicationInsights_ResourceInUseException, { class => 'Paws::ApplicationInsights::ResourceInUseException' };
  class_type ApplicationInsights_ResourceNotFoundException, { class => 'Paws::ApplicationInsights::ResourceNotFoundException' };
  class_type ApplicationInsights_UpdateComponentConfigurationRequest, { class => 'Paws::ApplicationInsights::UpdateComponentConfigurationRequest' };
  class_type ApplicationInsights_UpdateComponentConfigurationResponse, { class => 'Paws::ApplicationInsights::UpdateComponentConfigurationResponse' };
  class_type ApplicationInsights_UpdateComponentRequest, { class => 'Paws::ApplicationInsights::UpdateComponentRequest' };
  class_type ApplicationInsights_UpdateComponentResponse, { class => 'Paws::ApplicationInsights::UpdateComponentResponse' };
  class_type ApplicationInsights_ValidationException, { class => 'Paws::ApplicationInsights::ValidationException' };

1;
