#!/usr/bin/env perl

my @args = @ARGV;

$ENV{PAWS_MOCK_MODE} = 'RECORD';
$ENV{PAWS_MOCK_DIR} = 'tests/' . time . '/';

my @cmd = ('perl', '-I', 't/lib', '-I', 'lib', 'bin/paws', $args[0], '--caller', 'TestMakerCaller', @args[1..$#args]);

system @cmd;
