package Paws::MediaStore::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type MediaStore_Container, { class => 'Paws::MediaStore::Container' };
  class_type MediaStore_ContainerInUseException, { class => 'Paws::MediaStore::ContainerInUseException' };
  class_type MediaStore_ContainerNotFoundException, { class => 'Paws::MediaStore::ContainerNotFoundException' };
  class_type MediaStore_CorsPolicyNotFoundException, { class => 'Paws::MediaStore::CorsPolicyNotFoundException' };
  class_type MediaStore_CorsRule, { class => 'Paws::MediaStore::CorsRule' };
  class_type MediaStore_CreateContainerInput, { class => 'Paws::MediaStore::CreateContainerInput' };
  class_type MediaStore_CreateContainerOutput, { class => 'Paws::MediaStore::CreateContainerOutput' };
  class_type MediaStore_DeleteContainerInput, { class => 'Paws::MediaStore::DeleteContainerInput' };
  class_type MediaStore_DeleteContainerOutput, { class => 'Paws::MediaStore::DeleteContainerOutput' };
  class_type MediaStore_DeleteContainerPolicyInput, { class => 'Paws::MediaStore::DeleteContainerPolicyInput' };
  class_type MediaStore_DeleteContainerPolicyOutput, { class => 'Paws::MediaStore::DeleteContainerPolicyOutput' };
  class_type MediaStore_DeleteCorsPolicyInput, { class => 'Paws::MediaStore::DeleteCorsPolicyInput' };
  class_type MediaStore_DeleteCorsPolicyOutput, { class => 'Paws::MediaStore::DeleteCorsPolicyOutput' };
  class_type MediaStore_DeleteLifecyclePolicyInput, { class => 'Paws::MediaStore::DeleteLifecyclePolicyInput' };
  class_type MediaStore_DeleteLifecyclePolicyOutput, { class => 'Paws::MediaStore::DeleteLifecyclePolicyOutput' };
  class_type MediaStore_DescribeContainerInput, { class => 'Paws::MediaStore::DescribeContainerInput' };
  class_type MediaStore_DescribeContainerOutput, { class => 'Paws::MediaStore::DescribeContainerOutput' };
  class_type MediaStore_GetContainerPolicyInput, { class => 'Paws::MediaStore::GetContainerPolicyInput' };
  class_type MediaStore_GetContainerPolicyOutput, { class => 'Paws::MediaStore::GetContainerPolicyOutput' };
  class_type MediaStore_GetCorsPolicyInput, { class => 'Paws::MediaStore::GetCorsPolicyInput' };
  class_type MediaStore_GetCorsPolicyOutput, { class => 'Paws::MediaStore::GetCorsPolicyOutput' };
  class_type MediaStore_GetLifecyclePolicyInput, { class => 'Paws::MediaStore::GetLifecyclePolicyInput' };
  class_type MediaStore_GetLifecyclePolicyOutput, { class => 'Paws::MediaStore::GetLifecyclePolicyOutput' };
  class_type MediaStore_InternalServerError, { class => 'Paws::MediaStore::InternalServerError' };
  class_type MediaStore_LimitExceededException, { class => 'Paws::MediaStore::LimitExceededException' };
  class_type MediaStore_ListContainersInput, { class => 'Paws::MediaStore::ListContainersInput' };
  class_type MediaStore_ListContainersOutput, { class => 'Paws::MediaStore::ListContainersOutput' };
  class_type MediaStore_ListTagsForResourceInput, { class => 'Paws::MediaStore::ListTagsForResourceInput' };
  class_type MediaStore_ListTagsForResourceOutput, { class => 'Paws::MediaStore::ListTagsForResourceOutput' };
  class_type MediaStore_PolicyNotFoundException, { class => 'Paws::MediaStore::PolicyNotFoundException' };
  class_type MediaStore_PutContainerPolicyInput, { class => 'Paws::MediaStore::PutContainerPolicyInput' };
  class_type MediaStore_PutContainerPolicyOutput, { class => 'Paws::MediaStore::PutContainerPolicyOutput' };
  class_type MediaStore_PutCorsPolicyInput, { class => 'Paws::MediaStore::PutCorsPolicyInput' };
  class_type MediaStore_PutCorsPolicyOutput, { class => 'Paws::MediaStore::PutCorsPolicyOutput' };
  class_type MediaStore_PutLifecyclePolicyInput, { class => 'Paws::MediaStore::PutLifecyclePolicyInput' };
  class_type MediaStore_PutLifecyclePolicyOutput, { class => 'Paws::MediaStore::PutLifecyclePolicyOutput' };
  class_type MediaStore_StartAccessLoggingInput, { class => 'Paws::MediaStore::StartAccessLoggingInput' };
  class_type MediaStore_StartAccessLoggingOutput, { class => 'Paws::MediaStore::StartAccessLoggingOutput' };
  class_type MediaStore_StopAccessLoggingInput, { class => 'Paws::MediaStore::StopAccessLoggingInput' };
  class_type MediaStore_StopAccessLoggingOutput, { class => 'Paws::MediaStore::StopAccessLoggingOutput' };
  class_type MediaStore_Tag, { class => 'Paws::MediaStore::Tag' };
  class_type MediaStore_TagResourceInput, { class => 'Paws::MediaStore::TagResourceInput' };
  class_type MediaStore_TagResourceOutput, { class => 'Paws::MediaStore::TagResourceOutput' };
  class_type MediaStore_UntagResourceInput, { class => 'Paws::MediaStore::UntagResourceInput' };
  class_type MediaStore_UntagResourceOutput, { class => 'Paws::MediaStore::UntagResourceOutput' };

1;
