package Paws::FMS::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type FMS_AssociateAdminAccountRequest, { class => 'Paws::FMS::AssociateAdminAccountRequest' };
  class_type FMS_ComplianceViolator, { class => 'Paws::FMS::ComplianceViolator' };
  class_type FMS_CustomerPolicyScopeMap, { class => 'Paws::FMS::CustomerPolicyScopeMap' };
  class_type FMS_DeleteNotificationChannelRequest, { class => 'Paws::FMS::DeleteNotificationChannelRequest' };
  class_type FMS_DeletePolicyRequest, { class => 'Paws::FMS::DeletePolicyRequest' };
  class_type FMS_DisassociateAdminAccountRequest, { class => 'Paws::FMS::DisassociateAdminAccountRequest' };
  class_type FMS_EvaluationResult, { class => 'Paws::FMS::EvaluationResult' };
  class_type FMS_GetAdminAccountRequest, { class => 'Paws::FMS::GetAdminAccountRequest' };
  class_type FMS_GetAdminAccountResponse, { class => 'Paws::FMS::GetAdminAccountResponse' };
  class_type FMS_GetComplianceDetailRequest, { class => 'Paws::FMS::GetComplianceDetailRequest' };
  class_type FMS_GetComplianceDetailResponse, { class => 'Paws::FMS::GetComplianceDetailResponse' };
  class_type FMS_GetNotificationChannelRequest, { class => 'Paws::FMS::GetNotificationChannelRequest' };
  class_type FMS_GetNotificationChannelResponse, { class => 'Paws::FMS::GetNotificationChannelResponse' };
  class_type FMS_GetPolicyRequest, { class => 'Paws::FMS::GetPolicyRequest' };
  class_type FMS_GetPolicyResponse, { class => 'Paws::FMS::GetPolicyResponse' };
  class_type FMS_GetProtectionStatusRequest, { class => 'Paws::FMS::GetProtectionStatusRequest' };
  class_type FMS_GetProtectionStatusResponse, { class => 'Paws::FMS::GetProtectionStatusResponse' };
  class_type FMS_InternalErrorException, { class => 'Paws::FMS::InternalErrorException' };
  class_type FMS_InvalidInputException, { class => 'Paws::FMS::InvalidInputException' };
  class_type FMS_InvalidOperationException, { class => 'Paws::FMS::InvalidOperationException' };
  class_type FMS_InvalidTypeException, { class => 'Paws::FMS::InvalidTypeException' };
  class_type FMS_IssueInfoMap, { class => 'Paws::FMS::IssueInfoMap' };
  class_type FMS_LimitExceededException, { class => 'Paws::FMS::LimitExceededException' };
  class_type FMS_ListComplianceStatusRequest, { class => 'Paws::FMS::ListComplianceStatusRequest' };
  class_type FMS_ListComplianceStatusResponse, { class => 'Paws::FMS::ListComplianceStatusResponse' };
  class_type FMS_ListMemberAccountsRequest, { class => 'Paws::FMS::ListMemberAccountsRequest' };
  class_type FMS_ListMemberAccountsResponse, { class => 'Paws::FMS::ListMemberAccountsResponse' };
  class_type FMS_ListPoliciesRequest, { class => 'Paws::FMS::ListPoliciesRequest' };
  class_type FMS_ListPoliciesResponse, { class => 'Paws::FMS::ListPoliciesResponse' };
  class_type FMS_Policy, { class => 'Paws::FMS::Policy' };
  class_type FMS_PolicyComplianceDetail, { class => 'Paws::FMS::PolicyComplianceDetail' };
  class_type FMS_PolicyComplianceStatus, { class => 'Paws::FMS::PolicyComplianceStatus' };
  class_type FMS_PolicySummary, { class => 'Paws::FMS::PolicySummary' };
  class_type FMS_PutNotificationChannelRequest, { class => 'Paws::FMS::PutNotificationChannelRequest' };
  class_type FMS_PutPolicyRequest, { class => 'Paws::FMS::PutPolicyRequest' };
  class_type FMS_PutPolicyResponse, { class => 'Paws::FMS::PutPolicyResponse' };
  class_type FMS_ResourceNotFoundException, { class => 'Paws::FMS::ResourceNotFoundException' };
  class_type FMS_ResourceTag, { class => 'Paws::FMS::ResourceTag' };
  class_type FMS_SecurityServicePolicyData, { class => 'Paws::FMS::SecurityServicePolicyData' };

1;
