package Paws::ApplicationAutoScaling::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type ApplicationAutoScaling_Alarm, { class => 'Paws::ApplicationAutoScaling::Alarm' };
  class_type ApplicationAutoScaling_ConcurrentUpdateException, { class => 'Paws::ApplicationAutoScaling::ConcurrentUpdateException' };
  class_type ApplicationAutoScaling_CustomizedMetricSpecification, { class => 'Paws::ApplicationAutoScaling::CustomizedMetricSpecification' };
  class_type ApplicationAutoScaling_DeleteScalingPolicyRequest, { class => 'Paws::ApplicationAutoScaling::DeleteScalingPolicyRequest' };
  class_type ApplicationAutoScaling_DeleteScalingPolicyResponse, { class => 'Paws::ApplicationAutoScaling::DeleteScalingPolicyResponse' };
  class_type ApplicationAutoScaling_DeleteScheduledActionRequest, { class => 'Paws::ApplicationAutoScaling::DeleteScheduledActionRequest' };
  class_type ApplicationAutoScaling_DeleteScheduledActionResponse, { class => 'Paws::ApplicationAutoScaling::DeleteScheduledActionResponse' };
  class_type ApplicationAutoScaling_DeregisterScalableTargetRequest, { class => 'Paws::ApplicationAutoScaling::DeregisterScalableTargetRequest' };
  class_type ApplicationAutoScaling_DeregisterScalableTargetResponse, { class => 'Paws::ApplicationAutoScaling::DeregisterScalableTargetResponse' };
  class_type ApplicationAutoScaling_DescribeScalableTargetsRequest, { class => 'Paws::ApplicationAutoScaling::DescribeScalableTargetsRequest' };
  class_type ApplicationAutoScaling_DescribeScalableTargetsResponse, { class => 'Paws::ApplicationAutoScaling::DescribeScalableTargetsResponse' };
  class_type ApplicationAutoScaling_DescribeScalingActivitiesRequest, { class => 'Paws::ApplicationAutoScaling::DescribeScalingActivitiesRequest' };
  class_type ApplicationAutoScaling_DescribeScalingActivitiesResponse, { class => 'Paws::ApplicationAutoScaling::DescribeScalingActivitiesResponse' };
  class_type ApplicationAutoScaling_DescribeScalingPoliciesRequest, { class => 'Paws::ApplicationAutoScaling::DescribeScalingPoliciesRequest' };
  class_type ApplicationAutoScaling_DescribeScalingPoliciesResponse, { class => 'Paws::ApplicationAutoScaling::DescribeScalingPoliciesResponse' };
  class_type ApplicationAutoScaling_DescribeScheduledActionsRequest, { class => 'Paws::ApplicationAutoScaling::DescribeScheduledActionsRequest' };
  class_type ApplicationAutoScaling_DescribeScheduledActionsResponse, { class => 'Paws::ApplicationAutoScaling::DescribeScheduledActionsResponse' };
  class_type ApplicationAutoScaling_FailedResourceAccessException, { class => 'Paws::ApplicationAutoScaling::FailedResourceAccessException' };
  class_type ApplicationAutoScaling_InternalServiceException, { class => 'Paws::ApplicationAutoScaling::InternalServiceException' };
  class_type ApplicationAutoScaling_InvalidNextTokenException, { class => 'Paws::ApplicationAutoScaling::InvalidNextTokenException' };
  class_type ApplicationAutoScaling_LimitExceededException, { class => 'Paws::ApplicationAutoScaling::LimitExceededException' };
  class_type ApplicationAutoScaling_MetricDimension, { class => 'Paws::ApplicationAutoScaling::MetricDimension' };
  class_type ApplicationAutoScaling_ObjectNotFoundException, { class => 'Paws::ApplicationAutoScaling::ObjectNotFoundException' };
  class_type ApplicationAutoScaling_PredefinedMetricSpecification, { class => 'Paws::ApplicationAutoScaling::PredefinedMetricSpecification' };
  class_type ApplicationAutoScaling_PutScalingPolicyRequest, { class => 'Paws::ApplicationAutoScaling::PutScalingPolicyRequest' };
  class_type ApplicationAutoScaling_PutScalingPolicyResponse, { class => 'Paws::ApplicationAutoScaling::PutScalingPolicyResponse' };
  class_type ApplicationAutoScaling_PutScheduledActionRequest, { class => 'Paws::ApplicationAutoScaling::PutScheduledActionRequest' };
  class_type ApplicationAutoScaling_PutScheduledActionResponse, { class => 'Paws::ApplicationAutoScaling::PutScheduledActionResponse' };
  class_type ApplicationAutoScaling_RegisterScalableTargetRequest, { class => 'Paws::ApplicationAutoScaling::RegisterScalableTargetRequest' };
  class_type ApplicationAutoScaling_RegisterScalableTargetResponse, { class => 'Paws::ApplicationAutoScaling::RegisterScalableTargetResponse' };
  class_type ApplicationAutoScaling_ScalableTarget, { class => 'Paws::ApplicationAutoScaling::ScalableTarget' };
  class_type ApplicationAutoScaling_ScalableTargetAction, { class => 'Paws::ApplicationAutoScaling::ScalableTargetAction' };
  class_type ApplicationAutoScaling_ScalingActivity, { class => 'Paws::ApplicationAutoScaling::ScalingActivity' };
  class_type ApplicationAutoScaling_ScalingPolicy, { class => 'Paws::ApplicationAutoScaling::ScalingPolicy' };
  class_type ApplicationAutoScaling_ScheduledAction, { class => 'Paws::ApplicationAutoScaling::ScheduledAction' };
  class_type ApplicationAutoScaling_StepAdjustment, { class => 'Paws::ApplicationAutoScaling::StepAdjustment' };
  class_type ApplicationAutoScaling_StepScalingPolicyConfiguration, { class => 'Paws::ApplicationAutoScaling::StepScalingPolicyConfiguration' };
  class_type ApplicationAutoScaling_TargetTrackingScalingPolicyConfiguration, { class => 'Paws::ApplicationAutoScaling::TargetTrackingScalingPolicyConfiguration' };
  class_type ApplicationAutoScaling_ValidationException, { class => 'Paws::ApplicationAutoScaling::ValidationException' };

1;
