package Paws::LicenseManager::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type LicenseManager_AccessDeniedException, { class => 'Paws::LicenseManager::AccessDeniedException' };
  class_type LicenseManager_AuthorizationException, { class => 'Paws::LicenseManager::AuthorizationException' };
  class_type LicenseManager_ConsumedLicenseSummary, { class => 'Paws::LicenseManager::ConsumedLicenseSummary' };
  class_type LicenseManager_CreateLicenseConfigurationRequest, { class => 'Paws::LicenseManager::CreateLicenseConfigurationRequest' };
  class_type LicenseManager_CreateLicenseConfigurationResponse, { class => 'Paws::LicenseManager::CreateLicenseConfigurationResponse' };
  class_type LicenseManager_DeleteLicenseConfigurationRequest, { class => 'Paws::LicenseManager::DeleteLicenseConfigurationRequest' };
  class_type LicenseManager_DeleteLicenseConfigurationResponse, { class => 'Paws::LicenseManager::DeleteLicenseConfigurationResponse' };
  class_type LicenseManager_FailedDependencyException, { class => 'Paws::LicenseManager::FailedDependencyException' };
  class_type LicenseManager_Filter, { class => 'Paws::LicenseManager::Filter' };
  class_type LicenseManager_FilterLimitExceededException, { class => 'Paws::LicenseManager::FilterLimitExceededException' };
  class_type LicenseManager_GetLicenseConfigurationRequest, { class => 'Paws::LicenseManager::GetLicenseConfigurationRequest' };
  class_type LicenseManager_GetLicenseConfigurationResponse, { class => 'Paws::LicenseManager::GetLicenseConfigurationResponse' };
  class_type LicenseManager_GetServiceSettingsRequest, { class => 'Paws::LicenseManager::GetServiceSettingsRequest' };
  class_type LicenseManager_GetServiceSettingsResponse, { class => 'Paws::LicenseManager::GetServiceSettingsResponse' };
  class_type LicenseManager_InvalidParameterValueException, { class => 'Paws::LicenseManager::InvalidParameterValueException' };
  class_type LicenseManager_InvalidResourceStateException, { class => 'Paws::LicenseManager::InvalidResourceStateException' };
  class_type LicenseManager_InventoryFilter, { class => 'Paws::LicenseManager::InventoryFilter' };
  class_type LicenseManager_LicenseConfiguration, { class => 'Paws::LicenseManager::LicenseConfiguration' };
  class_type LicenseManager_LicenseConfigurationAssociation, { class => 'Paws::LicenseManager::LicenseConfigurationAssociation' };
  class_type LicenseManager_LicenseConfigurationUsage, { class => 'Paws::LicenseManager::LicenseConfigurationUsage' };
  class_type LicenseManager_LicenseSpecification, { class => 'Paws::LicenseManager::LicenseSpecification' };
  class_type LicenseManager_LicenseUsageException, { class => 'Paws::LicenseManager::LicenseUsageException' };
  class_type LicenseManager_ListAssociationsForLicenseConfigurationRequest, { class => 'Paws::LicenseManager::ListAssociationsForLicenseConfigurationRequest' };
  class_type LicenseManager_ListAssociationsForLicenseConfigurationResponse, { class => 'Paws::LicenseManager::ListAssociationsForLicenseConfigurationResponse' };
  class_type LicenseManager_ListLicenseConfigurationsRequest, { class => 'Paws::LicenseManager::ListLicenseConfigurationsRequest' };
  class_type LicenseManager_ListLicenseConfigurationsResponse, { class => 'Paws::LicenseManager::ListLicenseConfigurationsResponse' };
  class_type LicenseManager_ListLicenseSpecificationsForResourceRequest, { class => 'Paws::LicenseManager::ListLicenseSpecificationsForResourceRequest' };
  class_type LicenseManager_ListLicenseSpecificationsForResourceResponse, { class => 'Paws::LicenseManager::ListLicenseSpecificationsForResourceResponse' };
  class_type LicenseManager_ListResourceInventoryRequest, { class => 'Paws::LicenseManager::ListResourceInventoryRequest' };
  class_type LicenseManager_ListResourceInventoryResponse, { class => 'Paws::LicenseManager::ListResourceInventoryResponse' };
  class_type LicenseManager_ListTagsForResourceRequest, { class => 'Paws::LicenseManager::ListTagsForResourceRequest' };
  class_type LicenseManager_ListTagsForResourceResponse, { class => 'Paws::LicenseManager::ListTagsForResourceResponse' };
  class_type LicenseManager_ListUsageForLicenseConfigurationRequest, { class => 'Paws::LicenseManager::ListUsageForLicenseConfigurationRequest' };
  class_type LicenseManager_ListUsageForLicenseConfigurationResponse, { class => 'Paws::LicenseManager::ListUsageForLicenseConfigurationResponse' };
  class_type LicenseManager_ManagedResourceSummary, { class => 'Paws::LicenseManager::ManagedResourceSummary' };
  class_type LicenseManager_OrganizationConfiguration, { class => 'Paws::LicenseManager::OrganizationConfiguration' };
  class_type LicenseManager_RateLimitExceededException, { class => 'Paws::LicenseManager::RateLimitExceededException' };
  class_type LicenseManager_ResourceInventory, { class => 'Paws::LicenseManager::ResourceInventory' };
  class_type LicenseManager_ResourceLimitExceededException, { class => 'Paws::LicenseManager::ResourceLimitExceededException' };
  class_type LicenseManager_ServerInternalException, { class => 'Paws::LicenseManager::ServerInternalException' };
  class_type LicenseManager_Tag, { class => 'Paws::LicenseManager::Tag' };
  class_type LicenseManager_TagResourceRequest, { class => 'Paws::LicenseManager::TagResourceRequest' };
  class_type LicenseManager_TagResourceResponse, { class => 'Paws::LicenseManager::TagResourceResponse' };
  class_type LicenseManager_UntagResourceRequest, { class => 'Paws::LicenseManager::UntagResourceRequest' };
  class_type LicenseManager_UntagResourceResponse, { class => 'Paws::LicenseManager::UntagResourceResponse' };
  class_type LicenseManager_UpdateLicenseConfigurationRequest, { class => 'Paws::LicenseManager::UpdateLicenseConfigurationRequest' };
  class_type LicenseManager_UpdateLicenseConfigurationResponse, { class => 'Paws::LicenseManager::UpdateLicenseConfigurationResponse' };
  class_type LicenseManager_UpdateLicenseSpecificationsForResourceRequest, { class => 'Paws::LicenseManager::UpdateLicenseSpecificationsForResourceRequest' };
  class_type LicenseManager_UpdateLicenseSpecificationsForResourceResponse, { class => 'Paws::LicenseManager::UpdateLicenseSpecificationsForResourceResponse' };
  class_type LicenseManager_UpdateServiceSettingsRequest, { class => 'Paws::LicenseManager::UpdateServiceSettingsRequest' };
  class_type LicenseManager_UpdateServiceSettingsResponse, { class => 'Paws::LicenseManager::UpdateServiceSettingsResponse' };

1;
