package Paws::LakeFormation::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type LakeFormation_AlreadyExistsException, { class => 'Paws::LakeFormation::AlreadyExistsException' };
  class_type LakeFormation_BatchGrantPermissionsRequest, { class => 'Paws::LakeFormation::BatchGrantPermissionsRequest' };
  class_type LakeFormation_BatchGrantPermissionsResponse, { class => 'Paws::LakeFormation::BatchGrantPermissionsResponse' };
  class_type LakeFormation_BatchPermissionsFailureEntry, { class => 'Paws::LakeFormation::BatchPermissionsFailureEntry' };
  class_type LakeFormation_BatchPermissionsRequestEntry, { class => 'Paws::LakeFormation::BatchPermissionsRequestEntry' };
  class_type LakeFormation_BatchRevokePermissionsRequest, { class => 'Paws::LakeFormation::BatchRevokePermissionsRequest' };
  class_type LakeFormation_BatchRevokePermissionsResponse, { class => 'Paws::LakeFormation::BatchRevokePermissionsResponse' };
  class_type LakeFormation_CatalogResource, { class => 'Paws::LakeFormation::CatalogResource' };
  class_type LakeFormation_ColumnWildcard, { class => 'Paws::LakeFormation::ColumnWildcard' };
  class_type LakeFormation_ConcurrentModificationException, { class => 'Paws::LakeFormation::ConcurrentModificationException' };
  class_type LakeFormation_DatabaseResource, { class => 'Paws::LakeFormation::DatabaseResource' };
  class_type LakeFormation_DataLakePrincipal, { class => 'Paws::LakeFormation::DataLakePrincipal' };
  class_type LakeFormation_DataLakeSettings, { class => 'Paws::LakeFormation::DataLakeSettings' };
  class_type LakeFormation_DataLocationResource, { class => 'Paws::LakeFormation::DataLocationResource' };
  class_type LakeFormation_DeregisterResourceRequest, { class => 'Paws::LakeFormation::DeregisterResourceRequest' };
  class_type LakeFormation_DeregisterResourceResponse, { class => 'Paws::LakeFormation::DeregisterResourceResponse' };
  class_type LakeFormation_DescribeResourceRequest, { class => 'Paws::LakeFormation::DescribeResourceRequest' };
  class_type LakeFormation_DescribeResourceResponse, { class => 'Paws::LakeFormation::DescribeResourceResponse' };
  class_type LakeFormation_EntityNotFoundException, { class => 'Paws::LakeFormation::EntityNotFoundException' };
  class_type LakeFormation_ErrorDetail, { class => 'Paws::LakeFormation::ErrorDetail' };
  class_type LakeFormation_FilterCondition, { class => 'Paws::LakeFormation::FilterCondition' };
  class_type LakeFormation_GetDataLakeSettingsRequest, { class => 'Paws::LakeFormation::GetDataLakeSettingsRequest' };
  class_type LakeFormation_GetDataLakeSettingsResponse, { class => 'Paws::LakeFormation::GetDataLakeSettingsResponse' };
  class_type LakeFormation_GetEffectivePermissionsForPathRequest, { class => 'Paws::LakeFormation::GetEffectivePermissionsForPathRequest' };
  class_type LakeFormation_GetEffectivePermissionsForPathResponse, { class => 'Paws::LakeFormation::GetEffectivePermissionsForPathResponse' };
  class_type LakeFormation_GrantPermissionsRequest, { class => 'Paws::LakeFormation::GrantPermissionsRequest' };
  class_type LakeFormation_GrantPermissionsResponse, { class => 'Paws::LakeFormation::GrantPermissionsResponse' };
  class_type LakeFormation_InternalServiceException, { class => 'Paws::LakeFormation::InternalServiceException' };
  class_type LakeFormation_InvalidInputException, { class => 'Paws::LakeFormation::InvalidInputException' };
  class_type LakeFormation_ListPermissionsRequest, { class => 'Paws::LakeFormation::ListPermissionsRequest' };
  class_type LakeFormation_ListPermissionsResponse, { class => 'Paws::LakeFormation::ListPermissionsResponse' };
  class_type LakeFormation_ListResourcesRequest, { class => 'Paws::LakeFormation::ListResourcesRequest' };
  class_type LakeFormation_ListResourcesResponse, { class => 'Paws::LakeFormation::ListResourcesResponse' };
  class_type LakeFormation_OperationTimeoutException, { class => 'Paws::LakeFormation::OperationTimeoutException' };
  class_type LakeFormation_PrincipalPermissions, { class => 'Paws::LakeFormation::PrincipalPermissions' };
  class_type LakeFormation_PrincipalResourcePermissions, { class => 'Paws::LakeFormation::PrincipalResourcePermissions' };
  class_type LakeFormation_PutDataLakeSettingsRequest, { class => 'Paws::LakeFormation::PutDataLakeSettingsRequest' };
  class_type LakeFormation_PutDataLakeSettingsResponse, { class => 'Paws::LakeFormation::PutDataLakeSettingsResponse' };
  class_type LakeFormation_RegisterResourceRequest, { class => 'Paws::LakeFormation::RegisterResourceRequest' };
  class_type LakeFormation_RegisterResourceResponse, { class => 'Paws::LakeFormation::RegisterResourceResponse' };
  class_type LakeFormation_Resource, { class => 'Paws::LakeFormation::Resource' };
  class_type LakeFormation_ResourceInfo, { class => 'Paws::LakeFormation::ResourceInfo' };
  class_type LakeFormation_RevokePermissionsRequest, { class => 'Paws::LakeFormation::RevokePermissionsRequest' };
  class_type LakeFormation_RevokePermissionsResponse, { class => 'Paws::LakeFormation::RevokePermissionsResponse' };
  class_type LakeFormation_TableResource, { class => 'Paws::LakeFormation::TableResource' };
  class_type LakeFormation_TableWithColumnsResource, { class => 'Paws::LakeFormation::TableWithColumnsResource' };
  class_type LakeFormation_UpdateResourceRequest, { class => 'Paws::LakeFormation::UpdateResourceRequest' };
  class_type LakeFormation_UpdateResourceResponse, { class => 'Paws::LakeFormation::UpdateResourceResponse' };

1;
