package Paws::Signer::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type Signer_AccessDeniedException, { class => 'Paws::Signer::AccessDeniedException' };
  class_type Signer_CancelSigningProfileRequest, { class => 'Paws::Signer::CancelSigningProfileRequest' };
  class_type Signer_DescribeSigningJobRequest, { class => 'Paws::Signer::DescribeSigningJobRequest' };
  class_type Signer_DescribeSigningJobResponse, { class => 'Paws::Signer::DescribeSigningJobResponse' };
  class_type Signer_Destination, { class => 'Paws::Signer::Destination' };
  class_type Signer_EncryptionAlgorithmOptions, { class => 'Paws::Signer::EncryptionAlgorithmOptions' };
  class_type Signer_GetSigningPlatformRequest, { class => 'Paws::Signer::GetSigningPlatformRequest' };
  class_type Signer_GetSigningPlatformResponse, { class => 'Paws::Signer::GetSigningPlatformResponse' };
  class_type Signer_GetSigningProfileRequest, { class => 'Paws::Signer::GetSigningProfileRequest' };
  class_type Signer_GetSigningProfileResponse, { class => 'Paws::Signer::GetSigningProfileResponse' };
  class_type Signer_HashAlgorithmOptions, { class => 'Paws::Signer::HashAlgorithmOptions' };
  class_type Signer_InternalServiceErrorException, { class => 'Paws::Signer::InternalServiceErrorException' };
  class_type Signer_ListSigningJobsRequest, { class => 'Paws::Signer::ListSigningJobsRequest' };
  class_type Signer_ListSigningJobsResponse, { class => 'Paws::Signer::ListSigningJobsResponse' };
  class_type Signer_ListSigningPlatformsRequest, { class => 'Paws::Signer::ListSigningPlatformsRequest' };
  class_type Signer_ListSigningPlatformsResponse, { class => 'Paws::Signer::ListSigningPlatformsResponse' };
  class_type Signer_ListSigningProfilesRequest, { class => 'Paws::Signer::ListSigningProfilesRequest' };
  class_type Signer_ListSigningProfilesResponse, { class => 'Paws::Signer::ListSigningProfilesResponse' };
  class_type Signer_PutSigningProfileRequest, { class => 'Paws::Signer::PutSigningProfileRequest' };
  class_type Signer_PutSigningProfileResponse, { class => 'Paws::Signer::PutSigningProfileResponse' };
  class_type Signer_ResourceNotFoundException, { class => 'Paws::Signer::ResourceNotFoundException' };
  class_type Signer_S3Destination, { class => 'Paws::Signer::S3Destination' };
  class_type Signer_S3SignedObject, { class => 'Paws::Signer::S3SignedObject' };
  class_type Signer_S3Source, { class => 'Paws::Signer::S3Source' };
  class_type Signer_SignedObject, { class => 'Paws::Signer::SignedObject' };
  class_type Signer_SigningConfiguration, { class => 'Paws::Signer::SigningConfiguration' };
  class_type Signer_SigningConfigurationOverrides, { class => 'Paws::Signer::SigningConfigurationOverrides' };
  class_type Signer_SigningImageFormat, { class => 'Paws::Signer::SigningImageFormat' };
  class_type Signer_SigningJob, { class => 'Paws::Signer::SigningJob' };
  class_type Signer_SigningMaterial, { class => 'Paws::Signer::SigningMaterial' };
  class_type Signer_SigningParameters, { class => 'Paws::Signer::SigningParameters' };
  class_type Signer_SigningPlatform, { class => 'Paws::Signer::SigningPlatform' };
  class_type Signer_SigningPlatformOverrides, { class => 'Paws::Signer::SigningPlatformOverrides' };
  class_type Signer_SigningProfile, { class => 'Paws::Signer::SigningProfile' };
  class_type Signer_Source, { class => 'Paws::Signer::Source' };
  class_type Signer_StartSigningJobRequest, { class => 'Paws::Signer::StartSigningJobRequest' };
  class_type Signer_StartSigningJobResponse, { class => 'Paws::Signer::StartSigningJobResponse' };
  class_type Signer_ThrottlingException, { class => 'Paws::Signer::ThrottlingException' };
  class_type Signer_ValidationException, { class => 'Paws::Signer::ValidationException' };

1;
