package Paws::SavingsPlans::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type SavingsPlans_CreateSavingsPlanRequest, { class => 'Paws::SavingsPlans::CreateSavingsPlanRequest' };
  class_type SavingsPlans_CreateSavingsPlanResponse, { class => 'Paws::SavingsPlans::CreateSavingsPlanResponse' };
  class_type SavingsPlans_DescribeSavingsPlanRatesRequest, { class => 'Paws::SavingsPlans::DescribeSavingsPlanRatesRequest' };
  class_type SavingsPlans_DescribeSavingsPlanRatesResponse, { class => 'Paws::SavingsPlans::DescribeSavingsPlanRatesResponse' };
  class_type SavingsPlans_DescribeSavingsPlansOfferingRatesRequest, { class => 'Paws::SavingsPlans::DescribeSavingsPlansOfferingRatesRequest' };
  class_type SavingsPlans_DescribeSavingsPlansOfferingRatesResponse, { class => 'Paws::SavingsPlans::DescribeSavingsPlansOfferingRatesResponse' };
  class_type SavingsPlans_DescribeSavingsPlansOfferingsRequest, { class => 'Paws::SavingsPlans::DescribeSavingsPlansOfferingsRequest' };
  class_type SavingsPlans_DescribeSavingsPlansOfferingsResponse, { class => 'Paws::SavingsPlans::DescribeSavingsPlansOfferingsResponse' };
  class_type SavingsPlans_DescribeSavingsPlansRequest, { class => 'Paws::SavingsPlans::DescribeSavingsPlansRequest' };
  class_type SavingsPlans_DescribeSavingsPlansResponse, { class => 'Paws::SavingsPlans::DescribeSavingsPlansResponse' };
  class_type SavingsPlans_InternalServerException, { class => 'Paws::SavingsPlans::InternalServerException' };
  class_type SavingsPlans_ListTagsForResourceRequest, { class => 'Paws::SavingsPlans::ListTagsForResourceRequest' };
  class_type SavingsPlans_ListTagsForResourceResponse, { class => 'Paws::SavingsPlans::ListTagsForResourceResponse' };
  class_type SavingsPlans_ParentSavingsPlanOffering, { class => 'Paws::SavingsPlans::ParentSavingsPlanOffering' };
  class_type SavingsPlans_ResourceNotFoundException, { class => 'Paws::SavingsPlans::ResourceNotFoundException' };
  class_type SavingsPlans_SavingsPlan, { class => 'Paws::SavingsPlans::SavingsPlan' };
  class_type SavingsPlans_SavingsPlanFilter, { class => 'Paws::SavingsPlans::SavingsPlanFilter' };
  class_type SavingsPlans_SavingsPlanOffering, { class => 'Paws::SavingsPlans::SavingsPlanOffering' };
  class_type SavingsPlans_SavingsPlanOfferingFilterElement, { class => 'Paws::SavingsPlans::SavingsPlanOfferingFilterElement' };
  class_type SavingsPlans_SavingsPlanOfferingProperty, { class => 'Paws::SavingsPlans::SavingsPlanOfferingProperty' };
  class_type SavingsPlans_SavingsPlanOfferingRate, { class => 'Paws::SavingsPlans::SavingsPlanOfferingRate' };
  class_type SavingsPlans_SavingsPlanOfferingRateFilterElement, { class => 'Paws::SavingsPlans::SavingsPlanOfferingRateFilterElement' };
  class_type SavingsPlans_SavingsPlanOfferingRateProperty, { class => 'Paws::SavingsPlans::SavingsPlanOfferingRateProperty' };
  class_type SavingsPlans_SavingsPlanRate, { class => 'Paws::SavingsPlans::SavingsPlanRate' };
  class_type SavingsPlans_SavingsPlanRateFilter, { class => 'Paws::SavingsPlans::SavingsPlanRateFilter' };
  class_type SavingsPlans_SavingsPlanRateProperty, { class => 'Paws::SavingsPlans::SavingsPlanRateProperty' };
  class_type SavingsPlans_ServiceQuotaExceededException, { class => 'Paws::SavingsPlans::ServiceQuotaExceededException' };
  class_type SavingsPlans_TagMap, { class => 'Paws::SavingsPlans::TagMap' };
  class_type SavingsPlans_TagResourceRequest, { class => 'Paws::SavingsPlans::TagResourceRequest' };
  class_type SavingsPlans_TagResourceResponse, { class => 'Paws::SavingsPlans::TagResourceResponse' };
  class_type SavingsPlans_UntagResourceRequest, { class => 'Paws::SavingsPlans::UntagResourceRequest' };
  class_type SavingsPlans_UntagResourceResponse, { class => 'Paws::SavingsPlans::UntagResourceResponse' };
  class_type SavingsPlans_ValidationException, { class => 'Paws::SavingsPlans::ValidationException' };

1;
