package Paws::CloudHSMv2::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CloudHSMv2_Backup, { class => 'Paws::CloudHSMv2::Backup' };
  class_type CloudHSMv2_Certificates, { class => 'Paws::CloudHSMv2::Certificates' };
  class_type CloudHSMv2_CloudHsmAccessDeniedException, { class => 'Paws::CloudHSMv2::CloudHsmAccessDeniedException' };
  class_type CloudHSMv2_CloudHsmInternalFailureException, { class => 'Paws::CloudHSMv2::CloudHsmInternalFailureException' };
  class_type CloudHSMv2_CloudHsmInvalidRequestException, { class => 'Paws::CloudHSMv2::CloudHsmInvalidRequestException' };
  class_type CloudHSMv2_CloudHsmResourceNotFoundException, { class => 'Paws::CloudHSMv2::CloudHsmResourceNotFoundException' };
  class_type CloudHSMv2_CloudHsmServiceException, { class => 'Paws::CloudHSMv2::CloudHsmServiceException' };
  class_type CloudHSMv2_Cluster, { class => 'Paws::CloudHSMv2::Cluster' };
  class_type CloudHSMv2_CopyBackupToRegionRequest, { class => 'Paws::CloudHSMv2::CopyBackupToRegionRequest' };
  class_type CloudHSMv2_CopyBackupToRegionResponse, { class => 'Paws::CloudHSMv2::CopyBackupToRegionResponse' };
  class_type CloudHSMv2_CreateClusterRequest, { class => 'Paws::CloudHSMv2::CreateClusterRequest' };
  class_type CloudHSMv2_CreateClusterResponse, { class => 'Paws::CloudHSMv2::CreateClusterResponse' };
  class_type CloudHSMv2_CreateHsmRequest, { class => 'Paws::CloudHSMv2::CreateHsmRequest' };
  class_type CloudHSMv2_CreateHsmResponse, { class => 'Paws::CloudHSMv2::CreateHsmResponse' };
  class_type CloudHSMv2_DeleteBackupRequest, { class => 'Paws::CloudHSMv2::DeleteBackupRequest' };
  class_type CloudHSMv2_DeleteBackupResponse, { class => 'Paws::CloudHSMv2::DeleteBackupResponse' };
  class_type CloudHSMv2_DeleteClusterRequest, { class => 'Paws::CloudHSMv2::DeleteClusterRequest' };
  class_type CloudHSMv2_DeleteClusterResponse, { class => 'Paws::CloudHSMv2::DeleteClusterResponse' };
  class_type CloudHSMv2_DeleteHsmRequest, { class => 'Paws::CloudHSMv2::DeleteHsmRequest' };
  class_type CloudHSMv2_DeleteHsmResponse, { class => 'Paws::CloudHSMv2::DeleteHsmResponse' };
  class_type CloudHSMv2_DescribeBackupsRequest, { class => 'Paws::CloudHSMv2::DescribeBackupsRequest' };
  class_type CloudHSMv2_DescribeBackupsResponse, { class => 'Paws::CloudHSMv2::DescribeBackupsResponse' };
  class_type CloudHSMv2_DescribeClustersRequest, { class => 'Paws::CloudHSMv2::DescribeClustersRequest' };
  class_type CloudHSMv2_DescribeClustersResponse, { class => 'Paws::CloudHSMv2::DescribeClustersResponse' };
  class_type CloudHSMv2_DestinationBackup, { class => 'Paws::CloudHSMv2::DestinationBackup' };
  class_type CloudHSMv2_ExternalSubnetMapping, { class => 'Paws::CloudHSMv2::ExternalSubnetMapping' };
  class_type CloudHSMv2_Filters, { class => 'Paws::CloudHSMv2::Filters' };
  class_type CloudHSMv2_Hsm, { class => 'Paws::CloudHSMv2::Hsm' };
  class_type CloudHSMv2_InitializeClusterRequest, { class => 'Paws::CloudHSMv2::InitializeClusterRequest' };
  class_type CloudHSMv2_InitializeClusterResponse, { class => 'Paws::CloudHSMv2::InitializeClusterResponse' };
  class_type CloudHSMv2_ListTagsRequest, { class => 'Paws::CloudHSMv2::ListTagsRequest' };
  class_type CloudHSMv2_ListTagsResponse, { class => 'Paws::CloudHSMv2::ListTagsResponse' };
  class_type CloudHSMv2_RestoreBackupRequest, { class => 'Paws::CloudHSMv2::RestoreBackupRequest' };
  class_type CloudHSMv2_RestoreBackupResponse, { class => 'Paws::CloudHSMv2::RestoreBackupResponse' };
  class_type CloudHSMv2_Tag, { class => 'Paws::CloudHSMv2::Tag' };
  class_type CloudHSMv2_TagResourceRequest, { class => 'Paws::CloudHSMv2::TagResourceRequest' };
  class_type CloudHSMv2_TagResourceResponse, { class => 'Paws::CloudHSMv2::TagResourceResponse' };
  class_type CloudHSMv2_UntagResourceRequest, { class => 'Paws::CloudHSMv2::UntagResourceRequest' };
  class_type CloudHSMv2_UntagResourceResponse, { class => 'Paws::CloudHSMv2::UntagResourceResponse' };

1;
