package Paws::RAM::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type RAM_AcceptResourceShareInvitationRequest, { class => 'Paws::RAM::AcceptResourceShareInvitationRequest' };
  class_type RAM_AcceptResourceShareInvitationResponse, { class => 'Paws::RAM::AcceptResourceShareInvitationResponse' };
  class_type RAM_AssociateResourceShareRequest, { class => 'Paws::RAM::AssociateResourceShareRequest' };
  class_type RAM_AssociateResourceShareResponse, { class => 'Paws::RAM::AssociateResourceShareResponse' };
  class_type RAM_CreateResourceShareRequest, { class => 'Paws::RAM::CreateResourceShareRequest' };
  class_type RAM_CreateResourceShareResponse, { class => 'Paws::RAM::CreateResourceShareResponse' };
  class_type RAM_DeleteResourceShareRequest, { class => 'Paws::RAM::DeleteResourceShareRequest' };
  class_type RAM_DeleteResourceShareResponse, { class => 'Paws::RAM::DeleteResourceShareResponse' };
  class_type RAM_DisassociateResourceShareRequest, { class => 'Paws::RAM::DisassociateResourceShareRequest' };
  class_type RAM_DisassociateResourceShareResponse, { class => 'Paws::RAM::DisassociateResourceShareResponse' };
  class_type RAM_EnableSharingWithAwsOrganizationRequest, { class => 'Paws::RAM::EnableSharingWithAwsOrganizationRequest' };
  class_type RAM_EnableSharingWithAwsOrganizationResponse, { class => 'Paws::RAM::EnableSharingWithAwsOrganizationResponse' };
  class_type RAM_GetResourcePoliciesRequest, { class => 'Paws::RAM::GetResourcePoliciesRequest' };
  class_type RAM_GetResourcePoliciesResponse, { class => 'Paws::RAM::GetResourcePoliciesResponse' };
  class_type RAM_GetResourceShareAssociationsRequest, { class => 'Paws::RAM::GetResourceShareAssociationsRequest' };
  class_type RAM_GetResourceShareAssociationsResponse, { class => 'Paws::RAM::GetResourceShareAssociationsResponse' };
  class_type RAM_GetResourceShareInvitationsRequest, { class => 'Paws::RAM::GetResourceShareInvitationsRequest' };
  class_type RAM_GetResourceShareInvitationsResponse, { class => 'Paws::RAM::GetResourceShareInvitationsResponse' };
  class_type RAM_GetResourceSharesRequest, { class => 'Paws::RAM::GetResourceSharesRequest' };
  class_type RAM_GetResourceSharesResponse, { class => 'Paws::RAM::GetResourceSharesResponse' };
  class_type RAM_IdempotentParameterMismatchException, { class => 'Paws::RAM::IdempotentParameterMismatchException' };
  class_type RAM_InvalidClientTokenException, { class => 'Paws::RAM::InvalidClientTokenException' };
  class_type RAM_InvalidMaxResultsException, { class => 'Paws::RAM::InvalidMaxResultsException' };
  class_type RAM_InvalidNextTokenException, { class => 'Paws::RAM::InvalidNextTokenException' };
  class_type RAM_InvalidParameterException, { class => 'Paws::RAM::InvalidParameterException' };
  class_type RAM_InvalidResourceTypeException, { class => 'Paws::RAM::InvalidResourceTypeException' };
  class_type RAM_InvalidStateTransitionException, { class => 'Paws::RAM::InvalidStateTransitionException' };
  class_type RAM_ListPrincipalsRequest, { class => 'Paws::RAM::ListPrincipalsRequest' };
  class_type RAM_ListPrincipalsResponse, { class => 'Paws::RAM::ListPrincipalsResponse' };
  class_type RAM_ListResourcesRequest, { class => 'Paws::RAM::ListResourcesRequest' };
  class_type RAM_ListResourcesResponse, { class => 'Paws::RAM::ListResourcesResponse' };
  class_type RAM_MalformedArnException, { class => 'Paws::RAM::MalformedArnException' };
  class_type RAM_MissingRequiredParameterException, { class => 'Paws::RAM::MissingRequiredParameterException' };
  class_type RAM_OperationNotPermittedException, { class => 'Paws::RAM::OperationNotPermittedException' };
  class_type RAM_Principal, { class => 'Paws::RAM::Principal' };
  class_type RAM_RejectResourceShareInvitationRequest, { class => 'Paws::RAM::RejectResourceShareInvitationRequest' };
  class_type RAM_RejectResourceShareInvitationResponse, { class => 'Paws::RAM::RejectResourceShareInvitationResponse' };
  class_type RAM_Resource, { class => 'Paws::RAM::Resource' };
  class_type RAM_ResourceArnNotFoundException, { class => 'Paws::RAM::ResourceArnNotFoundException' };
  class_type RAM_ResourceShare, { class => 'Paws::RAM::ResourceShare' };
  class_type RAM_ResourceShareAssociation, { class => 'Paws::RAM::ResourceShareAssociation' };
  class_type RAM_ResourceShareInvitation, { class => 'Paws::RAM::ResourceShareInvitation' };
  class_type RAM_ResourceShareInvitationAlreadyAcceptedException, { class => 'Paws::RAM::ResourceShareInvitationAlreadyAcceptedException' };
  class_type RAM_ResourceShareInvitationAlreadyRejectedException, { class => 'Paws::RAM::ResourceShareInvitationAlreadyRejectedException' };
  class_type RAM_ResourceShareInvitationArnNotFoundException, { class => 'Paws::RAM::ResourceShareInvitationArnNotFoundException' };
  class_type RAM_ResourceShareInvitationExpiredException, { class => 'Paws::RAM::ResourceShareInvitationExpiredException' };
  class_type RAM_ResourceShareLimitExceededException, { class => 'Paws::RAM::ResourceShareLimitExceededException' };
  class_type RAM_ServerInternalException, { class => 'Paws::RAM::ServerInternalException' };
  class_type RAM_ServiceUnavailableException, { class => 'Paws::RAM::ServiceUnavailableException' };
  class_type RAM_Tag, { class => 'Paws::RAM::Tag' };
  class_type RAM_TagFilter, { class => 'Paws::RAM::TagFilter' };
  class_type RAM_TagLimitExceededException, { class => 'Paws::RAM::TagLimitExceededException' };
  class_type RAM_TagResourceRequest, { class => 'Paws::RAM::TagResourceRequest' };
  class_type RAM_TagResourceResponse, { class => 'Paws::RAM::TagResourceResponse' };
  class_type RAM_UnknownResourceException, { class => 'Paws::RAM::UnknownResourceException' };
  class_type RAM_UntagResourceRequest, { class => 'Paws::RAM::UntagResourceRequest' };
  class_type RAM_UntagResourceResponse, { class => 'Paws::RAM::UntagResourceResponse' };
  class_type RAM_UpdateResourceShareRequest, { class => 'Paws::RAM::UpdateResourceShareRequest' };
  class_type RAM_UpdateResourceShareResponse, { class => 'Paws::RAM::UpdateResourceShareResponse' };

1;
