package Paws::CloudHSM::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type CloudHSM_AddTagsToResourceRequest, { class => 'Paws::CloudHSM::AddTagsToResourceRequest' };
  class_type CloudHSM_AddTagsToResourceResponse, { class => 'Paws::CloudHSM::AddTagsToResourceResponse' };
  class_type CloudHSM_CloudHsmInternalException, { class => 'Paws::CloudHSM::CloudHsmInternalException' };
  class_type CloudHSM_CloudHsmServiceException, { class => 'Paws::CloudHSM::CloudHsmServiceException' };
  class_type CloudHSM_CreateHapgRequest, { class => 'Paws::CloudHSM::CreateHapgRequest' };
  class_type CloudHSM_CreateHapgResponse, { class => 'Paws::CloudHSM::CreateHapgResponse' };
  class_type CloudHSM_CreateHsmRequest, { class => 'Paws::CloudHSM::CreateHsmRequest' };
  class_type CloudHSM_CreateHsmResponse, { class => 'Paws::CloudHSM::CreateHsmResponse' };
  class_type CloudHSM_CreateLunaClientRequest, { class => 'Paws::CloudHSM::CreateLunaClientRequest' };
  class_type CloudHSM_CreateLunaClientResponse, { class => 'Paws::CloudHSM::CreateLunaClientResponse' };
  class_type CloudHSM_DeleteHapgRequest, { class => 'Paws::CloudHSM::DeleteHapgRequest' };
  class_type CloudHSM_DeleteHapgResponse, { class => 'Paws::CloudHSM::DeleteHapgResponse' };
  class_type CloudHSM_DeleteHsmRequest, { class => 'Paws::CloudHSM::DeleteHsmRequest' };
  class_type CloudHSM_DeleteHsmResponse, { class => 'Paws::CloudHSM::DeleteHsmResponse' };
  class_type CloudHSM_DeleteLunaClientRequest, { class => 'Paws::CloudHSM::DeleteLunaClientRequest' };
  class_type CloudHSM_DeleteLunaClientResponse, { class => 'Paws::CloudHSM::DeleteLunaClientResponse' };
  class_type CloudHSM_DescribeHapgRequest, { class => 'Paws::CloudHSM::DescribeHapgRequest' };
  class_type CloudHSM_DescribeHapgResponse, { class => 'Paws::CloudHSM::DescribeHapgResponse' };
  class_type CloudHSM_DescribeHsmRequest, { class => 'Paws::CloudHSM::DescribeHsmRequest' };
  class_type CloudHSM_DescribeHsmResponse, { class => 'Paws::CloudHSM::DescribeHsmResponse' };
  class_type CloudHSM_DescribeLunaClientRequest, { class => 'Paws::CloudHSM::DescribeLunaClientRequest' };
  class_type CloudHSM_DescribeLunaClientResponse, { class => 'Paws::CloudHSM::DescribeLunaClientResponse' };
  class_type CloudHSM_GetConfigRequest, { class => 'Paws::CloudHSM::GetConfigRequest' };
  class_type CloudHSM_GetConfigResponse, { class => 'Paws::CloudHSM::GetConfigResponse' };
  class_type CloudHSM_InvalidRequestException, { class => 'Paws::CloudHSM::InvalidRequestException' };
  class_type CloudHSM_ListAvailableZonesRequest, { class => 'Paws::CloudHSM::ListAvailableZonesRequest' };
  class_type CloudHSM_ListAvailableZonesResponse, { class => 'Paws::CloudHSM::ListAvailableZonesResponse' };
  class_type CloudHSM_ListHapgsRequest, { class => 'Paws::CloudHSM::ListHapgsRequest' };
  class_type CloudHSM_ListHapgsResponse, { class => 'Paws::CloudHSM::ListHapgsResponse' };
  class_type CloudHSM_ListHsmsRequest, { class => 'Paws::CloudHSM::ListHsmsRequest' };
  class_type CloudHSM_ListHsmsResponse, { class => 'Paws::CloudHSM::ListHsmsResponse' };
  class_type CloudHSM_ListLunaClientsRequest, { class => 'Paws::CloudHSM::ListLunaClientsRequest' };
  class_type CloudHSM_ListLunaClientsResponse, { class => 'Paws::CloudHSM::ListLunaClientsResponse' };
  class_type CloudHSM_ListTagsForResourceRequest, { class => 'Paws::CloudHSM::ListTagsForResourceRequest' };
  class_type CloudHSM_ListTagsForResourceResponse, { class => 'Paws::CloudHSM::ListTagsForResourceResponse' };
  class_type CloudHSM_ModifyHapgRequest, { class => 'Paws::CloudHSM::ModifyHapgRequest' };
  class_type CloudHSM_ModifyHapgResponse, { class => 'Paws::CloudHSM::ModifyHapgResponse' };
  class_type CloudHSM_ModifyHsmRequest, { class => 'Paws::CloudHSM::ModifyHsmRequest' };
  class_type CloudHSM_ModifyHsmResponse, { class => 'Paws::CloudHSM::ModifyHsmResponse' };
  class_type CloudHSM_ModifyLunaClientRequest, { class => 'Paws::CloudHSM::ModifyLunaClientRequest' };
  class_type CloudHSM_ModifyLunaClientResponse, { class => 'Paws::CloudHSM::ModifyLunaClientResponse' };
  class_type CloudHSM_RemoveTagsFromResourceRequest, { class => 'Paws::CloudHSM::RemoveTagsFromResourceRequest' };
  class_type CloudHSM_RemoveTagsFromResourceResponse, { class => 'Paws::CloudHSM::RemoveTagsFromResourceResponse' };
  class_type CloudHSM_Tag, { class => 'Paws::CloudHSM::Tag' };

1;
