---
call: DeleteBucketInventoryConfiguration
service: S3
tests:
  - expected: oneoffpaws 
    op: eq
    path: parameters
    key: Bucket
  - expected: tyehshsyye
    op: eq
    path: parameters
    key: id
  - expected: DELETE 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws?
    path: url
    op: eq
  - expected: inventory
    path: url
    op: eq
  - expected: /oneoffpaws
    path: uri
    op: eq
  - expected: inventory
    path: url
    op: eq
  - expected: id=tyehshsyye
    path: url
    op: eq
  - expected: id=tyehshsyye
    path: url
    op: eq
