---
call: GetBucketAccelerateConfiguration
service: S3
tests:
  - expected: '' 
    op: eq
    path: content
  - expected: oneoffpaws 
    op: eq
    path: parameters
    key: Bucket
  - expected: GET 
    op: eq
    path: method
  - expected: https://s3.fake_region.amazonaws.com/oneoffpaws?accelerate
    path: url
  - expected: /oneoffpaws?
    op: eq
    path: uri
  - expected: accelerate
    op: eq
    path: uri
