package Paws::MigrationHub::Types;
  use Type::Library qw/-base/;
  use Type::Utils qw/class_type/;

  class_type MigrationHub_AccessDeniedException, { class => 'Paws::MigrationHub::AccessDeniedException' };
  class_type MigrationHub_AssociateCreatedArtifactRequest, { class => 'Paws::MigrationHub::AssociateCreatedArtifactRequest' };
  class_type MigrationHub_AssociateCreatedArtifactResult, { class => 'Paws::MigrationHub::AssociateCreatedArtifactResult' };
  class_type MigrationHub_AssociateDiscoveredResourceRequest, { class => 'Paws::MigrationHub::AssociateDiscoveredResourceRequest' };
  class_type MigrationHub_AssociateDiscoveredResourceResult, { class => 'Paws::MigrationHub::AssociateDiscoveredResourceResult' };
  class_type MigrationHub_CreatedArtifact, { class => 'Paws::MigrationHub::CreatedArtifact' };
  class_type MigrationHub_CreateProgressUpdateStreamRequest, { class => 'Paws::MigrationHub::CreateProgressUpdateStreamRequest' };
  class_type MigrationHub_CreateProgressUpdateStreamResult, { class => 'Paws::MigrationHub::CreateProgressUpdateStreamResult' };
  class_type MigrationHub_DeleteProgressUpdateStreamRequest, { class => 'Paws::MigrationHub::DeleteProgressUpdateStreamRequest' };
  class_type MigrationHub_DeleteProgressUpdateStreamResult, { class => 'Paws::MigrationHub::DeleteProgressUpdateStreamResult' };
  class_type MigrationHub_DescribeApplicationStateRequest, { class => 'Paws::MigrationHub::DescribeApplicationStateRequest' };
  class_type MigrationHub_DescribeApplicationStateResult, { class => 'Paws::MigrationHub::DescribeApplicationStateResult' };
  class_type MigrationHub_DescribeMigrationTaskRequest, { class => 'Paws::MigrationHub::DescribeMigrationTaskRequest' };
  class_type MigrationHub_DescribeMigrationTaskResult, { class => 'Paws::MigrationHub::DescribeMigrationTaskResult' };
  class_type MigrationHub_DisassociateCreatedArtifactRequest, { class => 'Paws::MigrationHub::DisassociateCreatedArtifactRequest' };
  class_type MigrationHub_DisassociateCreatedArtifactResult, { class => 'Paws::MigrationHub::DisassociateCreatedArtifactResult' };
  class_type MigrationHub_DisassociateDiscoveredResourceRequest, { class => 'Paws::MigrationHub::DisassociateDiscoveredResourceRequest' };
  class_type MigrationHub_DisassociateDiscoveredResourceResult, { class => 'Paws::MigrationHub::DisassociateDiscoveredResourceResult' };
  class_type MigrationHub_DiscoveredResource, { class => 'Paws::MigrationHub::DiscoveredResource' };
  class_type MigrationHub_DryRunOperation, { class => 'Paws::MigrationHub::DryRunOperation' };
  class_type MigrationHub_ImportMigrationTaskRequest, { class => 'Paws::MigrationHub::ImportMigrationTaskRequest' };
  class_type MigrationHub_ImportMigrationTaskResult, { class => 'Paws::MigrationHub::ImportMigrationTaskResult' };
  class_type MigrationHub_InternalServerError, { class => 'Paws::MigrationHub::InternalServerError' };
  class_type MigrationHub_InvalidInputException, { class => 'Paws::MigrationHub::InvalidInputException' };
  class_type MigrationHub_ListCreatedArtifactsRequest, { class => 'Paws::MigrationHub::ListCreatedArtifactsRequest' };
  class_type MigrationHub_ListCreatedArtifactsResult, { class => 'Paws::MigrationHub::ListCreatedArtifactsResult' };
  class_type MigrationHub_ListDiscoveredResourcesRequest, { class => 'Paws::MigrationHub::ListDiscoveredResourcesRequest' };
  class_type MigrationHub_ListDiscoveredResourcesResult, { class => 'Paws::MigrationHub::ListDiscoveredResourcesResult' };
  class_type MigrationHub_ListMigrationTasksRequest, { class => 'Paws::MigrationHub::ListMigrationTasksRequest' };
  class_type MigrationHub_ListMigrationTasksResult, { class => 'Paws::MigrationHub::ListMigrationTasksResult' };
  class_type MigrationHub_ListProgressUpdateStreamsRequest, { class => 'Paws::MigrationHub::ListProgressUpdateStreamsRequest' };
  class_type MigrationHub_ListProgressUpdateStreamsResult, { class => 'Paws::MigrationHub::ListProgressUpdateStreamsResult' };
  class_type MigrationHub_MigrationTask, { class => 'Paws::MigrationHub::MigrationTask' };
  class_type MigrationHub_MigrationTaskSummary, { class => 'Paws::MigrationHub::MigrationTaskSummary' };
  class_type MigrationHub_NotifyApplicationStateRequest, { class => 'Paws::MigrationHub::NotifyApplicationStateRequest' };
  class_type MigrationHub_NotifyApplicationStateResult, { class => 'Paws::MigrationHub::NotifyApplicationStateResult' };
  class_type MigrationHub_NotifyMigrationTaskStateRequest, { class => 'Paws::MigrationHub::NotifyMigrationTaskStateRequest' };
  class_type MigrationHub_NotifyMigrationTaskStateResult, { class => 'Paws::MigrationHub::NotifyMigrationTaskStateResult' };
  class_type MigrationHub_PolicyErrorException, { class => 'Paws::MigrationHub::PolicyErrorException' };
  class_type MigrationHub_ProgressUpdateStreamSummary, { class => 'Paws::MigrationHub::ProgressUpdateStreamSummary' };
  class_type MigrationHub_PutResourceAttributesRequest, { class => 'Paws::MigrationHub::PutResourceAttributesRequest' };
  class_type MigrationHub_PutResourceAttributesResult, { class => 'Paws::MigrationHub::PutResourceAttributesResult' };
  class_type MigrationHub_ResourceAttribute, { class => 'Paws::MigrationHub::ResourceAttribute' };
  class_type MigrationHub_ResourceNotFoundException, { class => 'Paws::MigrationHub::ResourceNotFoundException' };
  class_type MigrationHub_ServiceUnavailableException, { class => 'Paws::MigrationHub::ServiceUnavailableException' };
  class_type MigrationHub_Task, { class => 'Paws::MigrationHub::Task' };
  class_type MigrationHub_UnauthorizedOperation, { class => 'Paws::MigrationHub::UnauthorizedOperation' };

1;
